### ISSUE TITLE
Circulations problem - Item not available(copy)

### ISSUE THREAD

**Issue by dubravica** [Librarika/Issues#100]
I have Circulations problem with books copy.
Anybody have/has same problem?

Screenshot
![librarika](https://cloud.githubusercontent.com/assets/11349350/6525015/6f0bd000-c400-11e4-8b23-d19be08a2888.jpg)

![librarika1](https://cloud.githubusercontent.com/assets/11349350/6525037/bb1a364e-c400-11e4-8ab0-eeacaef3e7ce.jpg)

**Comment by rayhan** [comment]
There is a chance that the book is already reserved or circulated or marked
as is_booked. Please make sure its not already reserved for this period, or
its not already circulated. If eventhing is ok then edit the copy and
un-select "Is Booked" checkbox.

Thanks

On Fri, Mar 6, 2015 at 5:58 PM, dubravica <notifications@github.com> wrote:

> I have Circulations problem with books copy.
> Anybody have/has same problem?
>
> Screenshot
> [image: librarika]
> <https://cloud.githubusercontent.com/assets/11349350/6525015/6f0bd000-c400-11e4-8b23-d19be08a2888.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/100>.
>



-- 
Rayhan

**Comment by dubravica** [comment]
Booked was marked, i've unselected it and now i have green circle. But still have problem with item not available. I have 18 copies of same book/title with the same bar code. 1 book was issued.

Thanks for fast response.

**Comment by dubravica** [comment]
Did you fix my problem?Please help me to fix this problem because its school librarry........

**Comment by dubravica** [comment]
I FOUND PROBLEM .........
ITS AS.NUMBER..........

**Comment by dubravica** [comment]
HOW TO MAKE ACCESION NUMBER WITH SAME BAR CODE?

**Comment by dubravica** [comment]
THE ONE ITEM HAS SAME BAR CODE FOR EVERY COPY.DO I HAVE TO EDIT EVERY COPY WITH DIFFERENT ACCESION NUMBER OR WHAT?

**Comment by dubravica** [comment]
PROBLEM SOLVED........thx .......

**Comment by rayhan** [comment]
Its good to know that it's solved, yes accession number should be unique
for each and every copy of the books. That's why it is called accession
number. Best of luck.

On Saturday, March 7, 2015, dubravica <notifications@github.com> wrote:

> PROBLEM SOLVED........thx .......
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/100#issuecomment-77679108>.
>


-- 
Rayhan

**Comment by dubravica** [comment]
Thx.... best regardsSent from Yahoo Mail for iPhoneAt 07.03.2015. 18:16:11, Md. Rayhan Chowdhury wrote:Its good to know that it's solved, yes accession number should be unique
for each and every copy of the books. That's why it is called accession
number. Best of luck.

On Saturday, March 7, 2015, dubravica  wrote:

> PROBLEM SOLVED........thx .......
>
> —
> Reply to this email directly or view it on GitHub
> .
>


-- 
Rayhan
