### ISSUE TITLE
Problems reserving titles currently on loan

### ISSUE THREAD

**Issue by CanberraBrewers** [Librarika/Issues#101]
Hi, thanks for the great library.

We're having a problem at the moment where books currently on loan (status unavailable) cannot be reserved for future dates. I have tried all sorts of different date combinations but it doesn't work. (Error message "The Item is not available for selected dates" - see screen grab)

Our books are generally borrowed from one monthly club meeting to the next, so a book will probably be on loan and someone wants to request it for the following month, so this is an important feature for us.

Is there something we've set up wrong? I currently have set the default action for request items to "pending" because I want to manually check and prepare requests as they come in - could that be causing the issue?

Regards,
Patrick
![request error mesage](https://cloud.githubusercontent.com/assets/11433194/6610499/49d8c000-c8b4-11e4-96f5-40f36d998006.png)

**Comment by CanberraBrewers** [comment]
bump?

**Comment by mtle8** [comment]
I have the same issue.

**Comment by CanberraBrewers** [comment]
Several months with no response to bug reports, via this forum, or email, and no reply to facebook posts.

I suspect this library is a sitting duck. Very disappointing considering how much time we put into setting up the catalogue.

It's a great product, with a few minor issues - just a shame it seems to have been abandoned with little or no explanation.

**Comment by rayhan** [comment]
This issue will be taken care of in short span of time.

**Comment by CanberraBrewers** [comment]
Still receiving reports that this remains an issue.

Any news yet?

Another bug has come in where "editing" a booking just takes you to a blank web page. Same result in Chrome and Safari.

**Comment by winamp-fan** [comment]
"books currently on loan (status unavailable) cannot be reserved for future dates" - same problem here. Please take a look at this error, future reservations are an important feature in my library.

**Comment by rayhan** [comment]
Taking care of this.

**Comment by rayhan** [comment]
Hopefully this issue is solved, if not, then please open this issue again.
