### ISSUE TITLE
Bar-codes and accession numbers

### ISSUE THREAD

**Issue by cfbroom** [Librarika/Issues#103]
Hi Rayhan,

Our bar-codes are in the format of ####, which adds one (two, three) leading zeroes for the first one thousand (one hundred, ten) books.  When modifying the accession number to match, the system automatically truncates the leading zeros.  Is there any way around this so we can continue to use these bar-code stickers for check-in/check-out?

Thanks,

**Comment by rayhan** [comment]
Well, normally accession number is a numeric field that do not support leading zero. To make this work with leading zero will require change in code level across application which is a bit of works. I don't see a quick way around but will let you know if I find anything.
