### ISSUE TITLE
Problem with the processing of ISBN codes on Smart Add

### ISSUE THREAD

**Issue by ireadacs** [Librarika/Issues#108]
There seems to be an issue with the Smart Add - whenever I try to enter the ISBN code of a book from my library, the site displays the message: "Error in processing data. Please try again." The database does not have a problem with book codes that have already been entered (it includes them as additional copies).

**Comment by blessedbaptist** [comment]
My library has same problem also.

**Comment by rayhan** [comment]
We applied some changes already, do you still have the issue?

**Comment by rayhan** [comment]
That problem has been fixed and hopefully will not be an issue again.
