### ISSUE TITLE
Book title disappered in circulations list

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#109]
While checking in an issued book, which was also reserved by another library member, the book title disappeared in the circulations list and the reservation also disappeared in the library members account. Please take a look at the attached screenshot below. Thanks! 

![reservation bug](https://cloud.githubusercontent.com/assets/10180177/7198202/099774f8-e4ea-11e4-9bf7-d5e3fdbf394f.png)

**Comment by rayhan** [comment]
Still the same issue, I believe it was due to deleting the book from the catalog. Closing this issue, please reopen if it still present.
