### ISSUE TITLE
Reservation duration

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#110]
Our library members find it quite confusing, when under just reserved books, the note "7 hours ago" occur. It is not a major issue, although it is a bit disturbing. Could something be done with it or was this implemented intentionally? You can find the screenshot below. Thanks in advance for your help. 

![bug_hours_add_to_reservation](https://cloud.githubusercontent.com/assets/10180177/7198360/da73af00-e4eb-11e4-9d17-0cc1c05145ca.png)

**Comment by winamp-fan** [comment]
Same bug here, but it says "14 hours ago". Is it a time zone mismatch?

**Comment by rayhan** [comment]
ok, got your point. Yes, its a time zone mismatch.

On Mon, Jul 13, 2015 at 8:38 PM, winamp-fan <notifications@github.com>
wrote:

> Same bug here, but it says "14 hours ago". Is it a time zone mismatch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/110#issuecomment-120951329>.
>



-- 
Rayhan

**Comment by rayhan** [comment]
The issue has been fixed. It should now correctly display the date offset.
