### ISSUE TITLE
Item Search in OPAC- Search by any item type? (enhancement)

### ISSUE THREAD

**Issue by asilbaugh** [Librarika/Issues#112]
I'm wondering if it would be possible to search by all item types, rather than books.

I'm using Librarika as a personal solution for my books, DVDs and video games. While not a terrible issue, but if I don't select "Audio/Visual" (because I cataloged all my DVDs under that), I won't be able to find my items and the users of my OPAC (friends and family) may not realize they have to change the option to "Audio/Visual"

Is there a way to have an "All item types" or something similar as a default search for function?

Thanks so much! Loving Librarika. Only been using it for two days and I'm already hooked!

**Comment by rayhan** [comment]
Yea, will consider this strongly.

**Comment by rayhan** [comment]
Added the option "All".
