### ISSUE TITLE
Password recovery issue 

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#120]
The user has forgotten his password and after having it recovered, he is still not able to access his account and to check his bookings. Please find the screenshot below. 

![librarika account issue](https://cloud.githubusercontent.com/assets/10180177/7652170/e83e8036-fb09-11e4-801b-9cfea6ca328e.png)

**Comment by rayhan** [comment]
It looks like it was an permission issue, not password recovery issue. Please open this issue again if not yet solved.
