### ISSUE TITLE
Unable to search for book items properly 

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#123]
While trying to search for catalog items by selected catogories (e.g. by Author, Title, etc.), the application always delete the search category after trying to see the next part of the catalog list. It also won´t show the second (or 3rd, 4th) part of the list. Please find the screenshots below to see the whole issue. Thanks.

![bug_part_1](https://cloud.githubusercontent.com/assets/10180177/7767652/96f47f12-0074-11e5-82a8-d7065f3144d8.png)
![bug_part_2](https://cloud.githubusercontent.com/assets/10180177/7767653/96f7a00c-0074-11e5-9ae9-0caf1d1e842e.png)
![bug_part_3](https://cloud.githubusercontent.com/assets/10180177/7767654/96fb3bb8-0074-11e5-9dd8-b0b2fef2983c.png)
![bug_part_4](https://cloud.githubusercontent.com/assets/10180177/7767655/9700d4b0-0074-11e5-9b94-3274474066cc.png)

**Comment by 2manybooks** [comment]
I agree that this is a major issue and frustration as well. Please correct this! Thank-you.

**Comment by rayhan** [comment]
This issue has been fixed, please report if you still find any bug.

**Comment by 2manybooks** [comment]
So far this seems to be working better - thank-you!
