### ISSUE TITLE
System logs me out and I cant log back in

### ISSUE THREAD

**Issue by ckbooth** [Librarika/Issues#126]
Hi - I've recently set up a library with Librarika, and I've started to encounter a problem, every so often it logs me out, and when I try to log back in it comes up with this issue, 'Last Action: You are not authorized to access that location. If you see this message again and again please click here to learn more' - now when I 'click here' sometimes it will let me access my library, other times it wont. 
Please can you look into this for me because thought overall Librarika is a good system, this is starting to get quite frustrating.

Thanks

Chris

**Comment by rayhan** [comment]
May I know which browsers are you using? Latest browsers such as Chrome or Firefox should not have such issue.

Regards,
Rayhan

**Comment by ckbooth** [comment]
Thanks mate.

Sent from my Sony Xperia™ smartphone

---- Md. Rayhan Chowdhury wrote ----

Closed #126.

---
Reply to this email directly or view it on GitHub:
https://github.com/Librarika/Issues/issues/126#event-317925245

**Comment by catseye10** [comment]
How about IE browser? I cannot login using Internet Explorer. Kindly help us to IE users to login using Internet Explorer. Thank you.
