### ISSUE TITLE
alphabetical order arrangement for Korean letters - would be helpful

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#127]
Thanks for great library.

We have used this library mainly for Korean books. So, Korean members hope to see Korean alphabetical order arrangement for book title, author, call number, etc.

Thanks again for the work of unfamiliar letters.

**Comment by winamp-fan** [comment]
Similar problem with serbian letters č, ć, đ, ž. They are all being sorted under "A", like some sort of special characters, instead in their alphabetical order.

**Comment by blessedbaptist** [comment]
In Korea, English alphabetical order is followed by Korean alphabetical order. Korean consonant order is briefly this order: ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ. I hope it would be helpful.

**Comment by rayhan** [comment]
Thanks for reporting, will see what we can do here.

**Comment by blessedbaptist** [comment]
We look forward to seeing the order soon: Numbers, English alphabets, and Korean alphabets....
Thank you, Rayhan.

**Comment by rayhan** [comment]
Hi, I have updated the system to enable sorting of unicode characters in Korean consonant. But I need your support in order to check how it works since you know the language. Please let me know if it works. 

Note: It may not work for already entered records, but should work for new records. 

Thanks in advance.

**Comment by blessedbaptist** [comment]
Hi, Rayhan,
Thanks for your work of Korean alphabetical order arrangements. But now we see broken letters for all of Korean letters for our previous works. As you know, we already inputted the information of 1084 books most of which were Korean books. Please let us know how to see our previous works or how to download previous works. 
And, I hope this will help you.
Korean has 14 consonants (and 5 double consonants) orderly: ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.Korean has 10 vowels (and double vowels): ㅏ, ㅐ, ㅑ, ㅒ, ㅓ, ㅔ, ㅕ ㅖ, ㅗ , ㅘ, ㅙ, ㅚ, ㅛ, ㅜ, ㅝ, ㅞ, ㅟ, ㅠ, ㅡ, ㅢ, ㅣ.
One Korean syllable will be formed with the combinations between consonants(C) and vowels(V).Combination:C1 + V (+ C2)
Available 19 C1 (orderly): ㄱ ㄲ ㄴ ㄷ ㄸ ㄹ ㅁ ㅂ ㅃ ㅅ ㅆ ㅇ ㅈ ㅉ ㅊ ㅋ ㅌ ㅍ ㅎAvailable 21 V (orderly): ㅏ ㅐ ㅑ ㅒ ㅓ ㅔ ㅕ ㅖ ㅗ ㅘ ㅙ ㅚ ㅛ ㅜ ㅝ ㅞ ㅟ ㅠ ㅡ ㅢ ㅣAvailable 27 C2 (orderly): ㄱ ㄲ ㄳ ㄴ ㄵ ㄶ ㄷ ㄹ ㄺ ㄻ ㄼ ㄽ ㄾ ㄿ ㅀ ㅁ ㅂ ㅄ ㅅ ㅆ ㅇ ㅈ ㅊ ㅋ ㅌ ㅍ ㅎ
Examples (orderly): 가, 각, 갂, 갃, 간 ... 개, 객, 갞, 갟, 갠 ... 갸, 갹, 갺, 갻, 갼 ... 까, 깍, 깎, 깏, 깐 ... 깨, 깩, 깪, 깫, 깬 ... 꺄, 꺅, 꺆, 꺇, 꺈 .... 힟, 힠, 힡, 힢, 힣. 
Thanks again for the great library system.
Blessings,
Yohan Cho

 
Date: Sun, 1 Nov 2015 00:35:12 -0700

**Comment by blessedbaptist** [comment]
Hi again, Rayhan,
We ordered several Korean books. After new records and check, I will let you know how it works...
Thanks again for the amazing library system.
Blessings,
Yohan
From: blessedbaptist@hotmail.com
To: reply@reply.github.com
Subject: RE: [Issues] alphabetical order arrangement for Korean letters - would be helpful (#127)
Date: Mon, 2 Nov 2015 16:34:00 +0000




Hi, Rayhan,
Thanks for your work of Korean alphabetical order arrangements. But now we see broken letters for all of Korean letters for our previous works. As you know, we already inputted the information of 1084 books most of which were Korean books. Please let us know how to see our previous works or how to download previous works. 
And, I hope this will help you.
Korean has 14 consonants (and 5 double consonants) orderly: ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.Korean has 10 vowels (and double vowels): ㅏ, ㅐ, ㅑ, ㅒ, ㅓ, ㅔ, ㅕ ㅖ, ㅗ , ㅘ, ㅙ, ㅚ, ㅛ, ㅜ, ㅝ, ㅞ, ㅟ, ㅠ, ㅡ, ㅢ, ㅣ.
One Korean syllable will be formed with the combinations between consonants(C) and vowels(V).Combination:C1 + V (+ C2)
Available 19 C1 (orderly): ㄱ ㄲ ㄴ ㄷ ㄸ ㄹ ㅁ ㅂ ㅃ ㅅ ㅆ ㅇ ㅈ ㅉ ㅊ ㅋ ㅌ ㅍ ㅎAvailable 21 V (orderly): ㅏ ㅐ ㅑ ㅒ ㅓ ㅔ ㅕ ㅖ ㅗ ㅘ ㅙ ㅚ ㅛ ㅜ ㅝ ㅞ ㅟ ㅠ ㅡ ㅢ ㅣAvailable 27 C2 (orderly): ㄱ ㄲ ㄳ ㄴ ㄵ ㄶ ㄷ ㄹ ㄺ ㄻ ㄼ ㄽ ㄾ ㄿ ㅀ ㅁ ㅂ ㅄ ㅅ ㅆ ㅇ ㅈ ㅊ ㅋ ㅌ ㅍ ㅎ
Examples (orderly): 가, 각, 갂, 갃, 간 ... 개, 객, 갞, 갟, 갠 ... 갸, 갹, 갺, 갻, 갼 ... 까, 깍, 깎, 깏, 깐 ... 깨, 깩, 깪, 깫, 깬 ... 꺄, 꺅, 꺆, 꺇, 꺈 .... 힟, 힠, 힡, 힢, 힣. 
Thanks again for the great library system.
Blessings,
Yohan Cho

 
Date: Sun, 1 Nov 2015 00:35:12 -0700

**Comment by rayhan** [comment]
Thank you, the work is in progress to fix these, will update you on this in couple of days.

**Comment by blessedbaptist** [comment]
HI, Rayhan,

Thank you for the Korean alphabetical order arrangement. It works well.

**Comment by rayhan** [comment]
Solved.
