### ISSUE TITLE
Rayhan, when is the next version being issued? 

### ISSUE THREAD

**Issue by judithfr** [Librarika/Issues#128]
We are considering creating a Librarika library. Rayhan, when will the next version (1.3?) being installed? Will all the issues in this list be addressed? Should we wait?

Please explain the terms "milestone", "bug", etc. that you use when you post a reply. You might say, e.g., "Milestone for v1.5", or "Bug - fix immediately",  to give an idea of when we will expect the resolution.

Could you please reply to every post to give me a feeling of confidence?

**Comment by rayhan** [comment]
There is no fixed date for next version, currently the base function to operate a library are working fine. There are few small issues, but not a significant one (of course not considering most advance library use case). The use case varies library to library and its difficult to accommodate them all.

So far, we are not displaying any ads on free versions where almost all of our platform libraries are using free versions. So with very little monetary benefit, I need to work on other things.

Regards,
Rayhan

**Comment by judithfr** [comment]
Thanks for your prompt reply.

I wish I could be there to help you.
