### ISSUE TITLE
Search by Call No in Catalog Items screen doesn't work

### ISSUE THREAD

**Issue by grii-melb-lib** [Librarika/Issues#133]
In Catalog Items screen -> if you search the catalog by Call No -> the search doesn't return correct search result.
![capture](https://cloud.githubusercontent.com/assets/12822131/8072781/70d464f2-0f5e-11e5-92bb-3d2d2eb66d6a.JPG)

**Comment by rayhan** [comment]
Fixed.

**Comment by 2manybooks** [comment]
Yay! Thanks!
