### ISSUE TITLE
Unable to Edit bookings

### ISSUE THREAD

**Issue by CanberraBrewers** [Librarika/Issues#135]
Hi, when I go to Edit a booking (to change it's status, or the booking date), the page just goes to a blank screen. Has been this way for several weeks. Same result for Safari and Chrome.

Is it being looked at?

**Comment by winamp-fan** [comment]
The same with me, at dml.librarika.com. Please look at this issue.

**Comment by majdi87** [comment]
its also same with me.

**Comment by rayhan** [comment]
Memory overflow issues, fixed.
