### ISSUE TITLE
Link activation for Author would be better

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#137]
Hi,

Thank you for this amazing library.
On administrator mode, the link for information of publisher is activated.
However,
on member mode, the link for information of publisher has been broken;
On member mode, the link for information of author has been broken.

Thanks again for the work!
Don't work too hard~~~.

Yohan

**Comment by rayhan** [comment]
Thanks for reporting this.

On Saturday, July 18, 2015, blessedbaptist <notifications@github.com> wrote:

> Hi,
>
> Thank you for this amazing library.
> On administrator mode, the link for information of publisher is activated.
> On member mode, the link for information of publisher has been broken.
> On member mode, the link for information of author has been broken.
>
> Thanks again for the work!
> Don't work too hard~~~.
>
> Yohan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/137>.
>


-- 
Rayhan

**Comment by rayhan** [comment]
Yes, its an missing feature that we like to add in future version.
