### ISSUE TITLE
Disappearance of special characters in Description box

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#138]
Hi, Rayhan,

Thanks for this amazing library.
I found some disappearance form with combination of special characters in  "Description" box. In the Description box, the character "<" or ">" can be showed. However the characters will not be showed if the characters are combined like "<>". And again, if one input any word, phrase, or sentence between the character "<" and ">", all of them disappear.  

Although the characters can be showed only in its edit mode, all will not be showed when one submit.

Yohan

**Comment by rayhan** [comment]
Yes, we escape HTML characters for security reason.
