### ISSUE TITLE
Book picture does not save

### ISSUE THREAD

**Issue by adrianocarv** [Librarika/Issues#140]
I can upload a picture for a book, but when a view the book again, the picture was not saved.

**Comment by rayhan** [comment]
Its weird, do you see the picture after a while?

**Comment by rayhan** [comment]
Can you please share a screen shot with us?

**Comment by adrianocarv** [comment]
Hi,

It is attached 4 print sreens in step order.

The book tested is: https://cce-circulante.librarika.com/media/view/313856

My username: adrianocarvYahoo.com.br

Thanks,

Adriano.

**Comment by rayhan** [comment]
Sorry, I can't see any screenshots. You probably added them in your mail response. Can you add them in Github?

**Comment by rayhan** [comment]
A fix has been added. Please confirm me if you read this.

**Comment by adrianocarv** [comment]
Hi Rayhan,

I have read.

Thanks, good work!

Adriano.
