### ISSUE TITLE
Email Addresses

### ISSUE THREAD

**Issue by githeko** [Librarika/Issues#141]
Librarika uses email addresses as user ID but is not able to recognise top level domains such as .institute.
In most cases I have found this to be caused by a regular expression that limits a top level domain name to between 2 and 4 characters. By changing this to [2,10] then the problem goes away.

**Comment by githeko** [comment]
In addition to inability to recognise new domains names inside email addresses, Librarika also rejects newer domain names inside web URL so one can not include an URL such as www.sibi.institute

**Comment by rayhan** [comment]
Yea, domain like .institute are very new, it requires code level update, will be in next bug list.

**Comment by rayhan** [comment]
After an investigation we found that this verification issue is related to the Base Framework we are using. Unfortunately it will take time when we get an update from the framework, will change our code base accordingly.
