### ISSUE TITLE
reached their total booking quota.

### ISSUE THREAD

**Issue by habanbo** [Librarika/Issues#145]
new member created with zero bookings and I get this error .

**Comment by rayhan** [comment]
Is it happening with any member you try with or a specific member?

**Comment by rayhan** [comment]
No response, this is a strange complain, so closing this issue for now. Please re-open if you still have the issue going on.

**Comment by habanbo** [comment]
no response because the product has so many issues and bugs and I found it not ready to be used yet. great start though .

**Comment by rayhan** [comment]
Bugs are continuous process, we try to minimise critical bugs on priority
basis. Everyday hundreds of libraries are active on the platform, compared
to them the number of open bugs are minimal.

On Wednesday, September 30, 2015, habanbo <notifications@github.com> wrote:

> no response because the product has so many issues and bugs and I found it
> not ready to be used yet. great start though .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/145#issuecomment-144291901>.
>


-- 
Rayhan
