### ISSUE TITLE
bulk loading members

### ISSUE THREAD

**Issue by rajmacleay** [Librarika/Issues#146]
Dear Rayhan, Is it possible to "bulk load" library members similar to catalog bulk load?

**Comment by rayhan** [comment]
There is a complexity with bulk loading of members, unless we resolve that complexity, its difficult to tell any deadline.

**Comment by rayhan** [comment]
Good news, we started working on this and will be done shortly.

**Comment by rayhan** [comment]
Added this feature, this is a new feature, hopefully it will be helpful. Let me know if there is any bug since its very new.

**Comment by rajmacleay** [comment]
Thanks Rayhan for your amazing work!
