### ISSUE TITLE
Can not delete users or resend invite.

### ISSUE THREAD

**Issue by Mrcjp03** [Librarika/Issues#148]
I have noticed that one of the users that I invited did not receive email. I have tried to resend but have not been able to get mail through. I also noticed that there is no way to delete users.

**Comment by rayhan** [comment]
Have you found any solution to this? Did you check the spam folder?

**Comment by rayhan** [comment]
You can't delete a user, but can remove all permissions, so the user can't access your library anymore.

**Comment by 2manybooks** [comment]
I was actually going to comment regarding deleting users, then I saw this thread. Thanks for providing this answer. However, it would be ideal if, at some point, you could add an option to delete a user, so we don't end up with users on our lists who are no longer members.

**Comment by himtlibrary** [comment]
i have deleted records, now again i want update record how is possible.

**Comment by rayhan** [comment]
@himtlibrary you library restored, you can do a fresh start now.

**Comment by rayhan** [comment]
Now you can remove users from your library by removing their permissions more easily.
