### ISSUE TITLE
Login from main librarika site question

### ISSUE THREAD

**Issue by ymgrigsb** [Librarika/Issues#149]
I am very new to (and very excited about) using Librarika.  I used the main link to Librarika this morning and signed in from there.  I became very confused at that point because I was expecting it to take me to my library (or give me a list to choose from), but I remained on the main screen.  
It made no sense to be logged into the main link, but I finally realized that I needed to go to my newly created library link and login to get all the menus to work in it.  Is there a way to get to my library when I log in at the www.librarika.com link?

![librarika login](https://cloud.githubusercontent.com/assets/14369814/9980452/b70d5582-5f68-11e5-89ac-fc351546fb96.jpg)

**Comment by rayhan** [comment]
Thanks for reporting, this feature has been added. In order to do this, please click on dropdown menu on the right top corner and select My Libraries from the main site.
