### ISSUE TITLE
Circulations: error when loading a member that doesn't exist anymore.

### ISSUE THREAD

**Issue by angelitoes** [Librarika/Issues#15]
From the table of circulations you can access to the members shown in the column Member. If you do so and the member has been previously deleted, an error appears.
Solutions:
1. Don't allow to access the members that don't exist now (by not showing the link, only the name of the member)
2. Allow clicking the member in the table and explain the situation with a apropiate message.

![member error](https://f.cloud.github.com/assets/6534638/2125478/f02b6b6e-9251-11e3-986d-0cd3acd8f7d2.PNG)

**Comment by rayhan** [comment]
This has been fixed already.
