### ISSUE TITLE
Cannot delete member

### ISSUE THREAD

**Issue by ymgrigsb** [Librarika/Issues#150]
I added a member (myself) with a different email address.  When I received the invitation email I clicked on it not realizing I was still logged in as admin.  I never saw the screen asking me to enter a password and continue.  On the admin screen, I saw the message "a member has joined".

Now, I cannot login using that member email (probably because the password was never set.) It errors with email not recognized when I try to do the Forgot Password process.  The join link in the email no longer works because it thinks the member has joined.  And it will not allow me as administrator to delete the member.  I am in library 3085, ID 18449, I was at least able to set the member to inactive.  How can I either fix the password or delete and start over?

**Comment by rayhan** [comment]
There is a option to delete member, please go to Circulations -> Members -> Edit -> Delete Member. Let me know what happen when you do that.

**Comment by ymgrigsb** [comment]
I have, that's where I get the message afterwards: Member  was not deleted. It may have something to do with the member having the same name as me...see pics.
Yvonne

**Comment by rayhan** [comment]
I know where you are having the problem: 

You needed to edit the member and Deselect Enable Login, Select Remove Login. Then try deleting member.

BTW, I have removed the member for you.

Cheers!
