### ISSUE TITLE
Barcode Scanner Issues

### ISSUE THREAD

**Issue by stagetech** [Librarika/Issues#151]
Hello! When I go to scan an user, it works fine, but when I scan a book, it says ""Accession no is required!" Does anyone have a solution for this? I know that it works when I manually enter it, but not when I scan something.

**Comment by rayhan** [comment]
In which page are you getting this error?

**Comment by stagetech** [comment]
When I am on the circulation screen/pop up. I will scan a card, that inserts the member's info. But then when I go and scan the allocation, it says "allocation no. Required"

**Comment by rayhan** [comment]
Fixed.

**Comment by rayhan** [comment]
It has been fixed permanently now.
