### ISSUE TITLE
Importing book list does not work

### ISSUE THREAD

**Issue by habanbo** [Librarika/Issues#152]
when importing csv file of many books, the books are not added to the library , although , all the authors of those books are added to the authors sections.

**Comment by rayhan** [comment]
Looks like you have problem with the csv file format. Try with correct csv
format, when you are ready I will cleanup ur entire catalog.

On Wednesday, September 30, 2015, habanbo <notifications@github.com> wrote:

> when importing csv file of many books, the books are not added to the
> library , although , all the authors of those books are added to the
> authors sections.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/152>.
>


-- 
Rayhan

**Comment by habanbo** [comment]
the csv file was provided by you via email , weeks earlier, the library is called Taawon Public Libraries

**Comment by rayhan** [comment]
Will check this out and let you know shortly.

**Comment by habanbo** [comment]
any news?

**Comment by rayhan** [comment]
I have reviewed your CSV file myself and found following issues:
- The title field should be first letter capital as Title, same for version field to Version, other than the file is ok, and I could import the file for you. 

But, I'm sorry we don't support non English numbers as ISBN and ISBN13 field, you can either remove data from these two field or put 10 or 13 digit numeric value to them accordingly.

Regards,
Rayhan
