### ISSUE TITLE
Sorry, member has reached their total booking quota.

### ISSUE THREAD

**Issue by bmssinfo** [Librarika/Issues#155]
Hello,
I am new in librarika. I added couple patrons and titles to try it out. I tried to circulate an item but it says "Sorry, member has reached their total booking quota." for any user I have.
Please help.
Thanks
Mevlut
![image 16](https://cloud.githubusercontent.com/assets/14931392/10232815/e9c063a4-6858-11e5-86ba-33ad24bb3820.png)

**Comment by rayhan** [comment]
Please go to the Manage -> Preferences and save your preferences. Hopefully it will work instantly. Let me know.

**Comment by bmssinfo** [comment]
Thanks, It works now. I only needed to click save !
