### ISSUE TITLE
Library email already taken

### ISSUE THREAD

**Issue by sagarjoshi3183** [Librarika/Issues#159]
Hi,

I had created a library for my organization on Librarika. I had used my own email id as library email. However, I had to delete the library because the entire catalog had to be re-hauled and a few other changed had to be made. I tried to make a new library again but I cannot use my email id now. Is there a workaround for the same? Can you remove my email id from records so that I can add it again for a new library?

Email ID (also used a library ID): sagar.joshi@operasolutions.com
Name of the (deleted) library: Opera Solutions India Office

Thanks in advance

**Comment by rayhan** [comment]
We can cleanup your entire catalog if you want, but its quite difficult to remove your email address and let you create another library.

**Comment by sagarjoshi3183** [comment]
Actually I have already deleted the library.

**Comment by rayhan** [comment]
Please try now, removed email id form the records.
