### ISSUE TITLE
accession no. Item not found!

### ISSUE THREAD

**Issue by habanbo** [Librarika/Issues#161]
when trying to check out a book, if I put accession number of one the manually added books ( added only 3 manually ) it works and I can check out a book. but if the accession number is bigger than 3 ( I added more than a thousand books by importing  CSV ) it says  Item not found!.

please check why, my library name is Taawon Public Libraries

**Comment by rayhan** [comment]
The reason for that was due to the mix-up with Arabic character in Accession Number field. Hope you have already figured this out as we have mailed you on this matter.
