### ISSUE TITLE
Circulation Bug

### ISSUE THREAD

**Issue by bmssinfo** [Librarika/Issues#162]
I am trying to circulate items from 'circulate item' button. when I scanned student Id and the book's barcode it shows it on left upper corner of browser but says item not found. please check screenshot. 

![image 14](https://cloud.githubusercontent.com/assets/14931392/10487939/56affc12-7264-11e5-80a6-ba755dc2f886.png)

**Comment by rayhan** [comment]
The access number that you entered is wrong you entered Call number instead of ASN# that is 1290. Btw in which browser are you getting the dropdown cutoff?

**Comment by bmssinfo** [comment]
I am using chrome. I tried it with Firefox and explorer.

It is not the ASN#, ISBN or call # issue. I am using a scanner to scan student ID 's and Book ISBN #/ Call # to enter them into those boxes.  Student ID is  being found with no problem but the book info popping up at the background in the grayed area which won't allow me to click on.

![image 19](https://cloud.githubusercontent.com/assets/14931392/10585188/2e836982-7664-11e5-9859-2a8bacd645c4.png)

**Comment by rayhan** [comment]
Ok, what happen when you enter the accession number manually instead of using scanner? Is the same? Since, I can't regenerate it here, I need a bit of information.

**Comment by bmssinfo** [comment]
when I enter ISBN manually it shows up with no problem.

![image 20](https://cloud.githubusercontent.com/assets/14931392/10585648/3c0e6762-7666-11e5-8716-3351f2805291.png)

**Comment by rayhan** [comment]
Thank you, now it makes sense. I was trying Manually all the time. Will update you shortly.

**Comment by rayhan** [comment]
Was able to reproduce the issue, it seems the scanner automatically call the form submit action after inserting the number. Is there any configuration setting that you can use to stop automatic form submission. 

In the meantime, I am working on to fix this issue and I will let you know when its done.

**Comment by bmssinfo** [comment]
I am not sure if I can configure scanner, but I know it scans and clicks "Enter" button at the same time.
My staff will scan ISBN and backspace the last digit and enter again manually to bypass the problem till you find a fix.
Thanks

**Comment by rayhan** [comment]
The issue has been fixed, please refresh browser cache or refresh couple of times to see the changes.

**Comment by bmssinfo** [comment]
Thank you!
