### ISSUE TITLE
Multiple books checkout option

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#168]
I WOULD like to know how to check out multiple books out to a member.

**Comment by rayhan** [comment]
Check-outs needs to be done one by one for now. We are going have multiple checkout soon but can't give you any deadline at this moment.

**Comment by rayhan** [comment]
Yes, finally we have the ability to checkout multiple items.

**Comment by shiv379** [comment]
Could you explain how this is done please? Maybe add it to the FAQ?
