### ISSUE TITLE
Changing all member Emails?

### ISSUE THREAD

**Issue by bmssinfo** [Librarika/Issues#169]
Am I be able to change all members' emails? Should I try to upload members again with right email addresses, so system updates them?

Thanks

**Comment by rayhan** [comment]
Bulk updating of member email is not possible. You may delete all members then import them again.

**Comment by bmssinfo** [comment]
How do I delete them all at once?

**Comment by rayhan** [comment]
I can remove them for you? Should I remove them all?

On Monday, 2 November 2015, bmssinfo <notifications@github.com> wrote:

> How do I delete them all at once?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/169#issuecomment-153033787>.
>


-- 
Rayhan

**Comment by bmssinfo** [comment]
I think I hold on to it now. because we are circulating 250 books to those users currently.

Thanks
