### ISSUE TITLE
Bulk Member Upload Issue

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#170]
Hi,

I was attempting to upload a bulk member file when I realised I had more than 500 members in my CSV. I clicked the Back to Import button, corrected my data file, and attempted to upload the file. However the next screen showed the data from my original file. Even after clearing my browser cache, renaming the file, and logging in from an icognito window, any attempt to upload a bulk member file showed the data from my first upload.

**Comment by rayhan** [comment]
The cache is on server for an hour tagged with your User ID, but the cache should be updated when you import a new version of CSV. Can you please email me the CSV file so that I can take a look while I am checking for any bugs.

**Comment by badhrij** [comment]
Please find the csv attached.
Thanks for the quick response.

:)
Badhri

thinkchangeindia.org
<http://social.yourstory.com/category/think-change-india/> ||
blacknike.blogspot.com ||
comedydaze.blogspot.com || ngopost.org ||

**Comment by rayhan** [comment]
@Badhri please send the csv file at info@librarika.com in a separate email. I did not receive any attachment here.
