### ISSUE TITLE
Unable to import members without email

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#173]
Hi,

I've just tried to import a csv file with members who have "Enable Login" as "No", and no value in the "Email" column, however every record is showing an error on the preview of "Email exists".

**Comment by badhrij** [comment]
Hi. Not sure what your statement means. Are you able to see the issue or
doest it work fine at your end? Is my csv format correct and complete?  I
am able to see the preview. But when i say confirm and go to next step it
says internal error.

**Comment by shiv379** [comment]
Short version: if I leave the email address column empty my bulk import fails (shows errors at preview)

**Comment by badhrij** [comment]
Thanks. But why are you trying such a thing?
My member login has email filled up. I am a member with "enable login"
checked.
If you leave these intact are you able to upload the csv?
I attach two pictures (keeping info@librarika.com) in cc
"works.jpg" shows that the csv is recognized properly.
"fails.jpg" shows that when I press "process upload" it shows internal
error.
Hope this helps.
Thanks.

:)
Badhri

thinkchangeindia.org
<http://social.yourstory.com/category/think-change-india/> ||
blacknike.blogspot.com ||
comedydaze.blogspot.com || ngopost.org ||

**Comment by rayhan** [comment]
@badhrij 

Yes, you CSV file is ok and its working now. There was an issue with call_no as null field that has been fixed. Please try now.

**Comment by rayhan** [comment]
@shiv379 checking this empty email things out.

**Comment by rayhan** [comment]
@shiv379 can you please email me the CSV file you are using at info@librarika.com

**Comment by rayhan** [comment]
@shiv379 hopefully fixed. Please confirm me.

**Comment by badhrij** [comment]
works thanks a lot.
There are other things. But I will file separate tickets for that.
I would like to commend you on your excellent support. Awesome work on an
awesome one-of-a-kind software!

:)
Badhri

thinkchangeindia.org
<http://social.yourstory.com/category/think-change-india/> ||
blacknike.blogspot.com ||
comedydaze.blogspot.com || ngopost.org ||

**Comment by shiv379** [comment]
I think there's a clash with issues here - this issue should not have been closed yet as has not been resolved. 

I'm importing members without email addresses as these users will not be able to log in themselves but may have books checked out to them by the librarian. As this is a primary school most of the children who are members simply do not have an email address of their own. I'm afraid I cannot send my csv file due to child protection, however I will try to create a dummy file with the same issue. 

Thank you for your excellent support!

**Comment by rayhan** [comment]
@shiv379 the problem with empty email address has been fixed. Just check this and confirm. You don't need to send me the CSV.

**Comment by shiv379** [comment]
Have just checked, is working fine now thank you!
