### ISSUE TITLE
Greek alphabet

### ISSUE THREAD

**Issue by ipsilantis** [Librarika/Issues#176]
Hi there,

I would like to know if the Greek alphabet is supported by your system. We have started a small library but most of our entries in Greek have been messed up.

Thanks in advance

**Comment by rayhan** [comment]
When did you add this entries, yesterday we made some changes that should
improve overall handling of Unicode character.

On Monday, 2 November 2015, ipsilantis <notifications@github.com> wrote:

> Hi there,
>
> I would like to know if the Greek alphabet is supported by your system. We
> have started a small library but most of our entries in Greek have been
> messed up.
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/176>.
>


-- 
Rayhan

**Comment by rayhan** [comment]
Yes, some characters messed up. Working on the fix..

**Comment by rayhan** [comment]
Can you please give me Media ID of one records with original text and messed up text for us to compare.

**Comment by ipsilantis** [comment]
Hey,

We added them some two days ago. At  the beginning the system saved them in perfect format but yesterday it appeared like this: the title Παλαιά Θεσσαλονίκη (Old Salonica), media id 453850, appears as Î Î±Î»Î¹Î¬ Î˜ÎµÏƒÏƒÎ±Î»Î¿Î½Î¯ÎºÎ· 

Thanks!

**Comment by rayhan** [comment]
Thank you, the work is in progress to fix these, will update you on this in couple of days.

**Comment by ipsilantis** [comment]
ok, thanks. I'll be waiting.

**Comment by rayhan** [comment]
Solved. please don't forget to confirm this.

**Comment by ipsilantis** [comment]
Thank you for what you did, everything it's fine but tags are still like this Î”ÏÎ¬Î¼Î±, Î¹ÏƒÏ„Î¿ÏÎ¯Î±, 
If you can fix it, do it, if you can't  it's fine.
