### ISSUE TITLE
letter

### ISSUE THREAD

**Issue by dubravica** [Librarika/Issues#178]
croatian letters is buged no č,ž,ć,š,đ,dž,there is only thing like this TIÅ INA,DRAÅ½EN KOMÅ IÄ†

**Comment by rayhan** [comment]
We changed the database to support full unicode characters including
sorting in Korean alphabets, that caused some existing characters to be
messed up. Please give me the Media ID of one of your bugged record with a
correct record information so that I can compare the bugged title with
original title.

Thanks in advance for your help.

On Tue, Nov 3, 2015 at 12:19 PM, dubravica <notifications@github.com> wrote:

> croatian letters is buged no č,ž,ć,š,đ,dž,there is only thing like this
> TIÅ INA,DRAÅ½EN KOMÅ IÄ†
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/178>.
>



-- 
Rayhan

**Comment by blessedbaptist** [comment]
Hi, Rayhan,

Korean letters have been messed up also.  It appears like this: the title 완전 소중한 비밀: 성공을 찾아가는 7가지 (in Korean), media id 442585, appears as ì™„ì „ ì†Œì¤‘í•œ ë¹„ë°€: ì„±ê³µì„ ì°¾ì•„ê°€ëŠ” 7ê°€ì§€

Don't work too hard,

Blessings,

Yohan

**Comment by rayhan** [comment]
Thank you, the work is in progress to fix these, will update you on this in couple of days.

**Comment by dubravica** [comment]
| Id | Date | To | ASN No | Member | Title | ISBN | Call No | Copy | Status | Actions |
| 34871  | Nov 05, 2015  | Nov 26, 2015  | 1042  | MONIKA AKRAPOVIÄ† | SLAVONSKA Å UMA,MOJ DJED,OPRAVA,TENABranch: Main | 9789530612112  |   | 1  | Issued  | Check-In |

 
This is wrong versionRight version is down

| Id | Date | To | ASN No | Member | Title | ISBN | Call No | Copy | Status | Actions |
| 34871  | Nov 05, 2015  | Nov 26, 2015  | 1042  | MONIKA AKRAPOVIĆ | SLAVONSKA ŠUMA,MOJ DJED,OPRAVA,TENABranch: Main | 9789530612112  |   | 1  | Issued  | Check-In
 |



     On Wednesday, November 4, 2015 1:35 PM, Md. Rayhan Chowdhury <notifications@github.com> wrote:
   

 Thank you, the work is in progress to fix these, will update you on this in couple of days.—

**Comment by rayhan** [comment]
Solved. please don't forget to confirm this.

**Comment by blessedbaptist** [comment]
Thank you for the work, but would you check "Tags"

**Comment by dubravica** [comment]
Thx , problem is solved!!!!                         Best regards!!!!!!Sent from Yahoo Mail for iPhoneOn 07.11.2015. 08:47:38, Md. Rayhan Chowdhury wrote:Closed #178.

**Comment by blessedbaptist** [comment]
Hi, Rayhan,

Thanks for the fix. But still in some parts (specifically in the blanks "Tags," "Remarks," and "Description,") Korean letters have been messed up. It appears like this: 
Tags (probably) 예배 (in Korean), media id 278814, appears as ì˜ˆë°°
Remarks (probably) 1판 14쇄 - 2009년 4월 25일 (in Korean), media id 278814, appears as 1íŒ 14ì‡„ - 2009ë…„ 4ì›” 25ì¼
Description appears as ë³¸ ë„ì„œê´€ì€ í…Œë„¤ì‹œì£¼ ë©¤í”¼ìŠ¤ì‹œ ì§€ì—­ì— ìœ„ì¹˜í•œ ë³µëœ êµíšŒ ë„ì„œê´€ìœ¼ë¡œì„œ, ê¸°ë…êµ ì‹ ì•™ê³¼ ì—°ê´€ëœ ì„œì ë“¤ë¿ë§Œ ì•„ë‹ˆë¼ ë‹¤ì–‘í•œ ë¶„ì•¼ì˜ í•œê¸€ ì„œì ë“¤ê³¼ í•œêµ­ê³¼ ê´€ë ¨ëœ ì„œì ë“¤ì„ ì†Œìž¥í•˜ê³  ìžˆìŠµë‹ˆë‹¤.

Blessings,

Yohan

![tags](https://cloud.githubusercontent.com/assets/12655219/11025307/1beb70c0-865f-11e5-98f6-ac36957f539e.png)

![remarks](https://cloud.githubusercontent.com/assets/12655219/11025309/249a018c-865f-11e5-9f65-a1fd0c2fa7a1.png)

![description](https://cloud.githubusercontent.com/assets/12655219/11025311/2d2bde42-865f-11e5-982c-5dc5327f687b.png)
