### ISSUE TITLE
Images for books and ISBN 13 issue and other suggestions

### ISSUE THREAD

**Issue by sagarjoshi3183** [Librarika/Issues#179]
Hi,

I've added the entire catalog of around 350 books to the library. I then realized that apart from 1 or 2 books, none other show the image of the book. On seeing the description of the books, I also found that all the books have ISBN-13 info missing. Upon checking the uploaded file I realized the column heading to be ISBN13 instead of ISBN 13. I've a personal library elsewhere where all the books have proper images with them but it is really cumbersome to add images for over 300 items one by one. Here are a few things I've tried and was wondering:
1. Tried adding the book via smart add to check if it then shows the book image but it did not recognize the isbn13 no even though its a valid one. (9788183520706 Animal Farm)
2. I was wondering if I should add the entire database again with the column title updates as ISBN 13 instead of ISBN13 but I will have to delete all 350 books one by one which again is a very tedious task. Is there a way to remove the entire catalog at once?
3. I have the page no info available with me for the books and librarika platform has the option of adding the info (but manually). If there is a way to add this as a column in the csv itself.
4. As a user added by an administrator to a library, I have the option of seeing parts of database on various parameters (category search, keyword search, top collection, recent collection, A-Z etc). But there is no option for me to just scroll through the entire catalog at once. I realize that various parameters help find things much better but for a new user checking out the library for the first few times, a casual browsing option allowing them to see whatever is available might be really useful.
5. I tried adding the company logo and it shows as information has been updated but the logo does not change. The size of the logo I am using is 200X200 px (as suggested) and around 100 kb. Does it also have to do anything with image size in kb?

Thanks

**Comment by sagarjoshi3183** [comment]
Issue no. 1 rectified on its own.

**Comment by rayhan** [comment]
Will update you shortly. Need to investigate them all.

**Comment by sagarjoshi3183** [comment]
Hi Rayhan,

Can you please clear the catalog database in the meanwhile so that I can add them manually again and start the circulation? Rest of the issues can be dealt with at a later time but this one thing will help us get the library running to begin with.

Thanks

**Comment by rayhan** [comment]
Catalog cleaned up. Thanks.

On Mon, Nov 16, 2015 at 11:55 AM, sagarjoshi3183 <notifications@github.com>
wrote:

> Hi Rayhan,
>
> Can you please clear the catalog database in the meanwhile so that I can
> add them manually again and start the circulation? Rest of the issues can
> be dealt with at a later time but this one thing will help us get the
> library running to begin with.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/179#issuecomment-156924004>.
>



-- 
Rayhan

**Comment by sagarjoshi3183** [comment]
Hi Rayhan,

A possible enhancement suggestion following from above:

Can we have a full catalog search and a category based search on the OPAC page itself?
The full catalog is for the users who want to casually browse through the whole catalog without any particular book in mind. The category based search will help those who have some sort of idea in mind about what they wanna look for.

Thanks in advance :)
