### ISSUE TITLE
Unable to access catalog

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#180]
When accessing the catalog through the dashboard I get the message

"Error: An Internal Error Has Occurred."

https://XXX.librarika.com/media

**Comment by rayhan** [comment]
Hi,

Its fixed, thanks for reporting. ☺

Regards,
Rayhan

On Tue, Nov 3, 2015 at 8:52 PM, shiv379 <notifications@github.com> wrote:

> When accessing the catalog through the dashboard I get the message
>
> "Error: An Internal Error Has Occurred."
>
> https://XXX.librarika.com/media
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/180>.
>



-- 
Rayhan
