### ISSUE TITLE
No option to search OPAC by accession number

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#181]
Hi,

There does not seem to be a way to search the catalog (as a member) by accession number. On the page https://XXX.librarika.com/search it is not one of the drop-down options.

**Comment by rayhan** [comment]
Do we need this? Should not ASN number be limited to library internal people?

**Comment by shiv379** [comment]
I thought of a reason before but I can't remember it now so can close this until I think of a decent reason again. Sorry!

**Comment by rayhan** [comment]
Nice.
