### ISSUE TITLE
special characters are changed 

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#182]
There is a bug regarding š,č,ž,ý,á,í,é characters, which are used in the slovak language. The names of the library members were writen correctly, now there are mistakes. See the screenshot. Thanks.  
![2015-11-03 23_20_25-librarika_ members](https://cloud.githubusercontent.com/assets/10180177/10923505/a5d84c18-8281-11e5-9dcf-940b51bbcd0c.png)

**Comment by rayhan** [comment]
Thank you, the work is in progress to fix these, will update you on this in couple of days.

**Comment by rayhan** [comment]
Solved. please don't forget to confirm this.

**Comment by MonikaIness** [comment]
yes, it is fixed. Thanks!
