### ISSUE TITLE
Quick Return books issue

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#183]
Hi,

We have leading 0s on our Accession Nos and this isn't a problem in most places, however on the quick return dialogue it doesn't work (we have to scan the Accession No then delete the leading 0s before the system will recognise it).

**Comment by rayhan** [comment]
It should now be fixed.

**Comment by shiv379** [comment]
Hi, 
I had a problem with this earlier - not sure if a one off or a bug. When using the quickreturn it wouldn't accept the accession number as typed until I had chosen the book from the pop up that appears.
