### ISSUE TITLE
Payment Options

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#184]
Hi,

Is there any possibility of adding an annual subscription option? It would be a lot easier for us to manage as an organisation to be able to subscribe for a year ahead rather than monthly payments.

**Comment by rayhan** [comment]
Agree, we have a plan to move to yearly plan for all. However, we can unlock yearly plan for you, just specify your library name and the plan you want to upgrade to. It will appear your my plan sections for Yearly upgrade instead of Monthly.

**Comment by rayhan** [comment]
Yearly plan activated.
