### ISSUE TITLE
User permissions unclear

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#185]
Hi,

The differences between members / privileged members / library staff / library admin / employee is unclear, and there seems to be no explanation of what the differences in permissions for each of these is. Could this please be added to the system / help? 

Going forward it would be really useful to be able to set the permissions for the Library Staff role at least (for example we would not want library staff to be able to access the Users page (or really anything under the Manage tab), or anything under the Others page. Essentially our Staff role is for "staff" (Library Prefects in our case) to be able to check books in and out to other users.

**Comment by rayhan** [comment]
Nice point, will add a detail clarifications  for them all.

**Comment by shiv379** [comment]
Thank you :)

**Comment by rayhan** [comment]
Added a write up for this: https://librarika.com/spages/librarika-permission-explained . Is this clear now?

**Comment by ecorm** [comment]
The "Official" role is not explained in the write-up.
