### ISSUE TITLE
Is Active / Is Circulated / Is Published difference unclear

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#187]
Hi,

Would it be possible to put an explanation of what each of these is, and the differences between them? Maybe with a "?" next to each one with a popup tooltip?

**Comment by rayhan** [comment]
Correct, will have them.

**Comment by shiv379** [comment]
Thx :)

**Comment by rayhan** [comment]
Done.

**Comment by shiv379** [comment]
Perfect! Thanks!
