### ISSUE TITLE
Add "Illustrator" to Authors type

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#188]
Hi,

Could you possibly add an option for Illustrator for the author types? (Currently Author / Co-Author / Editor). This is useful for childrens books and graphic novels.

**Comment by rayhan** [comment]
Not clear, can you give a specific example or more details?

**Comment by shiv379** [comment]
For example this book: http://www.amazon.co.uk/Rabbit-Lovely-Present-Red-Classics/dp/0099432951/ref=sr_1_8?ie=UTF8&qid=1446886891&sr=8-8&keywords=sendak

Illustrated by Maurice Sendak. A lot of people know Sendak from Where the Wild Things Are, but without an Illustrator field on the database this particular book would not show up when you search him (unless you write him down as co-author which would be incorrect). Or a graphic novel example here: http://www.amazon.co.uk/Batman-Vol-Zero-Year-Dark-ebook/dp/B00MV1NYEK/ref=sr_1_6?s=books&ie=UTF8&qid=1446887047&sr=1-6&keywords=batman

**Comment by rayhan** [comment]
Done.

**Comment by shiv379** [comment]
Thanks :)
