### ISSUE TITLE
Option to disable / customise Buy Online panel

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#193]
Hi,

Since our library is used by primary school from ages 5+ we avoid external links where possible for child safeguarding reasons. Could an option be added to the site settings to disable the Buy Online panel? Other libraries may wish to have the option to customise this list also - for example to disable certain links, to link to country-specific online stores, and to set the currency symbol.

**Comment by rayhan** [comment]
Added the show / hide control on "Library Preferences" section. This is going to be a pro feature. Will add the ability to add custom selection of country specific stores later.

**Comment by shiv379** [comment]
Thanks - another incentive for us to buy a paid programme! (I'm working on convincing the school ;))

Noticed a typo on the new addition to preferences - "offering serivces to"

**Comment by rayhan** [comment]
Fixed typo. Yes, incentivization is necessary to run a smooth system.
