### ISSUE TITLE
Database A-Z Including Korean Consonants Would Be Helpful

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#195]
Hi, Rayhan,

Thanks for the great library.
Database A-Z is only for English letter and number. Adding Korean consonant letter would be helpful for Korean libraries.
Korean 14-consonant letters: ㄱ (with ㄲ), ㄴ, ㄷ (with ㄸ), ㄹ, ㅁ, ㅂ (with ㅃ), ㅅ (with ㅆ), ㅇ, ㅈ (with ㅉ), ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.
Or Korean 19-consonant letters: ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.

Don't work too hard,
Blessings,

Yohan

**Comment by rayhan** [comment]
Not possible until we have interface specific to korean language. Now marking as not-possible, will go through this again in the future.

**Comment by blessedbaptist** [comment]
Thanks for the mention
