### ISSUE TITLE
Blank Length Longer - would be helpful

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#196]
HI, Rayhan,

Thanks for the great library,
The "Accession‎ No" blank box of pop-up window for "Edit Copy" seems to show only 10 letters.
American library system has 14 letters for accession number. It would be helpful to make the blank longer.
![screenshot 1](https://cloud.githubusercontent.com/assets/12655219/11014678/e2467922-8506-11e5-8d97-642f5c3e94d0.png)

**Comment by rayhan** [comment]
done

**Comment by blessedbaptist** [comment]
Thanks for the work
