### ISSUE TITLE
Email reminder for books already checked in...

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#200]
Hi,

I received an email reminder for books that have already been checked in. Also the reminder was sent to "Test Member" which is the old name of the account I was first using.

----

Reminders for Reservation / Due / Overdue Items 
Hi Test Member,

Being part of our integrated library system at Librarika, please be updated on following deadlines related to your booking activities. 
Overdue Item(s):
Title	Due Date
Cinderboy (Seriously Silly Supercrunchies)	Mon Nov 02, 2015
The Man Who Wore All His Clothes	Mon Nov 02, 2015
Into the Woods	Mon Nov 02, 2015

Click here to access the library now.

If you got this email by mistake, or you did not join the library, please simply ignore this message.

**Comment by rayhan** [comment]
I how why it happened, I was working on a back dated backup server for fixing some character encoding bug. All encoding issues have been fixed, but during the time that backup system was up, it sent email reminder form that old dated data set.

Hope it didn't affect the live server. Thanks for reporting, your information was really helpful, specially that part "which is the old name of the account I was first using.".

**Comment by shiv379** [comment]
Thanks :)
