### ISSUE TITLE
Circulations Quicksearch not working

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#201]
Hi,

Just tried to use the Quicksearch in circulations, and nothing seemed to happen. Was searching for part of a title (which I know has been circulated and returned) but the list did not filter as expected.

**Comment by rayhan** [comment]
Quick search works for Accession No, Call No and ISBN only. Suitable for barcode scanner to quickly scan and filter the booking.

**Comment by shiv379** [comment]
Ah thanks, I see you've changed the field to make that clearer :) Thank you!
