### ISSUE TITLE
Move "Edition" to Copies details, add "Format"

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#204]
Hi,

Something I've been struggling with is the Edition details - we have multiple copies of books which can be different editions and formats and at the moment we have to create separate book entries for each one which causes a lot of duplicates in searches.

Could the Edition field be moved to the Copy details, and could a format field be added too, please? 

The relevant formats (taken from Goodreads) are:
Paperback
Hardcover
Mass Market Paperback
Library Binding
Board Book
Unbound
Spiral-Bound

**Comment by shiv379** [comment]
On a similar note - Published / Circulation would make more sense attached to individual copies than the high level record wouldn't they?

e.g. If I have two copies of a book, one currently active in the main library but one not (maybe it's a reference only copy so cannot be circulated, or in the case of my setup it could be assigned to a different branch - classroom collection - so I wouldn't want that particular copy showing up in OPAC searches). I am assuming that "Active" is used when you want to remove a book from the shelves completely, for example if it need repair or replacement, that kind of thing.

**Comment by rayhan** [comment]
1) Edition and Format make sense, will do the changes 
2) You are right, we need published and circulations on copy too for more fine grained control. Will be considered.

**Comment by shiv379** [comment]
Perfect, thank you XD

**Comment by rayhan** [comment]
For format, you already have a field name Bindings.

**Comment by shiv379** [comment]
I think I'm being blind! Where is the binding field?

**Comment by rayhan** [comment]
No you were not, it was me. Added those additional fields.
