### ISSUE TITLE
Browse by  branch?

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#205]
Hi,

Is there any way for administrators to filter the catalog by branch? I thought there was but I can't find it now! I'm trying to set all books that are not in our main branch to published=false :)

**Comment by rayhan** [comment]
Added an experimental filter option by branch in Catalog page at the bottom. Need to see how effective this is.

**Comment by shiv379** [comment]
Looking good!

**Comment by petrfaitl** [comment]
Has "Browse by Branch" now gone away? It would be great to be able to filter out branches.
