### ISSUE TITLE
Circulation disabled error

### ISSUE THREAD

**Issue by jgibsonfaber** [Librarika/Issues#206]
Hello,

I have enabled circulation for all items in my catalog and when I go to check them out it says "curculation disabled for this title"

**Comment by rayhan** [comment]
Hi, in order for circulation to work, item must be in active state, are they active? If so, then pleas share me the Item ID and accession number so that I can check.

**Comment by grii-melb-lib** [comment]
I am encountering the same error. The items are active and circulation is enabled.
Item Id =  459480 Accession number = 1155
Another book:
Item Id =  253744 Accession number = 549

**Comment by rayhan** [comment]
Thanks for reporting. Please check this now. Has been fixed.
