### ISSUE TITLE
Letters still messed up

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#207]
Hi, Rayhan,

Thanks for the fix. But still in some parts (specifically in the blanks "Tags," "Remarks," and "Description,") Korean letters have been messed up. It appears like this: 
Tags (probably) 예배 (in Korean), media id 278814, appears as ì˜ˆë°°
Remarks (probably) 1판 14쇄 - 2009년 4월 25일 (in Korean), media id 278814, appears as 1íŒ� 14ì‡„ - 2009ë…„ 4ì›” 25ì�¼
Description appears as ë³¸ ë�„ì„œê´€ì�€ í…Œë„¤ì‹œì£¼ ë©¤í”¼ìŠ¤ì‹œ ì§€ì—­ì—� ìœ„ì¹˜í•œ ë³µë�œ êµ�íšŒ ë�„ì„œê´€ìœ¼ë¡œì„œ, ê¸°ë�…êµ� ì‹ ì•™ê³¼ ì—°ê´€ë�œ ì„œì �ë“¤ë¿�ë§Œ ì•„ë‹ˆë�¼ ë‹¤ì–‘í•œ ë¶„ì•¼ì�˜ í•œê¸€ ì„œì �ë“¤ê³¼ í•œêµ­ê³¼ ê´€ë ¨ë�œ ì„œì �ë“¤ì�„ ì†Œìž¥í•˜ê³  ìžˆìŠµë‹ˆë‹¤.

Blessings,

Yohan

![tags](https://cloud.githubusercontent.com/assets/12655219/11025374/e25a2652-865f-11e5-8053-e382a22fa2a2.png)

![remarks](https://cloud.githubusercontent.com/assets/12655219/11025380/ed961224-865f-11e5-9191-fd58ff2b8c5b.png)

![description](https://cloud.githubusercontent.com/assets/12655219/11025381/f4d39c32-865f-11e5-96ef-b71f96d1a5a4.png)

**Comment by rayhan** [comment]
There might be couple of instances where you have manually updated before my fix. Please let me know such specific instances.

**Comment by blessedbaptist** [comment]
All of them work properly now. Thanks for the work and the great library.
