### ISSUE TITLE
Export for Korean Letter

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#208]
Hi, rayhan

Thanks for great library.
Korean letter does not work for "Export Catalog Items" and "Export Members." All Korean letters appear as ?(question mark).

Blessings,

![reports](https://cloud.githubusercontent.com/assets/12655219/11027770/2c586656-867e-11e5-99b8-b37958886bee.png)

**Comment by rayhan** [comment]
Yes, I see, Microsoft Excel can't deal with utf-8 encoded character. Will find a solution.

**Comment by rayhan** [comment]
Hi, There are two suggestions here, can you please try then and see if they work. 

- https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0
- http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by blessedbaptist** [comment]
Thanks for the help.
To my library, this works:

1. Open CSV in Notepad
2. Save As -> select the right encoding
3. Open the new file
