### ISSUE TITLE
Letters still messed up

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#209]
Hi, Rayhan,

Thanks for the fix. But you fixed only media id 278814 and the blank "Description."

Still in all of the blanks "Tags" and "Remarks," Korean letters have been messed up. 
Tags: media ids: 242676, 242706, 242718, 243260, 243414, 243417, 243418, 243419, 243425, ... ... ...

**Comment by rayhan** [comment]
Ok, I will go through all of your tags and remarks.

**Comment by rayhan** [comment]
Updates:
- all the tags has been updated to korean letters
- all the remarks are ok and in korean letters already
- all the descriptions are ok and in korean letters already

Please confirm this.

**Comment by blessedbaptist** [comment]
Thanks for the work.
