### ISSUE TITLE
Assistant Librarian Role

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#210]
Hi, 

I mentioned this under the User Roles Unclear issue, but it is proving such a major issue for us that I thought I'd raise it separately. 

As well as Member and Staff, we really need an Assistant Librarian role (or perfumer permission setting) that allows users to check books in and out for other members.

Is this possible, please?

**Comment by rayhan** [comment]
Yes, we are going to have following roles:

Library Admin
- Access to all permissions 

Library Staff
- Access see many parts
- Mostly can view 
- Add catalog information. 
- No access to delete any information, 
- Limited ability to edit some catalog specific information.
- No access to users / permission settings
- Do check-ins and check-outs

Library Assistant [will be added shortly]
- Do only check-ins and check-outs related tasks
- Access to catalogs searching, view and booking information

Library Members:
- Access to OPAC
- For members / patrons / students - they can log into the library and access their booking and other information only.

**Comment by rayhan** [comment]
Added a role for Library Assistant with check-in and check-out permissions. Will test how it works in couple of days. Please let me know if you see any issues around this.

**Comment by shiv379** [comment]
Thanks it's looking good! I've added some issues in a new thread but this was just what we needed thanks!
