### ISSUE TITLE
Custom e-mails to overdue members

### ISSUE THREAD

**Issue by bmssinfo** [Librarika/Issues#211]
Hello,
I want to be able to send custom emails to members who has overdue items. This could be short term enhancement, but at least I want to be bale to see their emails on overdue list so I can export it to excel and make an email merge.

Thanks

![image 5](https://cloud.githubusercontent.com/assets/14931392/11121940/aeb4313e-8926-11e5-8f75-434336899ace.png)

**Comment by shiv379** [comment]
Maybe add Overdue Items as another report?

**Comment by bmssinfo** [comment]
That would be even better.

**Comment by rayhan** [comment]
You can access circulation emails from Reports -> Circulations -> Advance Reports.

**Comment by bmssinfo** [comment]
Thanks, I tried to export it to csv file, it doesn't reflect emails on csv.
