### ISSUE TITLE
recipt

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#212]
I was thinking of increasing the font and darkness of the text on the receipt and also help print via receipt printer or A5 sheet  whiteout the clarity being reduced  .

**Comment by rayhan** [comment]
Did you try printing on receipt printer? How does it look? Can you attach a picture here?

**Comment by SAIprasannaK** [comment]
I tried in a lazer printer using the size

**Comment by rayhan** [comment]
Color darkened.
