### ISSUE TITLE
Library Assistant Role

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#213]
Hi,

HUGE thanks for adding the Library Assistant role! I have some requests for changes which I hope all librarians will agree with:

Pages to remove access:
The Manage menu could be removed completely for Library Assistants...
-Manage > Website Integration
-Manage > Users
-Manage > Report a bug
-Catalog > Authors (Add/Edit - View is OK to access)
-Catalog >Publishers (Add/Edit - View is OK to access)

The Others menu can be removed completely for Library Assistants, as these are administration settings.

Also could these pages just not appear on the menus rather than appearing but redirecting to a failed access notice, please?

Thanks!

**Comment by rayhan** [comment]
Menu listings has been updated, now only show menus based on role.

**Comment by shiv379** [comment]
Thanks!
