### ISSUE TITLE
Re receipt printing error 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#215]
Hi sir the print is darker but i request you to please give a option to a select a paper size and then keep that as a standard for that library. Eg A6,A5 as when i print using the system dialogue or anything the due date and time gets cut .so if you give a option for paper size please make sure that the text fits the page.i also request you to please add the accession number below the ref number.Please take this in to consideration.

**Comment by SAIprasannaK** [comment]
![14475148368961184911806](https://cloud.githubusercontent.com/assets/15402765/11164304/55552a88-8b12-11e5-8b7b-2338a97eacd3.jpg)
PicA6

**Comment by rayhan** [comment]
Thanks you, your inputs was valuable. Added Accession number and the receipt page will now fit the paper size.
