### ISSUE TITLE
discussion board access,membership type,number of books

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#216]
please provide discussion board access to all library members.please allow the library to change the membership type and the number of books the member can borrow please make it so that we can add  more categories

**Comment by shiv379** [comment]
From our library point of view we wouldn't want all members to have access to the discussion board, only the staff as it is currently set. Maybe allow this option to be set in the library preferences so any implementation can choose what suits them? 

I'm assuming though that this would be at the very least restricted to members with logins?

**Comment by SAIprasannaK** [comment]
Yes it would be restricted to members with log in only
