### ISSUE TITLE
Return receipt,request receipt 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#217]
i request you to please create a return and a request receipt as it will be very use full.if possible please add a delivery option too as our library delivers books to the members homes

**Comment by rayhan** [comment]
How do you deliver to home? By post?

On Saturday, 14 November 2015, SAIprasannaK <notifications@github.com>
wrote:

> i request you to please create a return and a request receipt as it will
> be very use full.if possible please add a delivery option too as our
> library delivers books to the members homes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/217>.
>


-- 
Rayhan

**Comment by SAIprasannaK** [comment]
sir our staff deliver books .we get orders only at a range of 3 km

**Comment by SAIprasannaK** [comment]
As if we have a delivery receipt  it would be easy to know which book goes to whom sir.

**Comment by SAIprasannaK** [comment]
sir what happened to my request

**Comment by SAIprasannaK** [comment]
any updates or suggestions on it ?
