### ISSUE TITLE
sir whole name not appearing 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#218]
sir whole name of the library is not appearing only half   can we customize the receipt

**Comment by SAIprasannaK** [comment]
![14475250454551184911806](https://cloud.githubusercontent.com/assets/15402765/11165061/172f195e-8b2a-11e5-8cb6-2928683e9d18.jpg)

**Comment by rayhan** [comment]
The name on the header is the Organization Name that you can update from Manage -> Library -> Library Information -> Organization Info.

**Comment by SAIprasannaK** [comment]
Thank you sir what happened to my other request can they be fulfilled
