### ISSUE TITLE
Librarika smart add 

### ISSUE THREAD

**Issue by rve150** [Librarika/Issues#220]
Dear Librarika Support
  We are building a non-profit purpose online library database.
We were trying to add children comic books from Amar Chitra Katha.
See example:
http://www.amazon.in/Aruni-Uttanka-Amar-Chitra-Katha/dp/8184821271/ref=sr_1_1?s=books&ie=UTF8&qid=1447530198&sr=1-1&keywords=amar+chitra+katha+aruni+uttanka

We also converted the printed ISBN number to the ISBN13 format. However I get an error as seen in the screenshot below. We have a list of such books that needs to be entered into the online database hopefully with thumbnails of the front cover+ details.
Would request support on this.

Best Regards
R.Rao

![screenshot](https://cloud.githubusercontent.com/assets/13483094/11165508/cb7ae88e-8b11-11e5-9daa-fb114b780b45.PNG)

**Comment by SAIprasannaK** [comment]
Sir even i find the same problem Indian magazines cannot be added please link with amazon India

**Comment by rayhan** [comment]
Yes, support for Amazon India well be added.

**Comment by Martina-STBAPIA** [comment]
Hi Sir, can you please also link it with the Amazon Indonesia? thank you
