### ISSUE TITLE
Bulk upload seems to "forget" ISBN13

### ISSUE THREAD

**Issue by badhrij** [Librarika/Issues#222]
Hello When I do a bulk upload, it contains a few books with ISBN 10 and a few other books with ISBN13. All the books are uploaded. However, I find that, entry "ISBN13" is not retained for the books with a valid ISBN13 entry in CSV file. 
Here is the example. 
Title : "cold steel" forgot ISBN13, but title "inheritence of loss" retained isbn10

[to_be_uploaded_19Nov.xlsx](https://github.com/Librarika/Issues/files/38913/to_be_uploaded_19Nov.xlsx)

**Comment by rayhan** [comment]
Fixed. Thanks for reporting this critical bug.
