### ISSUE TITLE
Pictures of books not shown

### ISSUE THREAD

**Issue by badhrij** [Librarika/Issues#223]
Hello,
Earlier I noticed that when books are uploaded with ISBN/ISBN13, picture showed up against the Books.
But it doesn't happen anymore. Can you check if this is an issue? Or tell me how I can ensure that when I bulk upload books I can ensure that a picture shows up?

**Comment by rayhan** [comment]
I believe this issue is fixed already. Pictures only shows when our upstream has pictures, also you can save pictures for each item later. 

Thanks
