### ISSUE TITLE
Circulation is disabled for this title

### ISSUE THREAD

**Issue by nayaneye** [Librarika/Issues#229]
Why do i see following error while reserving the book... 

"Circulation is disabled for this title
![curculation_disabled](https://cloud.githubusercontent.com/assets/6984013/11417055/5ea01f32-9439-11e5-94d8-f908a7964708.png)
"

**Comment by dumpong** [comment]
Same issue here. Could someone help? I just created a library and inputted one book and tried to check it out (using a member account) and got the same screen. Any help is appreciated.

**Comment by dumpong** [comment]
Nevermind. I found the reason. Assuming the book is circulation-enabled, on your dashboard:

Manage -> Preferences -> Self Service - > Enable member checkouts. (it should be the first option). For me, it wasn't checked by default and we needed to check the box to start checking books out.

**Comment by nayaneye** [comment]
this is not helping us. :(

still looking for fix.

Thanks,
Nayan


---
http://nayaneye.co.in/
*-------------------------------------------------------------------------------------------------------*
Emails are being batched - if your message is urgent, please call
*-------------------------------------------------------------------------------------------------------*
<EOM>

**Comment by rayhan** [comment]
Hi, it should be fixed now.
