### ISSUE TITLE
Circulation is disabled for this title

### ISSUE THREAD

**Issue by mp4muk** [Librarika/Issues#230]
When I try to place a hold on a item, this message comes up for every item that I try. When I go to my administrator account, everything looks correct in the settings. How can I fix this?

![screenshot 2015-11-28 at 4 30 00 pm](https://cloud.githubusercontent.com/assets/16063313/11454338/aba9c854-95ed-11e5-9ac8-e24c624048da.png)

**Comment by dumpong** [comment]
Assuming the book is circulation-enabled, on your dashboard:

Manage -> Preferences -> Self Service - > Enable member checkouts. (it should be the first option). For me, it wasn't checked by default and we needed to check the box to start checking books out.

**Comment by rayhan** [comment]
Hope its fixed now.

**Comment by mp4muk** [comment]
Thank you for your help! This is a great library system!
