### ISSUE TITLE
Smart Add Error

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#234]
Hi, rayhan,

Thanks for great library.
Whenever I use "smart add," same error message appears. "Error in processing data, please try again."
Not always....

![screenshot 10](https://cloud.githubusercontent.com/assets/12655219/11494968/e4f6516e-97cc-11e5-8455-7847f0d1e935.png)

**Comment by rayhan** [comment]
It has been fixed already, and we tested couple of times. Please reopen if you still have issues. Thanks!
