### ISSUE TITLE
Members list - Searching by MemberNo

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#236]
Hi,

Searching the member list for MemberNo doesn't seem to work! I can search by name, but MemberNo doesn't seem to return any results.

https://XXX.librarika.com/members/index

Thanks!

**Comment by rayhan** [comment]
It works now.

**Comment by shiv379** [comment]
Just tried this and still doesn't seem to work :/

**Comment by rayhan** [comment]
Are you trying with non numeric member number?

**Comment by shiv379** [comment]
Yes that would be it, our member numbers are based on our local account logons
