### ISSUE TITLE
Booking Quota Override

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#237]
Hi,

It would be really useful if Librarians were given the option to override the booking quota during checkouts, could this option be added? 

Thanks!

**Comment by rayhan** [comment]
Yes, it can be per member basis.

**Comment by shiv379** [comment]
This would be really really helpful! Are there any timescales on this? This is particularly important so we can allow teachers to have a higher booking quota as they make take out up to 20 books at once for topic work! At the moment I have to just trust that they all come back!

**Comment by rayhan** [comment]
In members section, added an optional booking quota field for individual members. Can you please check this out and let me know if you find any big issue?

**Comment by shiv379** [comment]
Just had a look, doesn't seem to be saving changes to the quota setting when editing member

**Comment by rayhan** [comment]
My bad, there was delay in syncing database. Working now.

**Comment by shiv379** [comment]
Looks like it works great thanks! 

For a future development would it be possible to set the default by designation too? That would allow us to easily set all members of a particular type (e.g. Teachers within a school) without needing to set every account individually? 

Thanks so much for your awesome work on Librarika!

**Comment by rayhan** [comment]
That would require a lot of time, may be in the future.

**Comment by shiv379** [comment]
Thanks :)
