### ISSUE TITLE
bar code labels 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#242]
please provide bar code label feature

**Comment by shiv379** [comment]
What exactly are you looking for? I would suggest that barcode generation is actually quite complex and you would be better off obtaining separate   software for this task. In my library we use Barcode Studio by TEC-IT, and this does a fantastic job and can handle everything I've thrown at it. Working to add this feature to Librarika would probably distract the already very busy developers from working on actual library functionality ;-) 

Disclaimer: I'm not involved with the development or anything, just another user :-)

**Comment by rayhan** [comment]
We have added experimental barcode labeling feature accessible form Circulations menu. 👍

**Comment by SAIprasannaK** [comment]
Thanks
