### ISSUE TITLE
Logon expiration requested

### ISSUE THREAD

**Issue by ymgrigsb** [Librarika/Issues#246]
I have noticed that if I leave Librarika while logged on, when I come back (sometimes days later) I am still logged on.  We are planning to have a computer in our library for individuals to log in to their account for checking out/checking in books.  Is there any option or possible way that if there is inactivity for a certain amount of time, the user is automatically logged off to prevent someone else from using their account (like what the banks do to you if you are not actively clicking around on their site)?  
Maybe others may not like this, which is why I was thinking setup option (on or off).

Thank you so much for your support!
Yvonne

**Comment by shiv379** [comment]
This is a really good idea, I agree completely. Being able to set the timeout duration or disable this feature would be very useful too (maybe a paid option).
