### ISSUE TITLE
Faster quick returns

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#247]
Hiya,

For faster quick returns I was wondering if you could possibly remove the confirmation box "The item has been returned successfully." and instead have the text appear as in info-bar at the top of the circulations page with the accession number and book title? This will reduce the number of clicks required to return a list of books.

Even better, if after returning a book the return book dialog could automatically re-open allowing us to very quickly scan through a pile of return books! Is this possible, please? :)

Thank you!

**Comment by rayhan** [comment]
Done.

**Comment by shiv379** [comment]
Thanks :)
