### ISSUE TITLE
Multiple / Custom themes

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#248]
Hiya! 

Definitely a feature for paid users here and possibly quite an encouragement for the paid plans (at least for the custom option). It would be great to have multiple style themes to choose from, to allow each library to tailor the look to its own branding. Maybe even also have the option to choose the colours within the theme (so the theme sets the layout etc but then libraries can customise their colour scheme). 

It would be even better if there was a possibility to create our own themes by uploading a css file. 
Just an idea :-) 

Thank you for your awesome work!

**Comment by rayhan** [comment]
We already added some color schemes, will continue iterating this in the future.
