### ISSUE TITLE
Circulation problems

### ISSUE THREAD

**Issue by metusac** [Librarika/Issues#251]
I have set up two branches in my library. In Branch 1, "book A", for example, is allowed for circulation. In Branch 2, the same book (book A) is not allowed for circulation. However, when I try to circulate the item in branch 1, where it is allowed for circulation, it says that the book is not allowed for circulation, although I had checked the "allow circulation" button.
any ideas? thanks

**Comment by rayhan** [comment]
I believe this problem is resolved already. Please reopen if necessary.
