### ISSUE TITLE
Issue on book return date

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#252]
when returning a book even if its over due the book is returned on the original due that and not on the the date its checked in.
Eg XYZ book is borrowed on 21/11/15 and return date is 17/11/15 the member returns the book on 20/11/15.but it shows when check on the returned item section as the item was checked on 17/11/15.
Please check this
thank you

**Comment by rayhan** [comment]
We store return information in a separate field. The return information is added to the report now.

**Comment by SAIprasannaK** [comment]
sir no change sir still the same problem appears sir the original due date
is still the date

On Sun, Dec 27, 2015 at 11:24 PM, Md. Rayhan Chowdhury <
notifications@github.com> wrote:

> We store return information in a separate field. The return information is
> added to the report now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/252#issuecomment-167430946>.
>



-- 









k.sai prasanna
