### ISSUE TITLE
Trouble importing items via .csv file

### ISSUE THREAD

**Issue by Gatewaycollege** [Librarika/Issues#256]
Hello Support team!

I was very pleased when I found out about this system and how user friendly it is.  However, since we signed up we keep having issues. Firstly, we were unable to log in even after numerous of attempts of password changes that Librarika suggested. I have managed to fix that and it is working fine now. Secondly, we are unable to import our library into the system. I have made a Google Spreadsheet document as suggested and downloaded it as CSV. First issue I came across is that it has troubles accepting Central European accents and thus exchanges some letters (such as š č ť ž ý á í ľ etc.) for symbols  and thus makes the title of the book unreadable. Is there anyway to go around this issue? 
Second issue related with it is that when I attempt to upload it to Librarika it goes through and asks me to review the data but shows me blank page to review (please see attached screenshot). 
Is there anyway we can fix this?

Thank you!

![librarika review data](https://cloud.githubusercontent.com/assets/16609795/12198409/e919e1d2-b60f-11e5-8837-b032cdfc7677.jpg)

**Comment by rayhan** [comment]
We have already solved this issue over the emails, so closing it now.
