### ISSUE TITLE
Self check out 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#257]
Sir in our library we want to implement a self checkout system I.E having members be able to scan their card and the books on a pc without being able to view the circulation list or any other as a separate feature .the current feature allows members to checkout a book from their account and only by searching the title.what i would like is a type that library staff use to checkout books.

**Comment by rayhan** [comment]
We believe, the staff checkout is a quick service, a library member usually need couple of books a day, not 100s of books. So though it is great idea, but is not possible considering other pending features.

Thanks for your suggestions.
