### ISSUE TITLE
Please add the swedish national database (LIBRIS)

### ISSUE THREAD

**Issue by Naesstrom** [Librarika/Issues#259]
It would be really really great if you could add the Swedish national database as one of the sources for importing books.
They have a open API http://librishelp.libris.kb.se/help/xsearch_eng.jsp that you can use to fetch the information needed.

Best Regards
Erik

**Comment by rayhan** [comment]
Thank you very much. If you know any other resource like this, please share with us.

**Comment by rayhan** [comment]
We added Swedish national catalog search on experimental basis. It would be great if you can give some inputs on how its functioning.

Regards,
Rayhan

**Comment by Naesstrom** [comment]
Oh great, will try it out tomorrow and get back to you!

**Comment by Naesstrom** [comment]
Just tried it by searching for the book with ISBN:9789173515184 and librarika says **Unable to find book information online, please try adding manually.**
Searching for it manually gives me the correct book (http://libris.kb.se/bib/11433810)

I also tried the xsearch query http://libris.kb.se/xsearch?query=isbn:9789173515184&format=dc and that seems to be working to, the dc format can be replaced with any of the following:
marcxml | mods | json | ris | dc | rdfdc | bibtex | refworks | harvard | oxford

**Comment by rayhan** [comment]
We are processing http://api.libris.kb.se/sru/libris. Are they not the same?

**Comment by Naesstrom** [comment]
Feels like it should be, but I'm not that good at API's so I just used the information they had at http://librishelp.libris.kb.se/help/tech_eng.jsp?redirected=true&language=en

Could you use the Z39.50 interface, looks like it should be standard for library applications? https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=sv&ie=UTF-8&u=http%3A%2F%2Fwww.kb.se%2Flibris%2Fteknisk-information%2Flibris-via-Z3950%2F&edit-text=

**Comment by Naesstrom** [comment]
Just tried this again and it seems that you got it working! All the information is added and the only thing missing is the cover photo. :+1: 

Do you think that will be imported to or should we start adding all our books now?

**Comment by rayhan** [comment]
Z39.50 is what we are using. Unfortunately that interface doesn't provide any cover photos.
