### ISSUE TITLE
User photo form: doesn't remember the chosen image

### ISSUE THREAD

**Issue by angelitoes** [Librarika/Issues#26]
Select a file, submit correctly.
When you edit again this user the form doesn't have the image previously selected.

**Comment by shaanisabio** [comment]
Hi! I've been experiencing this just today. I've uploaded 300+ titles and tried to generate the list of items without photo. I uploaded the photos manually but when I checked the opac, the images didn't appear. 

Thank you! :)

**Comment by rayhan** [comment]
Are you saying about book picture or you are saying about user's picture. I
see that user's picture appear properly when I go to settings page.

On Wed, Oct 21, 2015 at 8:31 AM, shaanisabio <notifications@github.com>
wrote:

> Hi! I've been experiencing this just today. I've uploaded 300+ titles and
> tried to generate the list of items without photo. I uploaded the photos
> manually but when I checked the opac, the images didn't appear.
>
> Thank you! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/26#issuecomment-149763464>.
>



-- 
Rayhan

**Comment by shaanisabio** [comment]
It's okay now. It's the book picture. I think I just missed out the first zero digits of some ISBN numbers that's why the book images won't show up. Sorry and thanks! :)
