### ISSUE TITLE
Build Catalog Issue

### ISSUE THREAD

**Issue by homeschoolersofbealeton** [Librarika/Issues#261]
Never had issues before.  Now every time I try to click Smart Add it instantly shows "Network Error!  Please try again."  Connection is good....network is working...site is not.

So I try to manual add instead and only get a blank page.

**Comment by rayhan** [comment]
That means the site was not accessible from your computer. Can you please try again and confirm us with a screenshot of your entire scree along with the website address path.

**Comment by rayhan** [comment]
Any update?
