### ISSUE TITLE
ISSN - problem with adding multiple issues of a journal

### ISSUE THREAD

**Issue by VaultAusir** [Librarika/Issues#262]
Currently, ISSN is treated exactly like ISBN, which means that every item has to have a unique number, and duplicate ISSN numbers are not allowed. ISSN is for serial publications, e.g. magazines, so because of this I cannot add multiple issues of a given magazine with their proper ISSN, since they all have the same ISSN, and that is treated as an error, as every item is required to have a unique number.

**Comment by rayhan** [comment]
Thanks for reporting, we will investigate and solve this.

**Comment by rayhan** [comment]
Fixed.
