### ISSUE TITLE
No recognition for Korean letters for search

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#263]
Hi, rayhan.

Thanks for great library.
We could not search with Korean letters. That means we could not search any Korean books.
Blessings, on the first day of lunar calendar.

![777](https://cloud.githubusercontent.com/assets/12655219/12880269/72fa455c-ce04-11e5-9eef-28683e718711.png)

**Comment by rayhan** [comment]
Support for korean searching in default mode has been added.

**Comment by blessedbaptist** [comment]
Thanks, now there is recognition of Korean letters, so I can search Korean books.
A few minutes ago, I put some books on the library. 
But, I could not search the books. I think the search is invalid for new added books.
Would you check?
Thanks again.

**Comment by rayhan** [comment]
Hi,

Actually the default search index doesn't update instantly, it updates in
every 10-15 minutes intervals. So, newly added books are not instantly
found in search results only after 10-15 minutes.

Regards,
Rayhan

On Mon, Feb 8, 2016 at 5:43 PM, blessedbaptist <notifications@github.com>
wrote:

> Thanks, now there is recognition of Korean letters, so I can search Korean
> books.
> A few minutes ago, I put some books on the library.
> But, I could not search the books. I think the search is invalid for new
> added books.
> Would you check?
> Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/263#issuecomment-181330301>.
>



-- 
Rayhan

**Comment by blessedbaptist** [comment]
Thank you, Rayhan.
