### ISSUE TITLE
Help! Can't view book images / "new arrivals" 

### ISSUE THREAD

**Issue by ayandashutterbug** [Librarika/Issues#265]
Hello Support Team!

Just few weeks ago, Sophos was installed here in my workplace. Amazon and certain websites were blocked. Their reason was that Amazon is being categorized as "online shopping". Anyway, I just noticed that I can't view a large number of book images as well as the new arrivals section. I love this feature so much, it makes me sad that I will not be able to utilize it.  Please help me :) 

Thank you!

**Comment by rayhan** [comment]
Hi, 

Since amazon is blocked at your workplace, pictures can't be loaded from amazon. You may try manually uploading pictures for New Arrival Items, it that case pictures will be show from Librarika server and there will be no problem.

Regards,
Rayhan
