### ISSUE TITLE
Member access problem 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#267]
One of our members of our library  reported that their view of the OPAC  was different when we asked them to open their account we saw that they had access to all the tabs from circulation to report they had access. when we checked for permissions they were not in the list. I would like to know what to do.We have tried deleting the member and adding him again but the same problem persists.

**Comment by rayhan** [comment]
Can you please email me the username, email and MemberID of that member in info@librarika.com account?

Does all the member has same menue?

Regards
Rayhan

**Comment by SAIprasannaK** [comment]
Sir I have sent the mail with all the particulars.
Only this member faces this problem.

**Comment by rayhan** [comment]
Hi,

This user account has been completely disconnected from your library
however he can join with his same username and password. You can now
re-send member invitation to him. Thanks for reporting.

Regards,
Rayhan

On Sun, Feb 14, 2016 at 4:05 PM, SAIprasannaK <notifications@github.com>
wrote:

> Sir I have sent the mail with all the particulars.
> Only this member faces this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/267#issuecomment-183864903>.
>



-- 
Rayhan
