### ISSUE TITLE
Smart Add Error

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#270]
Hi, rayhan,

Thanks for great library.
When I still use "smart add," same error message appears  "Error in processing data, please try again."

![screenshot 30](https://cloud.githubusercontent.com/assets/12655219/13072456/0ed22214-d45f-11e5-8cb3-f6ead5841ea5.png)

**Comment by rayhan** [comment]
Is it happening again? I tried couple of times to reproduce, but no luck.

**Comment by rayhan** [comment]
Closing if not happen again. Any update on this?
