### ISSUE TITLE
Scanner and check out question

### ISSUE THREAD

**Issue by B00447143** [Librarika/Issues#274]
Is there any way that after i scan a member number that it would automatically go to the Accession No field ?
Also is there any way to check in multiple items in one click, just like in check out where after you check out one item with its  accession number and hit enter a new blank accession number field pops up to check out another item?

**Comment by shiv379** [comment]
I second these suggestions!

**Comment by rayhan** [comment]
Now quick check-in will allow you to check-in multiple items repeatedly. 

Cheers
