### ISSUE TITLE
Paid Feature: Custom Domain / Subdoman

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#275]
Hiya,

A really handy (paid) feature would be the ability to use a custom domain or subdoman. For example http://library.MYOTHERDOMAIN.com or maybe http://www.MYOTHERDOMAN.com/library.

Thanks!

**Comment by rayhan** [comment]
Yes, I have a plan for this already, this is going to be a bit tricky.

**Comment by rfonseca** [comment]
Any possibility of revisiting this?
