### ISSUE TITLE
Return date

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#276]
sir i had previously mentioned about this issue.The problem we face is that we have fine for over due but when we check in books even after a month passed  the due date ,both in circulation record and in the circulation page is shows as though if it has been checked on the due date.I.E a book is due  on the 25 of January and is returned on the 25 of February but the system show's as though it has been returned on the 25 January itself. I would also like to suggest adding a pop up screen when checking over due items. 
Thank you

**Comment by rayhan** [comment]
In the circulations page, do you see a column named **Received At**? It is supposed to be the date you receive item after due date. Can you confirm me this?

**Comment by SAIprasannaK** [comment]
yes sir thank you very much
