### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by porfiriobgc** [Librarika/Issues#277]
The author/editor and publisher name link on the table or on the description of a book doesn't make a search by that name. It returns no results... I think it should return all the books under that author's or publisher's name. If we make a search and then open the reference, the category link on that reference returns only the results on that category that fit the previous search term. It should list all the books in that category, I think. 

By the way, Great Work with the plataform. It's really nice and helpful.

**Comment by rayhan** [comment]
Updated.
