### ISSUE TITLE
Very slow Add Author popup - blocking other page loads

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#279]
Hi,

The Add Author popup is really slow to load, over the past few days it's taken a few minutes to appear and while I am waiting for it to appear any Librarika sessions I have open in other tabs will not load either!

**Comment by rayhan** [comment]
Ok, may be you have many authors in your library. Will optimize this in a week.

**Comment by rayhan** [comment]
Hopefully fixed.

**Comment by shiv379** [comment]
Thanks, I'll have a play with it over the next few days and let you know how it goes :-)
