### ISSUE TITLE
Goodreads Bulk upload

### ISSUE THREAD

**Issue by Don-Glass** [Librarika/Issues#281]
I exported a 119 book catalogue from Goodreads and attempted to BULK UPLOAD into Librarika.
I checked the content and marked the data and then clicked "SUBMIT".
I green-highlited message indicated import successful.
36 hours later, there was no change in my Librarika catalogue or the Dashboard.

I repeated the IMPORT process (using the same Goodreads CSV file) this morning and was again met with a "success" message.

**# Any idea where the imported catalogue data has gone???**

**Comment by rayhan** [comment]
It should load instantly, however we need to improvise this process to make it more transparent. Can you please send us the data in CSV format to info@librarika.com, we will then be able to investigate the issue further. Please name your library and login ID on that email.

--- 
Rayhan

**Comment by Don-Glass** [comment]
Hi Rayhan,

Attached is the CSV file I used (from Goodreads)

The Library is Glasshouse Library
I login as:  don.sjs@gmail.com

*Sincere regards,*

*Don Glass*
*telco@telkomsa.net <telco@telkomsa.net>*
021 782 5726  Phone
083 700 8012  Veggie
086 516 0075  Fax

**Comment by rayhan** [comment]
Hi,

Didn't receive the attachment, please attach it in a direct email, not to
this thread email.

Regards

On Monday, 7 March 2016, Don-Glass <notifications@github.com> wrote:

> Hi Rayhan,
>
> Attached is the CSV file I used (from Goodreads)
>
> The Library is Glasshouse Library
> I login as: don.sjs@gmail.com
> <javascript:_e(%7B%7D,'cvml','don.sjs@gmail.com');>
>
> *Sincere regards,*
>
> *Don Glass*
> *telco@telkomsa.net <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');> <
> telco@telkomsa.net <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');>>*
> 021 782 5726 Phone
> 083 700 8012 Veggie
> 086 516 0075 Fax
>
> On 7 March 2016 at 13:18, Md. Rayhan Chowdhury <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > It should load instantly, however we need to improvise this process to
> > make it more transparent. Can you please send us the data in CSV format
> to
> > info@librarika.com <javascript:_e(%7B%7D,'cvml','info@librarika.com');>,
> we will then be able to investigate the issue
> > further. Please name your library and login ID on that email.
> > ------------------------------
> >
> > Rayhan
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Librarika/Issues/issues/281#issuecomment-193209745>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/281#issuecomment-193232164>.
>


-- 
Rayhan

**Comment by Don-Glass** [comment]
Dear "Notifications" aka Rayhan!

I hope the attachment is still attached on arrival this time!!!

Please let me know!

Regards,
Don

**Comment by rayhan** [comment]
Dear Don,

This GitHub thread doesn't support attachment, that is why it will not
being forwarded. I know you attached the file but I will not receive it.

Would you please create a new email message with attachment and send it to
info@librarika.com.

:)

Regards,
Rayhan

On Monday, 7 March 2016, Don-Glass <notifications@github.com> wrote:

> Dear "Notifications" aka Rayhan!
>
> I hope the attachment is still attached on arrival this time!!!
>
> Please let me know!
>
> Regards,
> Don
>
> On 7 March 2016 at 15:55, Md. Rayhan Chowdhury <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Hi,
> >
> > Didn't receive the attachment, please attach it in a direct email, not to
> > this thread email.
> >
> > Regards
> >
> > On Monday, 7 March 2016, Don-Glass <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Hi Rayhan,
> > >
> > > Attached is the CSV file I used (from Goodreads)
> > >
> > > The Library is Glasshouse Library
> > > I login as: don.sjs@gmail.com
> <javascript:_e(%7B%7D,'cvml','don.sjs@gmail.com');>
> > > <javascript:_e(%7B%7D,'cvml','don.sjs@gmail.com
> <javascript:_e(%7B%7D,'cvml','don.sjs@gmail.com');>');>
> > >
> > > *Sincere regards,*
> > >
> > > *Don Glass*
> > > *telco@telkomsa.net
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');>
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');>');>
> > <
> > > telco@telkomsa.net
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');>
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net
> <javascript:_e(%7B%7D,'cvml','telco@telkomsa.net');>
> > ');>>*
> > > 021 782 5726 Phone
> > > 083 700 8012 Veggie
> > > 086 516 0075 Fax
> > >
> > > On 7 March 2016 at 13:18, Md. Rayhan Chowdhury <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > It should load instantly, however we need to improvise this process
> to
> > > > make it more transparent. Can you please send us the data in CSV
> format
> > > to
> > > > info@librarika.com
> <javascript:_e(%7B%7D,'cvml','info@librarika.com');>
> <javascript:_e(%7B%7D,'cvml','info@librarika.com
> <javascript:_e(%7B%7D,'cvml','info@librarika.com');>
> > ');>,
> > > we will then be able to investigate the issue
> > > > further. Please name your library and login ID on that email.
> > > > ------------------------------
> > > >
> > > > Rayhan
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/Librarika/Issues/issues/281#issuecomment-193209745
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Librarika/Issues/issues/281#issuecomment-193232164
> >.
> > >
> >
> >
> > --
> > Rayhan
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Librarika/Issues/issues/281#issuecomment-193256277>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/281#issuecomment-193257523>.
>


-- 
Rayhan

**Comment by Don-Glass** [comment]
Dear Rayhan,
I've just noticed that the AUTHORS and the PUBLISHERS of all the books uploaded via the Goodreads CSV file import have been added to my Glasshouse Library, but NONE of the Book Titles.
This is (possibly?) because the ISDN and ISDN13 numbers do not seems to have been recognized??

Regards,
Don

**Comment by rayhan** [comment]
Yes exactly, the ISBN and ISBN13 fields contain invalid characters, They
all should be numeric. I will cleanup your entire catalog and then do a
fresh import.

Regards,
Rayhan

On Mon, Mar 7, 2016 at 9:02 PM, Don-Glass <notifications@github.com> wrote:

> Dear Rayhan,
> I've just noticed that the AUTHORS and the PUBLISHERS of all the books
> uploaded via the Goodreads CSV file import have been added to my Glasshouse
> Library, but NONE of the Book Titles.
> This is (possibly?) because the ISDN and ISDN13 numbers do not seems to
> have been recognized??
>
> Regards,
> Don
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/281#issuecomment-193286427>.
>



-- 
Rayhan

**Comment by Don-Glass** [comment]
Thank you very much!
Is this a "problem" at the Goodreads EXPORT side...or is this something
that Librarika can devise a workaround for future??

(The reason why I ask, is that I can SCAN books from my physical library
very easily & quickly using the Goodread App on my smartphone)
I have a few hundred more books still to capture...hopefuly via SCANNING!!

WHEN will Librarika have a Scanning app using tablet or smartphone camera?

**Comment by rayhan** [comment]
Hi,

I believe the problem is with the good reads.

However, you keep scanning with goodreads, when done send me the CSV, I
will do clean import with new data.

We can't afford an iPhone app development at this moment, may be in the
near future we can.

Regards,
Rayhan

On Monday, 7 March 2016, Don-Glass <notifications@github.com> wrote:

> Thank you very much!
> Is this a "problem" at the Goodreads EXPORT side...or is this something
> that Librarika can devise a workaround for future??
>
> (The reason why I ask, is that I can SCAN books from my physical library
> very easily & quickly using the Goodread App on my smartphone)
> I have a few hundred more books still to capture...hopefuly via SCANNING!!
>
> WHEN will Librarika have a Scanning app using tablet or smartphone camera?
>
> On 7 March 2016 at 17:05, Md. Rayhan Chowdhury <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Yes exactly, the ISBN and ISBN13 fields contain invalid characters, They
> > all should be numeric. I will cleanup your entire catalog and then do a
> > fresh import.
> >
> > Regards,
> > Rayhan
> >
> > On Mon, Mar 7, 2016 at 9:02 PM, Don-Glass <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Dear Rayhan,
> > > I've just noticed that the AUTHORS and the PUBLISHERS of all the books
> > > uploaded via the Goodreads CSV file import have been added to my
> > Glasshouse
> > > Library, but NONE of the Book Titles.
> > > This is (possibly?) because the ISDN and ISDN13 numbers do not seems to
> > > have been recognized??
> > >
> > > Regards,
> > > Don
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Librarika/Issues/issues/281#issuecomment-193286427
> >.
> >
> > >
> >
> >
> >
> > --
> > Rayhan
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Librarika/Issues/issues/281#issuecomment-193287731>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/281#issuecomment-193294473>.
>


-- 
Rayhan

**Comment by Don-Glass** [comment]
Thanks very much Rayhan.

Could you obtain an ESTIMATE of an Android or iPhone app development cost?
I'd be prepared to start a process to help raise funds to assist in getting it started!!
I see it as a valuable extension to a really worthwhile SaaS offering!

Thanks for all YOUR assistance to me.

Much appreciated.

Don Glass
Mobile device
