### ISSUE TITLE
Error Processing Request

### ISSUE THREAD

**Issue by LifeTransitions** [Librarika/Issues#282]
Just started on Librarika this afternoon building a catalog for a small college annex library. Was 7 entries in utilizing smart-add when the system just stopped accepting ISBN 10s and ISBN 13s - every time, I got the same non-specific message: "error processing request, please try again." I've been trying again, utilizing about 15 different books at this point, and all of them have resulted in this same error. Is there some kind of a database hangup on Librarika's end?

**Comment by rayhan** [comment]
No database hangup as I am aware of, can you please try again, couple of times, I need to investigate this a bit more.

Regards,
Rayhan

**Comment by rayhan** [comment]
Hope this is already fixed.
