### ISSUE TITLE
SmartAdd with ASIN Tries to Add Copy to Existing Book in Librarika Catalog

### ISSUE THREAD

**Issue by DanKLib** [Librarika/Issues#283]
Starting today, I began noticing an issue where the SmartAdd function of Librarika detects an ASIN for a new catalog item as a different, already existing catalog item. Accordingly, instead of adding a new listing for the book, it attempts to add an additional copy to the incorrect, preexisting listing. This does not happen every time as ASIN is used with SmartAdd, but every time that it does happen, it detects the ASIN as the same preexisting book. I tried removing the book it was detecting, but it just started detecting another book. Again, every time this was an issue, it detected the same book (even after removing the first book that was being detected incorrectly). Please advise.

**Comment by rayhan** [comment]
Hope this is already fixed.
