### ISSUE TITLE
Disable "Review Item" emails

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#287]
Hi,

Is there any way to disable to "review item" email when a user checks a book in? We are looking at enabling overdue reminders for our users (Primary school) however the review item emails could be overwhelming for our pupils!

On a side note is it possible to change the text on the emails? "Cheers" is not an appropriate sign of for us to use with our pupils!

Thanks!

**Comment by rayhan** [comment]
Added a control at Manage -> Preferences section to disable the review reminder. This control is still experimental, but should work.

**Comment by shiv379** [comment]
Thank you! I'll give it a go :)
