### ISSUE TITLE
Search by Call No

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#291]
Could Call No please be added to the search options on the OPAC page? This would allow users to see all books the library has for a particular topic (as defined by the Dewey Decimal number, assuming the library is using the Call No in that way).

Thanks!

**Comment by rayhan** [comment]
I have a question: do you use iPhone? We are building a cataloging app to scan item from Barcode using iPhone. I think you might be in our early access list.

**Comment by shiv379** [comment]
I'm Android I'm afraid, but if you do an android app I'm happy to help!

**Comment by rayhan** [comment]
Ok, on android then :)

**Comment by shiv379** [comment]
You have my email address yeah? Just drop me an email with details anytime :)

**Comment by rayhan** [comment]
The option has been added. 👍
