### ISSUE TITLE
Error of pop-up system for Existing Author

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#293]
Hi, rayhan,

Thanks for this amazing library.

Pop-up system for Existing Author does not work correctly. Would you please check it? Thanks a lots.

Attached is a screen shot in which a weird pop up window of Existing Author appeared when I typed "y"

![screenshot 32](https://cloud.githubusercontent.com/assets/12655219/13968308/11c33074-f04a-11e5-9f7b-da8793c580b7.png)

**Comment by rayhan** [comment]
Please enter at least 2 characters, do you see more accurate authors now?

Regards,
Rayhan

On Wed, Mar 23, 2016 at 3:22 AM, blessedbaptist <notifications@github.com>
wrote:

> Hi, rayhan,
>
> Thanks for this amazing library.
>
> Pop-up system for Exist Author does not work correctly. Would you please
> check it? Thanks a lots.
>
> Attached is a screen shot that appeared when I type "y"
>
> [image: screenshot 32]
> <https://cloud.githubusercontent.com/assets/12655219/13968308/11c33074-f04a-11e5-9f7b-da8793c580b7.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/293>
>



-- 
Rayhan

**Comment by blessedbaptist** [comment]
Hi, Rayhan,
Thank you very much.

Blessings,
Yohan
