### ISSUE TITLE
Please correct grammar in the following places...I am a SCHOOL librarian!

### ISSUE THREAD

**Issue by njjames09** [Librarika/Issues#295]
Hello,
I noticed that when users are prompted to create an account, the site states they can sign up for as many "library" as they like. That should be "libraries" in the plural form. 

Also, where users are prompted to leave a review, it says "Share your detail experience..."  It should be changed to "Share your detailed experience..."   In that same box "unlikes" should be "dislikes."  

I MUST note this, because I am an English teacher (as well as the school librarian).

I am preparing to sign up HUNDREDS of students, faculty, and administration. Therefore, I cannot have a site with these grammatical errors.

Thank you.

**Comment by rayhan** [comment]
Thank you very much for your suggestions, we appreciate all grammatical suggestions.
