### ISSUE TITLE
Grammar errors when requesting a book.

### ISSUE THREAD

**Issue by njjames09** [Librarika/Issues#296]
Doing a bit of testing here...

From the patron perspective, when requesting a book, the box says "Leave message for librarian."  It should say "Leave a message for the librarian."

Also, when a request is accepted, the email message tells the patron to pick the book up "during the office hour." It should say "during office hours."

Thank you very much!

**Comment by rayhan** [comment]
I believe I have corrected the right pages. For you information, would you please mention URL along with your suggestions in the future. Thanks again for your valuable inputs.
