### ISSUE TITLE
Loan Receipt - Grammar

### ISSUE THREAD

**Issue by njjames09** [Librarika/Issues#298]
Hi,
On the loan receipt template, there is very poor grammar used.  It says:
"To check your loan status or to renew your library items or for other queries, please email us at njames@iltexas.org or contact us at https://iltghslib.librarika.com/libraries/contact"

It should say: "To check your loan status, renew your account, or for other inquiries, please email us at: njames@iltexas.org.  You may also contact us via: https://iltghslib.librarika.com/libraries/contact."

Thanks!

**Comment by rayhan** [comment]
Thank you very much, it has been updated.
