### ISSUE TITLE
DUE Date 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#300]
sir 
it it possible to set a time period for each book,If so please guide me.

**Comment by shiv379** [comment]
Does this mean setting the default return period to allow for different sets of books who are only allowed out for certain lengths (i.e. 3 day loan, 2 week, 1 month)? As opposed to setting it individually when you check out a book?

**Comment by SAIprasannaK** [comment]
Yes

K Sai Prasanna

**Comment by rayhan** [comment]
This is indeed a nice idea, but can't possible at this moment. Have put it on long future list.
