### ISSUE TITLE
Difficult to identify authors

### ISSUE THREAD

**Issue by blessedbaptist** [Librarika/Issues#301]
Hi, Rayhan

Thanks for this great library.
It is difficult to identify same-named authors on pop-up screen of "Add Author." Would you make appearance of their birth year?

Thanks again!!!
![screenshot 33](https://cloud.githubusercontent.com/assets/12655219/14271762/f5c359c6-fac1-11e5-92bf-2837641a133e.png)

**Comment by rayhan** [comment]
Hopefully solved.
