### ISSUE TITLE
I have deleted two books, yet they still appear as overdue / circulation

### ISSUE THREAD

**Issue by gclz** [Librarika/Issues#304]
I have been testing librarika and for that, I added dummy books that I used for experimenting.

After I was done with that, I deleted them, but now they still appear on my dashboard as Overdue / Circulated. What happened was, I checked them out but didn't checked in. I deleted them, and now the system probably is still waiting for me to check them in while they dont exist anymore.

**Comment by rayhan** [comment]
Can you please send library information over the email, I will look into this and add a fix.

**Comment by rayhan** [comment]
Fixed.
