### ISSUE TITLE
Search Issue "Default"

### ISSUE THREAD

**Issue by det-tommy** [Librarika/Issues#307]
I read (https://librarika.com/kb/new-improved-search-system-in-default-mode) that Librarika implement new improved system in default mode, but I wonder why I still can't search anything under default mode?

Example:
When I searched using author category and fill the author's name, I can find the books.
When I searched using default category and fill the author's name, I can find any books.

When I searched using tags category and fill the tags, I can find the books.
When I searched using default category and fill the tags, I can't find any books.

In fact, I haven't been able to do any successful search with default category. I wonder what's wrong?

EDIT: after trying it a few times, it seems that the books that I imported with CSV files today can't be searched in default category while the book that I inputted manually yesterday can be searched. I wonder where's the difference?

EDIT2. nevermind. It seems like there's a delay in the server or something like that. I logged in today and everything is working as intended

**Comment by rayhan** [comment]
Yes, search indexing in default mode has a delay. Thanks.
