### ISSUE TITLE
Barcode Labels Suggestion

### ISSUE THREAD

**Issue by mp4muk** [Librarika/Issues#310]
I wish for the barcode labels, you didn't have to type in **every** book number for a barcode, I wish that there was just a easy print button. This makes it very hard to use.

**Comment by rayhan** [comment]
Yes, we will add buttons on book and member page. Thanks.

On Sun, May 29, 2016 at 8:44 PM, mp4muk <notifications@github.com> wrote:

> I wish for the barcode labels, you didn't have to type in *every* book
> number for a barcode, I wish that there was just a easy print button. This
> makes it very hard to use.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Librarika/Issues/issues/310>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAEdRcwyhbUJhPZSqeG4P1Z9doC5fLqpks5qGaZLgaJpZM4IpTe3>
> .
>



-- 
Rayhan
