### ISSUE TITLE
Barcode

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#311]
I would like to point out that when the bar code size is increased the header and the number at the bottom does no  increase. it would be better if it would.

**Comment by rayhan** [comment]
If you increase barcode size, it will be more clear when you print on a
bigger label. By default size get scaled by label size. Yea, font size
should be increased on bigger label.

On Sun, May 29, 2016 at 9:11 PM, SAIprasannaK <notifications@github.com>
wrote:

> I would like to point out that when the bar code size is increased the
> header and the number at the bottom does no increase. it would be better if
> it would.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Librarika/Issues/issues/311>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAEdRQgIFkbYxId0plJ_GH24-BG4GP9Aks5qGayEgaJpZM4IpTzE>
> .
>



-- 
Rayhan
