### ISSUE TITLE
Unable to add copy

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#312]
Hi,

I'm having a problem with Librarika this morning; whenever I click on Add a Copy I get a network error message. However I am having no problems accessing any other part of Librarika or any other website.

**Comment by rayhan** [comment]
Which book did you try to add copy of?

**Comment by rayhan** [comment]
Its solved. Please try now.

**Comment by shiv379** [comment]
Thanks, I tried with a different book this evening and it seemed to work fine :-) I can't remember which book it was this morning offhand, do you still need to know?

**Comment by rayhan** [comment]
No need, I found the issue. We were updating some forms for internationalization, that caused this bug.

**Comment by shiv379** [comment]
Thanks :-)
