### ISSUE TITLE
Login page: user logo

### ISSUE THREAD

**Issue by angelitoes** [Librarika/Issues#32]
1. This could be a good place to use the user picture.
2. I think I'm confused about the use of User and Member. Shouldn't here it say User Area instead of Member Area. There is no Administrator member.

![captu5552ra](https://f.cloud.github.com/assets/6534638/2238096/874a0a1c-9bdc-11e3-954a-244fab2e661b.PNG)

**Comment by rayhan** [comment]
Now we have members, and member area.
