### ISSUE TITLE
Member Number

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#320]
I would Like to know what is up with the automatic library member number?

**Comment by shiv379** [comment]
What is the problem exactly?

**Comment by rayhan** [comment]
Some librarians find it very difficult to assign a member ID, so we added an auto increment counter for next member ID. You can easily change the value during submission, its just like a suggestion.

**Comment by SAIprasannaK** [comment]
OK thanks I just wanted to know if it was a new feature
K Sai Prasanna
