### ISSUE TITLE
Dashboard Stats don't match circulations report

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#322]
Hi,

Our dashboard shows 393 overdue items, however our circulations report only returns 112 overdue items. Is this a bug?

**Comment by rayhan** [comment]
Are you sure? When I go to Overdue tabs, I still see 393 records.

https://xxx.librarika.com/media_bookings/index/Overdue

**Comment by shiv379** [comment]
I'll check when I'm back on computer. I was looking at the circulations report on the Reports page.

**Comment by shiv379** [comment]
Ignore me! I missed the Created Date. Apologies!
