### ISSUE TITLE
Delete Library Catalog

### ISSUE THREAD

**Issue by davidhaines** [Librarika/Issues#324]
Good afternoon

Is it possible to delete all of the books that are currently listed in the catalog without having to do it one by one?

Thanks

**Comment by rayhan** [comment]
Hi,

Yea, it's possible from our end. Please email your library information when
you need the cleanup.

Regards,
Rayhan

On Tuesday, 14 June 2016, davidhaines <notifications@github.com> wrote:

> Good afternoon
>
> Is it possible to delete all of the books that are currently listed in the
> catalog without having to do it one by one?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Librarika/Issues/issues/324>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAEdRVx8AS0jOk5n2jRJ_RwsQOLESt8Gks5qLqj-gaJpZM4I1TnP>
> .
>


-- 
Rayhan

**Comment by davidhaines** [comment]
Thanks Rayhan for the prompt reply.

I will contact you again in a few weeks when I would like all of the
Catalog Items removed.

Regards

David Haines
Exams Officer/Librarian

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

Newbury Hall School is committed to safeguarding and promoting the welfare
of children and young people and expects all staff and volunteers to share
this commitment.

**Comment by davidhaines** [comment]
Good morning Rayhan

Please could you delete all of the Catalog Items?

Many thanks

David Haines
Exams Officer/Librarian

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

Newbury Hall School is committed to safeguarding and promoting the welfare
of children and young people and expects all staff and volunteers to share
this commitment.

**Comment by rayhan** [comment]
Hi,

Can you please email me your library information for deleting catalogs.

Regards,
Rayhan

On Thu, Jun 23, 2016 at 4:32 PM, davidhaines <notifications@github.com>
wrote:

> Good morning Rayhan
>
> Please could you delete all of the Catalog Items?
>
> Many thanks
>
> David Haines
> Exams Officer/Librarian
>
> Newbury Hall
> Enborne Road
> Newbury
> Berkshire
> RG14 6AD
>
> Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
> Email: david.haines@newburyhall.com
>
> Newbury Hall School is committed to safeguarding and promoting the welfare
> of children and young people and expects all staff and volunteers to share
> this commitment.
>
> On 14 June 2016 at 14:48, David Haines <david.haines@newburyhall.com>
> wrote:
>
> > Thanks Rayhan for the prompt reply.
> >
> > I will contact you again in a few weeks when I would like all of the
> > Catalog Items removed.
> >
> > Regards
> >
> > David Haines
> > Exams Officer/Librarian
> >
> > Newbury Hall
> > Enborne Road
> > Newbury
> > Berkshire
> > RG14 6AD
> >
> > Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
> > Email: david.haines@newburyhall.com
> >
> > Newbury Hall School is committed to safeguarding and promoting the
> welfare
> > of children and young people and expects all staff and volunteers to
> share
> > this commitment.
> >
> > On 14 June 2016 at 14:46, Md. Rayhan Chowdhury <notifications@github.com
> >
> > wrote:
> >
> >> Hi,
> >>
> >> Yea, it's possible from our end. Please email your library information
> >> when
> >> you need the cleanup.
> >>
> >> Regards,
> >> Rayhan
> >>
> >> On Tuesday, 14 June 2016, davidhaines <notifications@github.com> wrote:
> >>
> >> > Good afternoon
> >> >
> >> > Is it possible to delete all of the books that are currently listed in
> >> the
> >> > catalog without having to do it one by one?
> >> >
> >> > Thanks
> >> >
> >> > —
> >> > You are receiving this because you are subscribed to this thread.
> >> > Reply to this email directly, view it on GitHub
> >> > <https://github.com/Librarika/Issues/issues/324>, or mute the thread
> >> > <
> >>
> https://github.com/notifications/unsubscribe/AAEdRVx8AS0jOk5n2jRJ_RwsQOLESt8Gks5qLqj-gaJpZM4I1TnP
> >> >
> >> > .
> >> >
> >>
> >>
> >> --
> >> Rayhan
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/Librarika/Issues/issues/324#issuecomment-225885727
> >,
> >> or mute the thread
> >> <
> https://github.com/notifications/unsubscribe/AIaQ4MnUQvZA-ifqEa-Tkpdc3dOrxJb3ks5qLrDQgaJpZM4I1TnP
> >
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Librarika/Issues/issues/324#issuecomment-228011453>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEdRdcsi20lNGg2jOljhIwo9eJG0kMWks5qOmDVgaJpZM4I1TnP>
> .
>



-- 
Rayhan

**Comment by rayhan** [comment]
Ok, I have found your library information already. Cleaned up the catalogs.

Cheers!

On Thu, Jun 23, 2016 at 9:24 PM, Rayhan Chowdhury <ray@raynux.com> wrote:

> Hi,
>
> Can you please email me your library information for deleting catalogs.
>
> Regards,
> Rayhan
>
> On Thu, Jun 23, 2016 at 4:32 PM, davidhaines <notifications@github.com>
> wrote:
>
>> Good morning Rayhan
>>
>> Please could you delete all of the Catalog Items?
>>
>> Many thanks
>>
>> David Haines
>> Exams Officer/Librarian
>>
>> Newbury Hall
>> Enborne Road
>> Newbury
>> Berkshire
>> RG14 6AD
>>
>> Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
>> Email: david.haines@newburyhall.com
>>
>> Newbury Hall School is committed to safeguarding and promoting the welfare
>> of children and young people and expects all staff and volunteers to share
>> this commitment.
>>
>> On 14 June 2016 at 14:48, David Haines <david.haines@newburyhall.com>
>> wrote:
>>
>> > Thanks Rayhan for the prompt reply.
>> >
>> > I will contact you again in a few weeks when I would like all of the
>> > Catalog Items removed.
>> >
>> > Regards
>> >
>> > David Haines
>> > Exams Officer/Librarian
>> >
>> > Newbury Hall
>> > Enborne Road
>> > Newbury
>> > Berkshire
>> > RG14 6AD
>> >
>> > Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
>> > Email: david.haines@newburyhall.com
>> >
>> > Newbury Hall School is committed to safeguarding and promoting the
>> welfare
>> > of children and young people and expects all staff and volunteers to
>> share
>> > this commitment.
>> >
>> > On 14 June 2016 at 14:46, Md. Rayhan Chowdhury <
>> notifications@github.com>
>> > wrote:
>> >
>> >> Hi,
>> >>
>> >> Yea, it's possible from our end. Please email your library information
>> >> when
>> >> you need the cleanup.
>> >>
>> >> Regards,
>> >> Rayhan
>> >>
>> >> On Tuesday, 14 June 2016, davidhaines <notifications@github.com>
>> wrote:
>> >>
>> >> > Good afternoon
>> >> >
>> >> > Is it possible to delete all of the books that are currently listed
>> in
>> >> the
>> >> > catalog without having to do it one by one?
>> >> >
>> >> > Thanks
>> >> >
>> >> > —
>> >> > You are receiving this because you are subscribed to this thread.
>> >> > Reply to this email directly, view it on GitHub
>> >> > <https://github.com/Librarika/Issues/issues/324>, or mute the thread
>> >> > <
>> >>
>> https://github.com/notifications/unsubscribe/AAEdRVx8AS0jOk5n2jRJ_RwsQOLESt8Gks5qLqj-gaJpZM4I1TnP
>> >> >
>> >> > .
>> >> >
>> >>
>> >>
>> >> --
>> >> Rayhan
>> >>
>> >> —
>> >> You are receiving this because you authored the thread.
>> >> Reply to this email directly, view it on GitHub
>> >> <https://github.com/Librarika/Issues/issues/324#issuecomment-225885727
>> >,
>> >> or mute the thread
>> >> <
>> https://github.com/notifications/unsubscribe/AIaQ4MnUQvZA-ifqEa-Tkpdc3dOrxJb3ks5qLrDQgaJpZM4I1TnP
>> >
>> >> .
>> >>
>> >
>> >
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Librarika/Issues/issues/324#issuecomment-228011453>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAEdRdcsi20lNGg2jOljhIwo9eJG0kMWks5qOmDVgaJpZM4I1TnP>
>> .
>>
>
>
>
> --
> Rayhan
>



-- 
Rayhan

**Comment by davidhaines** [comment]
Thanks Rayhan.

Have a good day.

David Haines
Exams Officer/Librarian

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

Newbury Hall School is committed to safeguarding and promoting the welfare
of children and young people and expects all staff and volunteers to share
this commitment.
