### ISSUE TITLE
Due date error

### ISSUE THREAD

**Issue by DyaniPerson** [Librarika/Issues#325]
I tried to set a book as being due on Sept 31, 2016 and the date that appeared when printing the loan receipt AND trying to edit it in the circulations was always Nov 30, -0001. I was able to change the due date to Sept. 30, 2016 with no issues.

**Comment by rayhan** [comment]
I believe it was due to the reason that, September 31 is not a valid date.

On Thursday, 23 June 2016, DyaniPerson <notifications@github.com> wrote:

> I tried to set a book as being due on Sept 31, 2016 and the date that
> appeared when printing the loan receipt AND trying to edit it in the
> circulations was always Nov 30, -0001. I was able to change the due date to
> Sept. 30, 2016 with no issues.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Librarika/Issues/issues/325>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAEdRWZv7Ug8qsMBjLawd9TLPEfLsz_kks5qOa8tgaJpZM4I8Q05>
> .
>


-- 
Rayhan

**Comment by DyaniPerson** [comment]
True, but I would hope smart technology would be there to gently help silly people like me who sometimes don't have the amount of days in a month memorized :) Instead of a confusing date error. Maybe some sort of message instead.
