### ISSUE TITLE
fail to register Phone No.

### ISSUE THREAD

**Issue by syafiq89** [Librarika/Issues#326]
Good Day

kindly you assists me, why my library account failed to update membership phone number?
few times that i had try but still failed/phone number is invalid

my library web : ican_library.librarika.com

thank you in advance
![1](https://cloud.githubusercontent.com/assets/20120758/16327092/fdcb073c-39fe-11e6-9906-7e46cb1edb6e.png)

**Comment by rayhan** [comment]
Please try now, it should be solved.
