### ISSUE TITLE
PRICE Field Missing - from Export All Copies report

### ISSUE THREAD

**Issue by alphauser7** [Librarika/Issues#329]
Hi,

The "**PRICE**" field is **missing** from the 'Export all copies' (Export Catalog items) Report. 
I **really need this field**, hence we I enter values in it.

The report I am referring to is under: Reports >> Export Catalog Items >> Export all copies

Look forward to your reply.
Many thanks.

**Comment by rayhan** [comment]
Will look into this soon.

**Comment by alphauser7** [comment]
Do you have an indication on when this will be done?
Thank you.

**Comment by rayhan** [comment]
Hopefully in a week. 

Regards,
Rayhan

**Comment by rayhan** [comment]
Included.
