### ISSUE TITLE
Private Library displays "new arrivals" to public/non-members

### ISSUE THREAD

**Issue by alphauser7** [Librarika/Issues#333]
Hi,

On the Home page of a Private Library, public users can see titles displayed in a "New Arrivals" rotating carousel at the bottom. 

Can you please fix this? A private library's titles should not be displayed to non-members (or anyone who is not logged in).

Thank you.

**Comment by rayhan** [comment]
Yea, this makes sense.

**Comment by rayhan** [comment]
Should be working the right way now. Thanks.
