### ISSUE TITLE
Email all of a sudden not registered

### ISSUE THREAD

**Issue by TopNoteAcademy** [Librarika/Issues#335]
I set up a new library last night.  This morning, I added a picture to my library account.  Later, I logged out and tried to log back in only to discover that my email is no longer registered with my library.  Help!?!

**Comment by rayhan** [comment]
Very strange case, what else did you do, anything that can help to identify the cause?

**Comment by rayhan** [comment]
I see you have created two different library with two different user account. Did you try with the right account to the right library?

**Comment by TopNoteAcademy** [comment]
Yes, I know I tried the right password with the right account l.  I created
the second account only after I tried logging in with the email I use to
create the account and the original password as I wrote it down.  On top of
that, I tried the second password I created after the original password
failed.  The message I received was that my email l, which was never
changed,  was reported to be a nonregistered email.

All of this happened only after I uploaded an avatar for my library.

A second, unrelated note.   I am not sure where you are located, but I
suspect you are not in the USA or in Europe, or at least not originally.
There are misspellings and wrong words scattered throughout your webpage.
If you wish to attract professional businesses, then there must be a
perfectly spelled website to attract them.

Vicky

**Comment by rayhan** [comment]
Hi,

I see the first library you created using a Gmail ID (vjxxxxxx@gmail.com), that ID is still in the database. You said you updated the avatar of your library, that means the logo from (Manage -> Library Information page), is this correct? In that case I don't find any connection that may trigger changing your user record / password. 

Did you visit your profile settings page before uploading logo? By any chance?

We are located in South Asia. Sorry, we do have some grammatical errors that we are trying to resolve, thanks for your suggestions.

Regards,
Rayhan
