### ISSUE TITLE
Feature request: Member Groups

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#337]
A lot of academic institutions are using Librarika, from schools to universities. However at the moment there seems to be no support for member groups which would allow us to manage classes / year groups / cohorts together. Could this be added? 

-List members in a group
-Rename group
-Filter circulations by group
-Delete all members in group (useful for managing users who have now matriculated)

**Comment by shiv379** [comment]
In the future it would also be useful to be able to restrict circulation by group. This would allow us to prevent children withdrawing books not suitable for their age.

**Comment by rayhan** [comment]
Yes, I agree.

**Comment by rayhan** [comment]
Added functionalities for Member Groups:

-List members in a group
-Rename group
-Filter circulations by group

Other options will be added in the future.

**Comment by shiv379** [comment]
Excellent, thanks! I'll start looking into that soon.
