### ISSUE TITLE
Feature request: Custom Links

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#338]
We can now turn the book stores panel on and off which is great. A really useful addition would be the ability to create our own links to be shown - both direct links, and templates. 

For example:
Http://www.commonsensemedia.org

Or

Http://www.commonsensemedia.org/search/%BOOK-TITLE%

Is this possible?

**Comment by rayhan** [comment]
I'm not sure, there are some high level technical issues for custom domains.

**Comment by shiv379** [comment]
Hi Rayhan, 
I'm not sure  you understood correctly - I didn't mean setting up custom domains for Librarika, just the ability to add a custom link to an external site in the book stores panel (where links to Amazon etc currently are). Does that make sense?

**Comment by rayhan** [comment]
Aha :) got you now.
