### ISSUE TITLE
CVS Generated Reports

### ISSUE THREAD

**Issue by lrcinsb** [Librarika/Issues#339]
I ran the all copies generated report as I wanted to be able to use it to compare to items in my library to make sure that all items are in the correct location and in the correct category and in order to begin pricing all of my books.  I ran the report and more than half of my books show up as having an unknown category.  I do not even have an unknown category in my library, but on this report it is showing up.  I do not want to have to manual change everyone as I have already input all of my books and this would be doing a report so doing the work twice.  Is this just a bug in the report?  I need this report as I need to get the information added in within the next week for an audit of our library and we just recently switched to librarika.

**Comment by a1437** [comment]
I need more detail about your library. 

Did you upload all categories from CSV? Do you have any items without any specific category? Did you use Smart Add? What is your library name?

Please let me know so that I can help.

Regards,
Rayhan

**Comment by rayhan** [comment]
I need more detail about your library.

Did you upload all categories from CSV? Do you have any items without any specific category? Did you use Smart Add? What is your library name?

Please let me know so that I can help.

Regards,
Rayhan

**Comment by lrcinsb** [comment]
I manually input all of my books, I did not upload anything using the CVS
file.  What I am trying to do is export the CVS file under reports and in
order to have a complete print out of the books in my library.  I used
Smart Add to add most of the books and manual add for those that were not
included.  All of my books are in specific categories

My library is https://lrcsb.librarika.com/

**Comment by rayhan** [comment]
I guess I have found the reason. It's a bug with exporting copies, I see your books have categories attached to them. I'm gonna fix it soon. 

Thank you.

**Comment by rayhan** [comment]
Hi, the fix has been applied, can you please confirm now?

Thanks,
Rayhan

**Comment by lrcinsb** [comment]
I will check today thank you.
