### ISSUE TITLE
Reminder emails not being sent

### ISSUE THREAD

**Issue by books9123** [Librarika/Issues#342]
For the past week or so, I and all of the members of my library have not received any reminder emails for items being due soon, overdue, or hold emails. I have checked my account many times to ensure that all of the reminder settings are turned on, and that there is the correct email address in the system for each member. Still, no emails have been received. Please let me know if you need any more info on this problem. Thanks!

**Comment by rayhan** [comment]
Yes, there was a new bug last week that prevented some reminders. We have added a fix, reminders should be going fine now. I have tested a couple of reminders.

Please let me know if new reminders are not going through.
