### ISSUE TITLE
Email alerts not being received

### ISSUE THREAD

**Issue by ppring** [Librarika/Issues#343]
Hi there - it seems that reminder emails are not received by our members.  This has happened since we started using Librarika.  I have checked our settings and they are supposed to be receiving reminder alerts.  Thanks.

**Comment by rayhan** [comment]
Yes, there was a bug last week, but reminders should now be ok now, we are monitoring reminders for last two days and seems going through. 

Please let me know if you still have issues with new reminders.

**Comment by ppring** [comment]
Hi there - as the administrator, there have been a number of library requests that I haven't received.  It seems to be hit and miss....

Can you look into that?
