### ISSUE TITLE
Circulation reports

### ISSUE THREAD

**Issue by HawksLibrary** [Librarika/Issues#345]
Hi, I was wondering if there was a report to show how many students are borrowing books & how many books are being borrowed? thank you

**Comment by shiv379** [comment]
Under Reports that is a Circulations report with the information you would need 
https://MYLIBRARY.librarika.com/reports/circulations

**Comment by shiv379** [comment]
Also for a high level view you can see the number of issued and overdue books on the Circulations page https://MYLIBRARY.librarika.com/media_bookings/
