### ISSUE TITLE
search not finding items

### ISSUE THREAD

**Issue by patricewith6** [Librarika/Issues#346]
I'm finding that frequently items in our collection do not come up in a search. For example, the title "You'll never walk alone" doesn't come up until you eliminate the word "you'll". Then it comes up twice as "You'll never walk alone"!! This seem to happen randomly - and frequently.

**Comment by shiv379** [comment]
It's it due to apostrophe in the title? Does it work with or without the apostrophe when you search? 
Do you have two entries in your database for this title?

**Comment by shiv379** [comment]
It's it due to apostrophe in the title? Does it work with or without the apostrophe when you search? 
Do you have two entries in your database for this title?

**Comment by patricewith6** [comment]
I doesn't work either way - with or without the apostrophe. And yes, I do have two copies of this title (one is masters, one is copies). I have had several other titles that I input and then can't call up by title when I'm finished. Search seems very glitchy and inconsistent.


________________________________

**Comment by shiv379** [comment]
Could you give a few specific examples with what is happening? This will help investigating, thanks.

**Comment by patricewith6** [comment]
Except for the "you'll" piece, I can't remember the others. I'll try to write them down next time it happens; maybe I can figure out a pattern.


________________________________

**Comment by patricewith6** [comment]
Here's another example: I just cataloged a title called "Fort Walton Adventure". Then I had to look it up again and typed in "fort walton" - it showed 0 records found. I then typed in the accession # and the title "Fort Walton Adventure" came up.


I have also noticed that if there is any punctuation in the first word - such as "you'll" or "we're" or "Beethoven's" that the search won't work.


________________________________

**Comment by patricewith6** [comment]
Here's another one:

Title is... Carol of the Bells

If I search under the default, it doesn't come up - although several other items with the same title do come up.

If I search under title, then it comes up.


________________________________

**Comment by organarchive** [comment]
I am having the same issue - the search function when set on default, simply doesn't seem to work. If I refine down to title or subject, I can get results, but the initial search box so far doesn't seem to find anything.

Thanks for any and all help!
