### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#348]
I (and other users) have been getting a lot of "network error" messages when trying to check out books. Several page refreshes and clearing the cache seem to eventually fix this, but then it comes back intermittently. We have had no problem accessing any other web pages.

**Comment by rayhan** [comment]
Hi,

I'm using the site without any issue, this is happening for how log?

Regards,
Rayhan

**Comment by shiv379** [comment]
I've noticed this intermittently over the past two weeks.  Strangely it also seems to clear sometimes when I try to scan a different book.

**Comment by rayhan** [comment]
Any idea on which pages you face this issue mostly? Or is it related to checkouts only? I'm trying to narrow down my investigation.

Thank you very much for reporting.

**Comment by shiv379** [comment]
This has been happening  only on the Circulations page when circulating a book. It keeps happening but it seems like clearing browser cache *might* help fix it. 

Is there any way I can find more information for you when this happens? A log or something?

**Comment by rayhan** [comment]
Yes, snapshots will be helpful.

**Comment by rayhan** [comment]
Is this problem still happening? Can you please share some screenshots if it happens?

**Comment by shiv379** [comment]
Hi, 
Still happening occasionally. I keep forgetting to get a screenshot but there's not much to see, just the popup message. I'll try to remember to capture it this week.

**Comment by rayhan** [comment]
Okkk

**Comment by shiv379** [comment]
[screenshot.docx](https://github.com/Librarika/Issues/files/619186/screenshot.docx)

**Comment by shiv379** [comment]
We are still getting this at least once a day

**Comment by rayhan** [comment]
Thanks, added an under the hood improvement, still watching.

**Comment by findlefish** [comment]
Network error when I use "Contact us" or resent invitation. It's been there for the whole day
