### ISSUE TITLE
BUG Discover page showing books not in library

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#353]
Our discover page is showing books that are not in our library database. This is particularly worrying as some of the books showing could be inappropriate for primary school children. Please fix this ASAP - if there is a risk of inappropriate content we may have to close our library!

**Comment by rayhan** [comment]
In appropriate content is unexpected to us all. Will have a solution ASAP. Please don't worry.

Thank you very much for reporting.

**Comment by shiv379** [comment]
Thanks! What is inappropriate for a primary school will be very different from other contexts. So any Young Adult books, romance, and various adult books are not suitable for the young children to see. The Discover tab would be fantastic if it only listed books from our own library - its a bit pointless listing books we don't have! 

Thank you very much for your understanding  and support!

**Comment by rayhan** [comment]
A new control has been added to hide discover section from a library. Please navigate to Manage -> Preferences section and check "Hide discover" to disable Discover section.

Thank you.

**Comment by shiv379** [comment]
Thank you!
