### ISSUE TITLE
ILS Closing

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#356]
Hi
I would like to know how to delete the library or close the online library fully.

**Comment by rayhan** [comment]
May I know why you want to close the library? Is there is critical problem you are facing?

Thank you.

**Comment by SAIprasannaK** [comment]
Sir we are closing the library due to a financial funding problem.

**Comment by rayhan** [comment]
Sorry to hear that, its happening more with libraries worldwide in the last couple of years, wish you all the best.
