### ISSUE TITLE
Feature request: Member's borrowing history

### ISSUE THREAD

**Issue by HIALibrary** [Librarika/Issues#360]
It would be great if a feature could be added for viewing the borrowing history of members. If this was offered with the upgraded plan then I would certainly pay for that!

Thanks,
Tim

**Comment by JennieMay** [comment]
Go to 'Reports' then 'Circulations Advance Options' - type in Member number or name, amend the starting date then press the Filter button. You will then have a list of all items borrowed during the chosen period. A bit clunky, but gets the result you want. Hope this helps!
