### ISSUE TITLE
The Page not loading. 

### ISSUE THREAD

**Issue by PGS-Admin** [Librarika/Issues#368]
Every day librarika system goes off saying this site cannot be reached usually twice per day and it happens with other users to.

**Comment by rayhan** [comment]
We will take immediate measures to resolve this. Please keep us posted if page loading behavior changes.

Thank you very much for reporting.

**Comment by rayhan** [comment]
We have taken several improvement measures, is everything all right now?

**Comment by PGS-Admin** [comment]
yes. Thank you


Regards
Niall Quinn
Email: nquinn@penistone-gs.uk
Phone Number: 01226 762114 (Ext. 1260)

Penistone Grammar School ALC
Email: enquiries@penistone-gs.uk<mailto:enquiries@penistone-gs.uk>
Website: http://www.penistone-gs.uk/



________________________________
