### ISSUE TITLE
Stuck on generating barcodes.

### ISSUE THREAD

**Issue by yeshivaboys** [Librarika/Issues#370]
I am on the free library, having under 2000 books.  It says the beta testing allows me to print barcodes.  That was going fine when I did less that 20 barcodes.  I have in queue 100 barcodes and it will not let me generate the barcodes.  THey are sitting in the queue.  I'm scared to refresh or I will lose the ability to print then at all.  My library is Rafi Estrin.  Please help. 
The error message I get is
This operation will exceed generate queue, please print them first.
But there is nothing to print - only 100 barcodes sitting in the queue.

**Comment by rayhan** [comment]
I believe your problem is already solved by our mail communication, so closing this issue.

Thank you very much.
