### ISSUE TITLE
Export titles

### ISSUE THREAD

**Issue by jmatthewssummit** [Librarika/Issues#385]
I need to do a collection analysis and cannot export my titles.  It says waiting and never loads.  Finally got an error that says "no data returned". I have had our IT specialist run diagnostics on our end.  It is not our servers or firewall.  

This needs to be completed soon.  Please help.

**Comment by rayhan** [comment]
Please submit your request with library name and detail at our web contact us form, so that we can identify your problem and give a solution.

**Comment by CapSchool** [comment]
Hi Rayhan, 

We are a new user of Librarika and we are planning to upgrade our plan and your CONTACT US page is not working. I am trying to reach you and ask some questions but an error always pop up in my screen. Can you please give me your direct email? here is my email: maricel@capitalschooluae.com
looking forward for your reply.

**Comment by rayhan** [comment]
@CapSchool mail sent.

**Comment by rayhan** [comment]
We added page by page download option for large catalogs. Hope this problem is solved now. 

Thank you very much.
