### ISSUE TITLE
Availability by branch in Collection view

### ISSUE THREAD

**Issue by petrfaitl** [Librarika/Issues#400]
As we're considering joining several related libraries together, it is essential that the user can view branch availability of a title in list view. Currently the availability is on in a title detail view, which requires the user to go into the title one by one to view where the book is located.

From my experience from Kotui libraries in NZ, this location view enables users to prioritise requests for local titles, thus reducing transport costs for the library.

An alternative solution, would be to offer controls to restrict the view results list to a particular branch or to All branches.

**Comment by rayhan** [comment]
Thank you for your suggestions, we are planning on this.
