### ISSUE TITLE
Bulk import without pictures

### ISSUE THREAD

**Issue by thefamilyinstitute** [Librarika/Issues#403]
Hi, 
I am writing again because the answer I received was not clear. We did a bulk import of books and the pictures did not load. When we added them through smart add, the pictures loaded and were fine. I understood that if we requested it, you would be able to load the pictures for us but it has been quite a while and we still do not have pictures for the majority of our books. Please advise!

**Comment by thefamilyinstitute** [comment]
Hi, 
I am still waiting for help on this. Thanks!

**Comment by rayhan** [comment]
We are going to investigate this, thank you for your queries.

**Comment by pjleman** [comment]
I've done an import of a single book to see if the cover was added via some background process later.
It wasn't - should there be such a background process?
