### ISSUE TITLE
Unable to check out more than 10 copies of the same book

### ISSUE THREAD

**Issue by TrevCorkIreland** [Librarika/Issues#411]
Hi Everyone,

I've just started using Librarika and I think it's great - that is until I tried checking out more than 10 copies of the one textbook in my school library. When I was assigning books to a member, I'd type in the name (or the first few letters) of the textbook in the box...a dropdown box would let me select the copy I wanted. As I checked out each copy to various members, the list went from "green" to "red" ....as I checked out each copy the dropdown box ended up full of checked-out books and no longer gave me books with green dots beside them?! 

![image](https://user-images.githubusercontent.com/31295869/29665700-3f42f1e8-88cd-11e7-84a9-7cc5927d2010.png)

Please, if there is anyone out there that can help me, i'd be grateful - i've spent ages sourcing this freeware for my school and now I feel it's been a waste of time. Thank you.

**Comment by rayhan** [comment]
Using accession number (not the book ISBN) is the best way to checkout books. If you have more than 10 copies of the same book, you can also use barcode labels to quickly identify and scan the copy you are checking-in or out.

A detail answer has been given via email, hope this issue is resolved.
