### ISSUE TITLE
List of Books without Photos Is Not Working Anymore (was issue #82)

### ISSUE THREAD

**Issue by nahurfonseca** [Librarika/Issues#415]
When I go to:
Report / Catalog Items 
Then check "Missing Fields: [x] Photos".
And then click on "Filter"
Nothing is displayed.
Even though I use a wide range for date of creation.

It used to work.
Something changed.

Also, how can we help with the code?

**Comment by rayhan** [comment]
This feature is working and nothing has changed since then. Will you please provide more information about your library via email. 

Thank you.

**Comment by nahurfonseca** [comment]
My library is

akssma.librarika.com

When I try to use this feature, it complains that I need to enter a Media
ID or ISBN.

-nahur

**Comment by rayhan** [comment]
Please leave this field empty and adjust created date from and click on missing photo check-box. It works smoothly as I have tested. 

![image](https://user-images.githubusercontent.com/73029/30146956-08558786-93bd-11e7-8642-5942500fa70e.png)

**Comment by nahurfonseca** [comment]
Indeed.
Thanks.
