### ISSUE TITLE
POOREST SEO

### ISSUE THREAD

**Issue by mayeenulislam** [Librarika/Issues#417]
Search Engine Optimization is too poor in Librarika.
I opened my library with 4 books trial-basis, and it's been a week then - I googled with the term "রবোনগরী জ্ঞানসুধা", and nothing found in return. Where as the book in my library has a public link available:
https://gyanoshudha.librarika.com/search/detail/1833034

The most important thing why people should go with online catalogues is to let the user find their desired item on search engine's results.
As of minimal to no SEO I should think again to go with Librarika before entering more books.

**Comment by rayhan** [comment]
It depends on google's own algorithm. If you have unique contents, they index quickly.

We will see what we can do to improve this.
