### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by svanl** [Librarika/Issues#421]
I set up a library with my email account and input several records.   However, I needed to use a different email account for the administrator account.  So I went into the settings, then to the administrator account and changed the email address.  Since this change I have not been able to get into the library. The error message says that the email address is not recognized. When I try to reset the password it can't be reset because it doesn't recognize the new or old email address.  How can I get back into my library?

**Comment by rayhan** [comment]
I have already replied to your questions in feedback form. Hope the problem is solved.

Thank you very much.

**Comment by svanl** [comment]
Thank you for replying. Yesterday the system recognized the new email
address and I was able to get it in. At that at time I created a backup
admin account.

Thanks,
Sylvia
