### ISSUE TITLE
Cannot Launch Site

### ISSUE THREAD

**Issue by lkl21** [Librarika/Issues#424]
When trying to load our library the link just spins...nothing opens.  When I try to access through https://librarika.com an HTTP 500 error comes up.  I cannot load Librarika in any way. Is the site under construction?

**Comment by shiv379** [comment]
Same here, can't access our library.

**Comment by rayhan** [comment]
Yes, we are having some issue with a traffic spike, trying to resolve this ASAP.

Thank you very much for your kind patience and support.

**Comment by alphauser7** [comment]
Hi, still 14 hours on and still can't access our library nor the main librarika.com website! We need urgent access! What's happening?

**Comment by TheHungryCaterpillar** [comment]
Does this happen frequently? I was planning to inaugurate my library during Durga Pooja .

**Comment by jlovestmichaels** [comment]
Having tried to access site with same problem as IKL21 I now get message 404 Not Found. Please some info on how long this is likely to go on for.

**Comment by rayhan** [comment]
Still working on to bring it back. We are working constantly on this, will update once we are up.

**Comment by rayhan** [comment]
The service is back. Hopefully everything should be fine. We are still monitoring for performance issues. Please let us know if there are issues.

@TheHungryCaterpillar this happened for the first time in our 5 years service. We will take more counter measure to avoid such issue once we are fully recovered.

Thank you very much.

**Comment by TheHungryCaterpillar** [comment]
Thanks Rayhan. 

The site was up for few hours. Looks like it has gone down again :(

**Comment by JennieMay** [comment]
Still down  :(

**Comment by JennieMay** [comment]
Yay - thanks, Rayhan!
