### ISSUE TITLE
Two patrons cannot login

### ISSUE THREAD

**Issue by eibei** [Librarika/Issues#426]
I have two patrons who cannot login to my library. We use this library for our graded reader library at a university in Japan. I have two students who have accounts, but cannot login. Following the "forgot password" link doesn't work. Once student changes her password, but still can't login. The other student doesn't even receive the email despite the email being the same as the one that shows in the member list. What can be done?

**Comment by rayhan** [comment]
Would you please share us the email address of the two users using Librarika -> Contact Us form?

Thank you very much.

**Comment by eibei** [comment]
I tried that and got "Network Error! Please try again."
