### ISSUE TITLE
reset barcode label printing with no prefix?

### ISSUE THREAD

**Issue by curclibrary** [Librarika/Issues#441]
As new users, we were trying to print out labels for books without a barcode label on them. The printing setup was confusing and we clicked a mistake, and now our labels all have prefixes.  For example, the book with accession number 14 has a printed label of A14, and when the label is scanned, the book does not come up. Librarika can only recognize it as 14.  Can we reset the printing options to NOT have the prefix? We are not sure what to do at this point, as the labels with prefixes will be useless for our system. We are planning to upgrade, but was trying out the new beta system while it is free.  We need to make sure the printed barcodes will work.  Please help. 

We look forward to your response as we are hoping to get our library set up as soon as possible. Thank you!

**Comment by StClairAdmin** [comment]
Hope this isn't telling you something you have already tried.

  On the Print Barcode page, click Print Completed?
  Go back to the Barcode Queue page and re-enter your accession numbers.
  Go to Generate Barcodes.  At the bottom of the page, click Remove Prefix and click submit.
  Barcodes should print ok, but check the print preview before you print.  

  Also, if you get a message at the top of the print preview in a rectangular box, your labels will not 
  print correctly. To fix this, cancel the print preview, click on Generate Barcodes again and then 
  click on Print Barcodes again. When you look at the print preview, the message should be gone 
  and the line-up should be fine.

**Comment by curclibrary** [comment]
That works. Thank you so much!

**Comment by acdc70** [comment]
I am new to this so apologies if I am doing this wrong.  I don't know if I should continue with this issue or create a new issue. I thought I should keep related issues together.

I started using the trial a few days ago.  When I generated the (copy) barcodes, I checked on "Remove Prefix" but it are still there.  I also tried doing what was recommended StClairAdmin on 7 Dec 2017, I still couldn't remove the prefix.
Is it because I am using the trial version?

**Comment by StClairAdmin** [comment]
We only use the free version of Libarika and can print labels with no problem, but it took a lot of trial and error. I have written detailed instructions (about 9 pages) to print labels and if you will send your e-mail address to office@stclair.church I would be happy to send them to you. Then if you still have problems, we could talk through e-mail.
Linda

**Comment by acdc70** [comment]
Thanks, Linda. I'll e-mail you in a short while.

**Comment by StClairAdmin** [comment]
Hi

Did you ever get your problem resolved?

Linda
