### ISSUE TITLE
DYMO Bar Code Printer Does Not Print

### ISSUE THREAD

**Issue by RoletteCityLibrary** [Librarika/Issues#443]
This is driving me nuts!  Reinstalled driver.  Setup according to printed instructions.  Ready to print with appropriate Print settings.  Nothing!  Zip!  86!  Nada!  One blank strip after another.  Suggestions???
Thanks in advance.
Gnawing on Nails in North Dakota

**Comment by rayhan** [comment]
I believe you have already figured it out, please let us know if otherwise.
