### ISSUE TITLE
Bulk Upload error

### ISSUE THREAD

**Issue by KHawke** [Librarika/Issues#444]
Hi guys, all fields completed following the template but I get a general error status code.  It allows me to upload the CSV and it says **OK** next to each new member, but when I click on "add new 200 members" for example I get the same page but it just says **error** in red instead of OK.

**Comment by StClairAdmin** [comment]
I don't have a solution for you, but I do have a question.  How do you upload a CSV file? I can't find that option anywhere in the main menu items.  Could it only be available for paid plans, or is it something outside of Librarika?

Thanks...
