### ISSUE TITLE
Search under "Default" doesn't search for ISBN

### ISSUE THREAD

**Issue by alphauser7** [Librarika/Issues#448]
Hi,

When searching for a book (using the top right search text field, entering an ISBN in the text field and leaving the search type as "Default" does not bring up any records. Only when then selecting ISBN in the Dropdown search menu does the item then come up. I do recall that this wasn't the case before. I was previously able to leave the search type dropdown menu as "Default" and simply enter the ISBN and click search and the item would come up. But now this is not the case.

Can you please include the ISBN under "Default" search.

Thanks.

**Comment by rayhan** [comment]
ISBNs are included in default search. Hope this issue is resolved.
