### ISSUE TITLE
OPAC Catalog - a Display ALL page?

### ISSUE THREAD

**Issue by alphauser7** [Librarika/Issues#450]
Hi,

At the moment its hard for users to browse the Catalog without either searching or by Alphabetical selections. This limits the users when wanting to simple browse through the Catalog.
Is it possible to have a "DISPLAY ALL" items in the OPAC section? Two suggestions; you can have the "OPAC Catalog Search" page simply defaulting to displaying all listings with thumbnails when clicking on the "Catalog Search" link on the top Nav bar, and/or; you can include an "ALL" link in the "Database A-Z" page.

Hope you can help.

Thanks.

**Comment by petrfaitl** [comment]
I would like to second this suggestion.

**Comment by rasel2001** [comment]
To view all catalog on OPAC, we have new menu `Catalog` and `search catalog' option as well.
