### ISSUE TITLE
Adding Books says ISBN already exists 

### ISSUE THREAD

**Issue by AmeenZami** [Librarika/Issues#452]
I tried to add a new book for my library with new ISBN but it says "A catalog item "XYZ" with the same ISBN already exists. Please click here to add a new copy of the same item.

**Comment by alphauser7** [comment]
I too have been having this problem recently. There is definitely no other title with the next ISBN. The system does add the title, but it shows this error. If I go back and search for newly added title i can find it. So the error is appearing without reason. It's definitely a Bug.
Please see my other post with the original problem (https://github.com/Librarika/Issues/issues/438)

Still no solution. Could you please assist?

**Comment by AmeenZami** [comment]
I Found, If you type ISBN number wrongly or miss the a number from ISBN, this problem may come to stage so be aware of typing ISBN.

**Comment by pjleman** [comment]
I've often seen this error recently but the new ISBN is typed correctly. The catalogue item with the "same ISBN" is always the same one.

The new catalogue information does get entered into the system. Just an annoying error message.

**Comment by alphauser7** [comment]
Yes this is definitely a bug! Lots of us are experiencing the same issue, and like we all confirmed the ISBN is definitely unique and not used by another item on the database. Like "pjleman" and I said, the error comes up, yet the item is added. So it's an annoying incorrect error. So once again, the ISBN was NOT used before, and it still gives this error. Hope you can fix the bug.
Thanks very much.

**Comment by rayhan** [comment]
Will you please share few ISBNs and your library name with which this error occurs. This will help us to dig down this bug. You can privately share the information in out contact us page.

Thank you very much.
