### ISSUE TITLE
Default Search not finding books

### ISSUE THREAD

**Issue by mbounds1** [Librarika/Issues#453]
In our catalog we are having an issue with MANY books not coming up when you search by "default"  or "keyword" and type in the title. This is mostly happening with recently added books (last 2 months). I am attaching a screenshot to show and example. 
![screen shot 2018-01-12 at 10 49 58 am](https://user-images.githubusercontent.com/35376253/34883207-f22be184-f786-11e7-9316-3d5f3981f918.png)
![screen shot 2018-01-12 at 10 50 07 am](https://user-images.githubusercontent.com/35376253/34883210-f37b8e40-f786-11e7-967f-2af3282bfaea.png)

**Comment by vsolas** [comment]
I am having the same issue. Searching an author in the default setting does not bring up any results, even though there are definitely items in the catalog by that author.

**Comment by rayhan** [comment]
This should already be resolved. Are you still facing issue with default search?
