### ISSUE TITLE
Can't Delete item from Catalog

### ISSUE THREAD

**Issue by nyarasha** [Librarika/Issues#46]
I can figure out how to remove a copy of a book in my catalog so that the number of copies is 0. However, I can't figure out how to completely remove an entry of a media item from the catalog. This is really important.

**Comment by Naufalks** [comment]
how to remove or clear all catalogs from librarika please help any one , I can remove one by one but i need to remove all and upload a fresh list into

**Comment by Sonny-Crockett** [comment]
I am having the same issue. I want to remove all of my items and start over. Is just getting a new library better at this point?
