### ISSUE TITLE
Circulation is disabled for this item

### ISSUE THREAD

**Issue by ruthhaz** [Librarika/Issues#465]
I keep getting this error message no matter what book I try to check out. Permissions are enabled for self service and all books are ticked as in circulation.

**Comment by DrShockz** [comment]
Same here, please fix this. Make a good first impression for me!

**Comment by spookydel** [comment]
Also an issue for us - this appears to be a site-wide issue today.

**Comment by warriorgirl** [comment]
I have also been having the same issue and i have 250 children's books to check out. please resolve this issue as soon as possible

**Comment by rayhan** [comment]
This issue should already be resolved. Are you still facing this problem?

Sorry for the inconvenience.

**Comment by spookydel** [comment]
All sorted now

**Comment by warriorgirl** [comment]
Hi

It has been resolved now.

thank you
