### ISSUE TITLE
Can't delete my library / account from Librarika

### ISSUE THREAD

**Issue by nyarasha** [Librarika/Issues#47]
I can't delete my information, library / account from Librarika. Please add the ability to remove my information from the site.

**Comment by rayhan** [comment]
Though its difficult for us to see you go, there should be option to delete/cancel my account.

Good News. 
The option to delete library account is now available, its under Dashboard -> Library -> Library Information.

Thanks.

**Comment by nyarasha** [comment]
@djcerqueira Sure, it's got some bugs. There is a difference, however, in encouraging users to stay vs making it impossible to remove their information from the system.

@rayhan Thank you very much for adding this feature!
