### ISSUE TITLE
Not recognising accession numbers

### ISSUE THREAD

**Issue by themrsreads** [Librarika/Issues#472]
My library has around 100 titles that are showing up when I look down the catalogue list but don't appear when I search for them specifically or attempt to print off a barcode for them. I have attached two screen shots as an example. Look for accession number 1579. Thanks.
 [
![screenshot 8](https://user-images.githubusercontent.com/37791582/37889848-384de63a-30c6-11e8-82dd-bf3d81c4fe4b.png)
![screenshot 9](https://user-images.githubusercontent.com/37791582/37889861-3da8fcaa-30c6-11e8-90be-c7ce7d07d64d.png)

](url)

**Comment by rayhan** [comment]
Item should appear now. Accession number has been added to default search index. 

BR

**Comment by themrsreads** [comment]
So sorry to be a bother but it still doesn't seem to be recognising it. When I go to add it to the barcode queue it says 'item not found'. But if I go to my catalogue it is there. This is the same for books  1575 - 1690.
