### ISSUE TITLE
I can't access my Library

### ISSUE THREAD

**Issue by LibbyEdge** [Librarika/Issues#476]
Hi,

I've logged into Librarika today and gone to the 'My Libraries' option under my user icon, the screen changes to show the log in option for my library  Elmhurst Library, Institute: Elmhurst Ballet School, URL: https://elmhurstlibrary.librays.com.  Then when I click on the Access Library box I am just getting the following error message: 

This site can’t be reached
The webpage at https://elmhurstlibrary.librays.com/users/login?inSiteLogin=1&code=66a92be60ffc438dfd49fac71b6c33fe might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

What can I do?

**Comment by rayhan** [comment]
Resolved already.
