### ISSUE TITLE
forbidden to update media record

### ISSUE THREAD

**Issue by ericancollege2018** [Librarika/Issues#479]
could you assists me regarding this matter

error on update media record

![picture3](https://user-images.githubusercontent.com/38448976/38846607-d863fba8-422f-11e8-8bb4-6fd9f1c29b69.png)
![picture4](https://user-images.githubusercontent.com/38448976/38846609-d90d942e-422f-11e8-9663-7f5e5b0dcaa2.png)

**Comment by rayhan** [comment]
Would you please try refreshing your browser cache. 

Browser specific instructions are given here: https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache

Please let me know if this solves the problem.

**Comment by ericancollege2018** [comment]
i have done refreshing my browser cache according to all instruction

but still same, fyi only this title of book we unable to update and still forbidden 

however we manage to update different book without any problem

**Comment by rayhan** [comment]
This problem has already been resolved.
