### ISSUE TITLE
can't search authors whos name contains letter š

### ISSUE THREAD

**Issue by nb-tg** [Librarika/Issues#48]
I can't search authors whos name contains letter š (croatian alphabet), bug?

**Comment by rayhan** [comment]
Hi,

Our next update will include solution for searching with these special characters, our apology for this temporary inconvenience .

Regards,
Rayhan

**Comment by maroga** [comment]
Hi Rayhan,
Thank you very much for the update.
Is there any expected date for the update?
Thank you in advance
Best regards

Marga

**Comment by rayhan** [comment]
Hopefully, this is fixed. Please let me know if you still face the problem.

**Comment by maroga** [comment]
Hi,
I confirm you that it is working :-)
Thank you.

Marga
