### ISSUE TITLE
Issue creating a new library

### ISSUE THREAD

**Issue by schutth** [Librarika/Issues#480]
I tried to create a new library but after filling in all the details I do get an "Internal error".

Anybody that can assist please? I see I am not the only one with this problem.

![image](https://user-images.githubusercontent.com/38464008/38870323-c37b3b3e-424d-11e8-9094-522beadf6334.png)

**Comment by rayhan** [comment]
We are going to check the issue. 
Thanks for reporting this.

**Comment by rayhan** [comment]
Please try now. It should be alright.

**Comment by schutth** [comment]
Hi

Thank you I will check again tomorrow.

Regards

Henk Schutte

Sent from Outlook<https://aka.ms/qtex0l> (iPhone 6S - iOS 11)
________________________________

**Comment by schutth** [comment]
Hi

Thanks for your support. I managed to create a library this morning.

Groete / Kind Regards

Henk Schutte
Software Developer and IT Consultant

F:         086 628 8362
C:         082 550 7249
Email:  henk.schutte@live.co.za<mailto:henk.schutte@live.co.za>
