### ISSUE TITLE
Barcodes won't scan

### ISSUE THREAD

**Issue by rwatts08** [Librarika/Issues#487]
When I print off my member barcodes, any with a number less than 100 will not scan.

When I try to use the different codes they come up with other people's names.

**Comment by timowen2** [comment]
Low numbers on barcodes are always difficult to scan, this is a scanner problem and not the software. I suggest you use at least a five digit number then you should not have a problem.

**Comment by timowen2** [comment]
I don't think this can be a bug, or possible to enhance. Part of the barcode is a checksum and these just don't work for small numbers
