### ISSUE TITLE
Payment Not Going Through 

### ISSUE THREAD

**Issue by ESMairene** [Librarika/Issues#497]
Hello,

We are a school based in Mongolia trying to subscribe for a whole year to Librarika. However, every time the accountant tries to process the payment, the site turns completely white. No money has been deducted from our account yet, but she's too worried to try again. I've already emailed 2Checkout - but I wanted to know if this issue has ever happened before. 

Best wishes,
Irene

**Comment by rayhan** [comment]
Sorry to hear that, this issue has not been raised before. Will you please update us if everything is alright.

**Comment by ESMairene** [comment]
Hello, 

The issue still hasn't been resolved. Is there any alternative payment method?

**Comment by rayhan** [comment]
Payment from other people is going through. Would you please send us some screenshots to our email at info@librarika.com, so that we can further investigate.
