### ISSUE TITLE
Fusion of records (author / editor)

### ISSUE THREAD

**Issue by ghost** [Librarika/Issues#499]
When using the smart filling option sometimes by mistake has been created duplicates of author and editors. Should be very practical if can be a "fusion" option.

**Comment by rayhan** [comment]
Would you please explain this a bit more?

**Comment by acdc70** [comment]
I have seen this in other library software where two entries can be merged and the bibliographic records linked to each author heading are linked to the merged entity.  I know of one that has this feature on author and subject.
This could be an enhancement request.
