### ISSUE TITLE
Import Data Error

### ISSUE THREAD

**Issue by tjdickinson** [Librarika/Issues#503]
I have a CSV file with 8 items. The columns all match the columns on the template. After selecting the file in the import page, it asks me to review my data. I click the 'Confirm Data' box, and then 'Process Upload'. The next page says:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

Thank you in advance for your help.

**Comment by rayhan** [comment]
Hi,

We have updated our bulk import methods. Now you will see more details on what went wrong and can correct your source file for bulk import.

Thank you very much.

**Comment by SDMasters** [comment]
I too am having this problem. I have 1293 records. I divided them into two CSV files. The first CSV has 500 records and the second has the remaining 793. The CSV file with 500 items uploaded successfully but the second file with 793 continues to give me an Internal Error message after I confirm the data and tell it to process the upload. 

I tried this for two consecutive days using Chrome, Firefox and Safari browsers. It made no difference.
