### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by vicmwa** [Librarika/Issues#508]
![capture](https://user-images.githubusercontent.com/37795961/42862862-dde92486-8a69-11e8-8a90-44b4a54da360.PNG)

**Comment by englishcaddy** [comment]
I'm experiencing the same problem...
![librarika errors](https://user-images.githubusercontent.com/41357690/42862973-d28ac372-8a61-11e8-8e50-539cbd261b08.png)

**Comment by rasel2001** [comment]
Hi,

The system is now up and running. We worked constantly without any break to bring the system up. Hopefully everything is alright now. 

Thank you very much.

**Comment by vicmwa** [comment]
We thank you for your dedication

Victor Gatahi 
Knowledge Management Consultant 
 
Oraro & Company Advocates 
ACK Garden Annex, 6th Floor, 1st Ngong Avenue 
P.O. Box 51236 - 00200, Nairobi, Kenya. 
T: +254 20 271 3636 / +254 20 271 1480 
M: +254 722 203 054 / +254 733 333 447 
E: victor@oraro.co.ke | W: www.oraro.co.ke   




-----"rasel2001" <notifications@github.com> wrote: -----To: "Librarika/Issues" <Issues@noreply.github.com>From: "rasel2001" <notifications@github.com>Date: 07/18/2018 06:33PMCc: "vicmwa" <victor@oraro.co.ke>, "Author" <author@noreply.github.com>Subject: Re: [Librarika/Issues] cannot log in (#508)Hi,
The system is now up and running. We worked constantly without any break to bring the system up. Hopefully everything is alright now.
Thank you very much.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

This e-mail and any attachments may contain information that is confidential, legally privileged and protected by law and is intended for the sole use of the named recipient(s). Any unauthorized review, use, or disclosure or distribution is prohibited. Any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting on any information contained in this email is hereby excluded. If you are not the intended recipient, please delete the contents and notify the sender immediately; do not disclose the contents to any other person, use it for any purpose or store or copy the information in any medium. For further information about Oraro & Co Advocates, please contact us at ACK Garden Annex, 6th Floor, 1st Ngong Avenue, P. O. Box 51236-00200, Nairobi, Kenya, telephone: +254 20 2710426/271580/2713636  Fax +254 20 272709 or visit our website www.oraro.co.ke
