### ISSUE TITLE
Biblio field

### ISSUE THREAD

**Issue by acdc70** [Librarika/Issues#510]
I started using the trial version a few days ago. May I know what the Biblio field to used for?

**Comment by rayhan** [comment]
Some books have biblio reference information inside the book covers. If there is any then use this field to enter those information.

"A note about a bibliography, discography, filmography, webliography, and/or other bibliographic references in an item. Use field 504 also to indicate the presence of a bibliography, etc., in accompanying material that is described in the record. For multipart items, including serials, the note may pertain to all parts or to a single issue or part."

// BR

**Comment by acdc70** [comment]
Thanks for your explanation.
