### ISSUE TITLE
Permissions for Library Staff

### ISSUE THREAD

**Issue by timowen2** [Librarika/Issues#511]
If you are the Library Administrator you can edit circulations - see screen shot below - to do things like change the return date which we need to do very often. Library staff or assistants do not have this access. Could this access be given to Library Staff? We do not want to give Library Administrator permissions to anyone, but we would like Library staff to be able to change return dates.

Please consider this - thank you.
![image](https://user-images.githubusercontent.com/39652671/43036396-f46caf02-8cf8-11e8-90a1-68d8596a3dd7.png)

Tim Owen timat@hotmail.co.uk

**Comment by rayhan** [comment]
You are correct, we will update the permission for "Library Staff" role. But we do not believe Library Assistant role should have edit permission on circulations.

**Comment by timowen2** [comment]
Thank you, I agree that the library assistant role should not have this access

Tim

Sent from my iPad

On 23 Jul 2018, at 17:33, Md. Rayhan Chowdhury <notifications@github.com<mailto:notifications@github.com>> wrote:


You are correct, we will update the permission for "Library Staff" role. But we do not believe Library Assistant role should have edit permission on circulations.

**Comment by timowen2** [comment]
thank you for that, this now works on the circulation screen. Would it be possible to add the edit option to the issues on the screen below at some point? This would help us to manage changing return dates better


Thanks


Tim


[cid:8db1d19c-0be2-486c-aebb-dfedf748d5ac]



________________________________
