### ISSUE TITLE
Entire collection disappeared 

### ISSUE THREAD

**Issue by psulibrarian** [Librarika/Issues#512]
Hello, 

I was having trouble uploading a bulk import with a CSV file, and reached out to the Librarika support staff for direction. They helped me with some formatting issues and I was able to (almost) successfully import our remaining 300 items. I noticed that because of a mislabel, the call number and author information was not transferred to these new records. One of the support staff offered to clean these records up for me. When I checked our catalog the following day, it was entirely empty. Approximately a thousand items have disappeared. Perhaps it's a setting that can be adjusted on Librarika's end, but it is imperative that our students have access to the library materials. Please help!

**Comment by rasel2001** [comment]
We are looking into this issue and will update you shortly.
