### ISSUE TITLE
New User doesn't get Invite email

### ISSUE THREAD

**Issue by benmully** [Librarika/Issues#519]
Added a new user under "Manage > Users" with ID 58969 and email librarian@sherbornehouse.co.uk (it is a valid working email) and received no email to set password. Clicked the re-send invite link numerous times and still nothing. Also used the forgot password link on the login screen and still nothing. How do I get this user activated and password set, as obviously its our main librarian email/user?

![image](https://user-images.githubusercontent.com/38460037/44740622-d5c40100-aaf2-11e8-9f65-05a983bb4ec2.png)

**Comment by benmully** [comment]
I created another user called the.librarian and that worked fine. I also created one to my personal email, the first email arrived fine. I clicked the resend invite button several times and nothing came through. So I think there is a bug with the resend link button to activate the user.

**Comment by rayhan** [comment]
The resend link works fine. Some email servers, specially corporate servers, reject emails due to various reasons (mostly by spam filters). Please white list our domain name in your corporate email server, hopefully you will receive the email.

**Comment by rayhan** [comment]
Also this is the response our email system received when tried to send the email:

> 5.7.1 Sorry you are trying to email a student at Sherborne House School and 5.7.1 this is not permitted. Please contact the school office with any 5.7.1 enquiries. - gcdp a7-v6si967130oih.311 - gsmtp
