### ISSUE TITLE
Unresponsive website

### ISSUE THREAD

**Issue by GerriF** [Librarika/Issues#521]
I have been having issues regarding access to our account on Librarika as well as the home website itself. Is there someone else with the same issue? My connection is fine, but times out because there is no response. This has happened to my clients as well.

Is there something I'm doing wrong or is there something wrong with the website?

**Comment by rayhan** [comment]
We are not seeing any downtime or issues with others. Also, the system status is fine. Will you please share some screenshots so that we can see what is wrong with your library?

**Comment by GerriF** [comment]
Yes, I will. It is currently up again today. The message for both the
account and the website in general said the site could not be reached. I
will psot a screenshot if it happens again. Thank you for responding today.
It is greatly appreciated!

**Comment by aries11espino** [comment]
I am experiencing the same problem. The system is quite slow. I also checked my connection and it was working just fine.

**Comment by aries11espino** [comment]
![image](https://user-images.githubusercontent.com/42954800/45010392-fbcb3300-b015-11e8-98c2-3389b76d8f32.png)

**Comment by rasel2001** [comment]
We are monitoring the performance, are you still facing this issue.

**Comment by GerriF** [comment]
I am still having the issue, but I now believe it is the firewall in the
district where I am teaching. I can access the database from home, but not
from school. Thanks for asking. I wish I didn't have to take work home, but
there's nothing really that can be done. If anyone else has that problem, I
would ask them to check their administrator's firewall parameters.
GF
