### ISSUE TITLE
Minor issue on circulations screen

### ISSUE THREAD

**Issue by timowen2** [Librarika/Issues#527]
On the circulations screen - see below
![download](https://user-images.githubusercontent.com/39652671/46246471-0cdd4900-c3f6-11e8-8b1b-440f6da0fb72.png)

after selecting a member with the mouse the cursor stays on the member field.
![download 1](https://user-images.githubusercontent.com/39652671/46246475-31392580-c3f6-11e8-8540-4e6667a13f0f.png)

 I think it should automatically go to the accession number screen. This would be much easier to use as the keyboard or mouse would not be needed. (Also consistent with how other parts of Librarika work.  Not very important but if any maintenance is being done on the circulations screen perhaps this could be included?

**Comment by jlovestmichaels** [comment]
Not sure this would benefit our library

**Comment by timowen2** [comment]
OK, it might not be a benefit to you, but would it cause a problem? After you have selected a member the cursor focus being on the member field is pointless, the logical place to put it is on the accession field.

**Comment by jlovestmichaels** [comment]
Hi 
should have replied sooner. can't think of any immediate problems off the top of my head. Hope the enhancement makes things work better for you.

**Comment by timowen2** [comment]
Thank you, a good bit of work

Tim

Sent from my Huawei phone


-------- Original Message --------
Subject: Re: [Librarika/Issues] Minor issue on circulations screen (#527)
From: rasel2001
To: Librarika/Issues
CC: timowen2 ,Author


Closed #527<https://github.com/Librarika/Issues/issues/527>.
