### ISSUE TITLE
difficulty with data import. The imported data does not update automatically.

### ISSUE THREAD

**Issue by RYILibrary** [Librarika/Issues#530]
Hi, we have a non-profit library within a monastic setting in Nepal, with somewhere arourd 4000 titles. Therefore, I am thinking about upgrading my basic membership to pro. But I am having problem with bulk data import. Moreover, the small chunk that I managed to import does not get updated with book cover image and other details like descriptions and so forth.

**Comment by rasel2001** [comment]
You will be not able to upload 4000 titles unless upgrade to Pro. Only 2000 titles are allowed for free version.

Please note, you can't update your existing records using import method. Please use our bulk actions to update your existing records.

**Comment by RYILibrary** [comment]
Hi Rasel,

Thanks for your prompt response. We have upgrade to pro version but the
database is still not possible to transfer with the "*Description*" column.
Moreover, there is no provision within the software to update the database
based on the ISBN or book title through online databases like amazon,
goodreads, worldcat etc. (which is available in free android apps like Book
Catalogue).

Furthermore, I have listed few suggestion which I forwarded to  Raynux
team, from which I received the payment receipt.

I am forwarding here my suggestions/requests (that I sent to the team) to
you as well:
1) The bulk import of the older database is a bit problematic. It will be
way more convenient, if the transfer of .csv or excel files could be
tweaked a bit for easier data transfer and integration. Also the database
that is integrated does not update automatically. For example, the book
cover is not retrieved from the internet database, which we realized is
possible with free android softwares like "Book Catalogue" etc.

2) If the *Accession no.* could be visible in the *Catalog Item page*, it
will be very easy to conduct an inventory for the maintenance and record
keeping of any  library system.

3) Some of the books that have same title but different ISBN numbers are
not recognized by the system. If you could integrate multiple ISBN slots
for a book, that would be wonderful. Also for book without ISBN but
ASIN/LOC No., a slot for that would be very much appreciated.

4) In the *Manual add* tab, the author section can be integrated inside the
main tab so that one does not have to save the book, then edit it after in
the book info page. Also there should be provision for a customize author's
slot, so that we can add the name of translators, editors and so forth...of
the books.

5) It would be also very much time saving, if we could search the filter
(search) box  in the *Circulations tab* not only by ASN or ISBN but by
title, member's name etc.

6) For the "*Fees & Payments*" section, tab to choose other currencies (eg:
*Rupees*) would be a very much welcomed option.

7) A library should be able to save offline database for backup. Also an
offline efficient "*bulk bar-code generator add-in*" would be wonderful.

9) Every tab, such as *Catalog Item page, Circulations tab or Members
tab *should
be have an option either to scroll or show more than 20 records(eg: 50,
100, 200) at a time.

8) Lastly, for the paid users, if the Mobile version of the software could
be updated with the option to edit the database, then that would be an
amazing perk for the library like ours.

A heartfelt thanks once again for your wonderful work,
and best wishes,
RYI Library
Kathmandu,
Nepal
