### ISSUE TITLE
Keyword Search or Default Search at OPAC Issue

### ISSUE THREAD

**Issue by aries11espino** [Librarika/Issues#534]
The Keyword Search or Default Search doesn't seem to work. I tried to search using the term "Shakespeare", "William Shakespeare", and "Shakespeare, William" however it doesn't show any books I have encoded unless I change the "Default" field to "Author".

The Keyword or Default Search should search for the term at the "Title", "Author", "Description" and "Subject".

Hope you can help me with this.

Thank you.

**Comment by aries11espino** [comment]
I am now sure that it is not working. Even just searching for simple terms such as "Science", "Math", "Management" do not show any results.

**Comment by Turrill** [comment]
Same problem here and it was working last week.

**Comment by aries11espino** [comment]
It seems the problem has been addressed now. I can now search using the default field. Hope your system is also working now.

Are you using the free plan or you are subscribed to Librarika? We are planning to subscribe to it because we have around 10,000 to 14,000 volume of books.
