### ISSUE TITLE
Default search not working

### ISSUE THREAD

**Issue by englishcaddy** [Librarika/Issues#538]
I've noticed that in the past 2 days the "default search" in the catalog items menu is not working.  Entering title, tags, known accession numbers and key words turn up zero results.

**Comment by rasel2001** [comment]
default search is working fine in our end as well as title, tags, accession numbers & so on. please let us know if you still have this problem.

**Comment by adivele** [comment]
Hello! I have the same problem for the last days. If  I`m searching in the catalog items menu using ”default searching” the result is zero. If I`m searching using a different criteria like ”title” or ”author” the search is working. Today I have added a new book and surprise, for this one the searching by default is working.
![searching prob 1](https://user-images.githubusercontent.com/55286670/67942584-d2d60c00-fbe0-11e9-9e2b-e1cee96b51b8.jpg)
![searching prob 2](https://user-images.githubusercontent.com/55286670/67942585-d36ea280-fbe0-11e9-9f58-2a735d8060a6.jpg)
![searching prob 3](https://user-images.githubusercontent.com/55286670/67942586-d36ea280-fbe0-11e9-8bcd-96f0f2a8e4c5.jpg)
