### ISSUE TITLE
Error: An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by PatriciaBL** [Librarika/Issues#540]
I have been able to upload some of my books to Librarika, but now I keep getting this message Error: An Internal Error Has Occurred.  Is there anything I can do?

Patti

**Comment by rasel2001** [comment]
Can you please share some more details? 

Also please make sure your CSV files are encoded properly. May be some characters were not encoded properly in your CSV file.

Please share us the CSV file.

**Comment by PatriciaBL** [comment]
Hello,

I have attached the file.  I have attempted to import this file several times.  It appears to be just like the other files I was able to import, but each time I get the same message: Error: An Internal Error Has Occurred.

Hope to hear from you soon.

Thanks,
Patti

[cid5c2a427a-16a0-444f-89ef-39f191714cc1]
www.whatifconference.org<http://www.whatifconference.org>

Patti Larson

Impact Foundry

In the office:  T-Th

p:

916-569-8555

a:

2031 K Street, 2nd Floor, Sacramento, CA 95811

w:

www.impactfoundry.org<http://www.impactfoundry.org/>  e: plarson@impactfoundry.org<mailto:plarson@impactfoundry.org>

[facebook_sig.png]<https://www.facebook.com/impactfoundry/>  [twitter_sig.png] <https://twitter.com/ImpactFoundry>   [linkedin_sig.png] <https://www.linkedin.com/company/impactfoundry/>

**Comment by rasel2001** [comment]
We didn't get your attached file. Can you please use our contact us form to send that file.
Thanks

**Comment by PatriciaBL** [comment]
> I have been able to upload some of my books to Librarika, but now I keep getting this message Error: An Internal Error Has Occurred. Is there anything I can do?
> 
> Patti

Here is the zip file
[501-550.csv.zip](https://github.com/Librarika/Issues/files/2562899/501-550.csv.zip)

**Comment by rasel2001** [comment]
Hello Patti,

We have found only issue with your file 501-550.csv, Author name is more than 100 characters for serial number 830. Please sure each author's or co-author's name should not be more than 100 characters. 

After limiting the author name into 100 characters, we found it's works fine.

**Comment by PatriciaBL** [comment]
Thanks!

[cid5c2a427a-16a0-444f-89ef-39f191714cc1]
www.whatifconference.org<http://www.whatifconference.org>

Patti Larson

Impact Foundry

In the office:  T-Th

p:

916-569-8555

a:

2031 K Street, 2nd Floor, Sacramento, CA 95811

w:

www.impactfoundry.org<http://www.impactfoundry.org/>  e: plarson@impactfoundry.org<mailto:plarson@impactfoundry.org>

[facebook_sig.png]<https://www.facebook.com/impactfoundry/>  [twitter_sig.png] <https://twitter.com/ImpactFoundry>   [linkedin_sig.png] <https://www.linkedin.com/company/impactfoundry/>
