### ISSUE TITLE
How to Delete User Accounts for Librarians

### ISSUE THREAD

**Issue by aries11espino** [Librarika/Issues#541]
I have just noticed that there is no option for deleting User Account for Librarians. The once you are giving access to the dashboard? There are two User Accounts that the email addresses that were misspelled. I could not fine an option to delete those. Thank you.

**Comment by rasel2001** [comment]
Hi,

Yes, user account deletion access is not available for Librarians. We believe this is very sensitive data. Please use our contact us option and send us the users accounts you want to delete, we will do it manually.
