### ISSUE TITLE
After Auto Saving Smart Add, Takes me to a page of code

### ISSUE THREAD

**Issue by CapitolHillAcademy** [Librarika/Issues#542]
When I use smart add to enter the ISBN, when I click the AutoSave button, it takes me to a page of code instead of the button to view/edit.

![screen shot 2018-11-08 at 11 26 04 am](https://user-images.githubusercontent.com/44877685/48219486-df1ae680-e349-11e8-9ce1-1c052122488e.png)

**Comment by rasel2001** [comment]
Are you still having this issue?

We have tried many to but can't generate this issue, it's always working for us.

**Comment by CapitolHillAcademy** [comment]
The issue is still happening but I found that it only has this problem in
Chrome. When I use Safari it is fine.
