### ISSUE TITLE
Import tags

### ISSUE THREAD

**Issue by benhoodie** [Librarika/Issues#543]
Ls,

I tried to import my Library csv and it works very smooth!

Except for the tags, those are not imported. If I import a line with 1 tag the line gets imported but the tags are not showing up afterwards. 

Furthermore i am curious how to import multiple Tags seperated by Comma in a csv file... ;)

Hope to here from you soon!

Kind regards,

Ben

**Comment by benhoodie** [comment]
Any update? 
This is a showstopper for us to use the Librarika platform :/
Hope to hear from anyone soon!

**Comment by rasel2001** [comment]
We have already implemented this. You can add multiple tags using comma separate during import.
