### ISSUE TITLE
Login Issues for member

### ISSUE THREAD

**Issue by FranzLoh** [Librarika/Issues#546]
Hi,

I have recently started a library system for my office books. As i invite my colleagues as members, most are able to join and have access to the catalogue. However, one of my colleague with the email address andrinatan@smfsc.org.sg is unable to login. It states that she is already a user. However, upon resetting her password, the login screen prompted that she is an invalid user. Please refer to the attached for the screenshot on the error.
![error](https://user-images.githubusercontent.com/45228261/48831339-98010c80-edb1-11e8-9dc3-c93238770131.PNG)

**Comment by rasel2001** [comment]
Hi, we found this member has not confirmed her membership yet. She suppose to get a confirmation email. Please make sure she has got that email & confirmed.

**Comment by FranzLoh** [comment]
![error](https://user-images.githubusercontent.com/45228261/49057744-edb73800-f23b-11e8-94da-536834b3443d.PNG)
Hi, this is the error that prompted during the confirmation of the membership through the email link sent out. Even the option of resetting the password does not allow the access to this account.

**Comment by rasel2001** [comment]
This member already has an user account. Please choose second option from section **New to Librarika?** . Then login with username ( andrinatan@smfsc.org.sg ) and your password.

**Comment by FranzLoh** [comment]
She does not remember having an account. I have tried to choose the second option as well, by resetting the password, before trying to login with the new password. The error prompted would be the screenshot that I have initially posted.

**Comment by rasel2001** [comment]
We think you have invited her for both library user & member. She needs to confirm her user account first, then member confirmation.

**Comment by FranzLoh** [comment]
Thank you for the kind assistance. The issue is resolved.
