### ISSUE TITLE
Library is empty (white screen)

### ISSUE THREAD

**Issue by FalconsP** [Librarika/Issues#549]
Hello.
Whenever I open the app and tap on 'Select Library' all I can see is a blank screen.
I am successfully logged into the App.
I can't see the version number of the App but it is the latest version downloaded from the App store. I have tried this on iOS versions: 10.1.1 and 12.1
I have tried on several wifi networks too, all with the same outcome.

Any advice would be great!

**Comment by rasel2001** [comment]
Mobile App is only available for librarians.
