### ISSUE TITLE
Catalog Items Disappeared

### ISSUE THREAD

**Issue by bellemeadschool** [Librarika/Issues#555]
We had almost 500 books entered into our library, and now only 35 are listed. In fact, every time we log in, that number changes. How do we recover the items that have disappeared?

**Comment by gravetro000** [comment]
Same Issue

**Comment by rasel2001** [comment]
> We had almost 500 books entered into our library, and now only 35 are listed. In fact, every time we log in, that number changes. How do we recover the items that have disappeared?

@bellemeadschool we have seen that your library administrator has deleted books using bulk action. Please check bulk actions at https://bellemeadelibrary.librarika.com/bulk_actions

@gravetro000 You can also check bulk actions from Dashboard -> Others -> Bulk Actions.
