### ISSUE TITLE
Change button colours

### ISSUE THREAD

**Issue by phubers** [Librarika/Issues#557]
When viewing a book in the catalogue, buttons are shown for requesting a book and checking out a book. The order and colours of these buttons are not intuitive. The checkout button should come first and be green, because that will be the default action for most users. Making it red suggests that a book is not available when in fact it is. Having the request button as the second button makes more clear that that is the alternative option. Again, red is not a great colour for that button either, so a darker green might be more useful.

**Comment by rasel2001** [comment]
Thanks for your suggestion. We will check the color & order in our next release.
