### ISSUE TITLE
Mexican Spanish mistranslation

### ISSUE THREAD

**Issue by alorenasol** [Librarika/Issues#559]
Both the Check-in and Check-out buttons at the Mexican Spanish settings say "Check-out" which makes it confusing.

![image](https://user-images.githubusercontent.com/47605840/52728176-68ab0780-2f7c-11e9-9678-def87ace12f6.png)

**Comment by rasel2001** [comment]
We are working on new UI for library dashboard. All translation issue will be fixed then.
