### ISSUE TITLE
Receipt printing 

### ISSUE THREAD

**Issue by SAIprasannaK** [Librarika/Issues#571]
While printing the receipt using a 58 mm receipt printer the font is too small and it is not clearly visible .I have tried everything but nothing works. I would suggest to adapt the receipt accordingly to suit the print paper 
![IMG_20190512_202845](https://user-images.githubusercontent.com/15402765/57584084-0f0f9600-74f5-11e9-89a3-0eaee03664a3.jpg)
![IMG_20190512_202848](https://user-images.githubusercontent.com/15402765/57584086-0f0f9600-74f5-11e9-9480-4b1214013d71.jpg)

We had tried using word and Excel to create some custom receipts and it came out well . We used font size 9.
For is the length of the receipt paper does not matter.

**Comment by SAIprasannaK** [comment]
The printing is fine but I would suggest to increase the font size as it's is very difficult to read

**Comment by rasel2001** [comment]
Thanks for your suggestion. We will think about it.
