### ISSUE TITLE
Deleting my barcode queue.

### ISSUE THREAD

**Issue by chardevans** [Librarika/Issues#581]
I tried generating barcodes for my 2500 book library all in one go, I was unaware that I could only do 500 at a time and now I have a queue of 2500 books stuck in my barcode label queue. I cannot delete them in bulk it can only be done individually, is there not a way for me to clear it so I can 
 queue and then print off 500 at a time?
 If I click generate barcodes I get the "This operation will exceed generate queue, please print them first" message, which makes little sense to me.  
 Thanks
![Screenshot (8)](https://user-images.githubusercontent.com/51317492/58789329-d745cb00-8628-11e9-9aa4-94bc591fd8be.png)

**Comment by Garthkh** [comment]
I have the same problem. There should be a way of canceling the queue too if you don't want to print the codes.

**Comment by rasel2001** [comment]
This issue will be resolved in our next release.
