### ISSUE TITLE
Category Dropdown selection

### ISSUE THREAD

**Issue by englishcaddy** [Librarika/Issues#582]
I noticed the dropdown menu for the predefined Categories, is missing when adding new items.  Will this no longer be an option?

**Comment by CapitolHillAcademy** [comment]
I noticed this as well

**Comment by rasel2001** [comment]
It's still the but we have made a little update here. We are using auto-complete select to make it better. Just type a character and all category with that character will be listed below and you can pick your desired one from the list.
