### ISSUE TITLE
Closing Brackets Shown Incorrectly in Author Names

### ISSUE THREAD

**Issue by IraGraves** [Librarika/Issues#588]
In the Book Details, Author Names are shown as "Surname (First Name(" instead of "Surname (First Name)". So there is an opening bracket where there should be a closing bracket.

I use the German version. Example page:
https://planit.librarika.com/search/detail/3403610

**Comment by rasel2001** [comment]
This issue is occurred due to German language translation. We will resolved this in our next release.
