### ISSUE TITLE
Checking out more than one book per borrower

### ISSUE THREAD

**Issue by Garthkh** [Librarika/Issues#589]
Checking out more than one book per borrower - I have my barcode reader set to add a TAB as a terminator which works great between reading the borrowers barcode and the 1st book's barcode. The cursor moves from the one field to the other. But, now I have to pick up my mouse and click on the Submit button to be able to scan the 2nd book, and so on for each book. Can this be simplified so that each book can be scanned and then a final ENTER or click on the submit button to move to a 2nd borrower and his/her books?

**Comment by rasel2001** [comment]
Sorry! this is not possible now.
