### ISSUE TITLE
Searching by default in Catalog Items is not working

### ISSUE THREAD

**Issue by adivele** [Librarika/Issues#595]
Hello! I have this problem for 3 days. If I`m searching in the catalog items  using ”default” searching the result is zero. 
![searching prob 1](https://user-images.githubusercontent.com/55286670/67943061-f188d280-fbe1-11e9-9a00-87117063c1d3.jpg)

If I`m searching using a different criteria like ”title” or ”author” the search is working. 
![searching prob 2](https://user-images.githubusercontent.com/55286670/67943086-fc436780-fbe1-11e9-895d-d9de5258c26f.jpg)

Today I have added a new book and surprise, for this one the searching by default is working.
![searching prob 3](https://user-images.githubusercontent.com/55286670/67943106-049ba280-fbe2-11e9-98ef-37914ef84280.jpg)

**Comment by Taguardz** [comment]
I have the same problem also! Is a bug in the system? I used to see all the available resources but now I only see the available resources if I click the Title

**Comment by rasel2001** [comment]
When you use the Default option it takes about a couple hours for new entries. So, please wait for couple of hours or use specific search option for new entries. Please let us know if the issue is occurred for old entries as well.

**Comment by adivele** [comment]
I don't know what happened, but I haven't anymore the problem. The bug has been fixed
