### ISSUE TITLE
Database A-Z on-screen keyboard available in other languages

### ISSUE THREAD

**Issue by dibar77** [Librarika/Issues#601]
Hello,

would it be possible to have the on-screen keyboard in the "Database A-Z" section available in other character sets as well?
This means that in addition to the existing Latin keyboard, a check box (somewhere in "Preferences" maybe) would allow the library admin to enable/disable additional keyboards for the library.
I am particularly interested in the greek keyboard.

Thanks in advance,
Dimitris

**Comment by rasel2001** [comment]
This is not possible right now.
