### ISSUE TITLE
importing csv file of library items failing

### ISSUE THREAD

**Issue by mcjourney** [Librarika/Issues#602]
Hi,

I'm trying to import a csv file and consistently get the message that the Title is missing for all the records. Should I have no data in the SI field?
[TIC Video for Librarika.csv.zip](https://github.com/Librarika/Issues/files/3913602/TIC.Video.for.Librarika.csv.zip)

**Comment by rasel2001** [comment]
Do you still have this issue?

**Comment by mcjourney** [comment]
No. Our library was so small that we manually added the records.

************************
Lauranne Bailey
via iPhone mail
************************

On Dec 27, 2019, at 10:34 PM, rasel2001 <notifications@github.com> wrote:

﻿

Do you still have this issue?
