### ISSUE TITLE
I cannot click and save Preferences.

### ISSUE THREAD

**Issue by Ninein-Dog** [Librarika/Issues#607]
Whenever I click the button to save "Preferences", it **does nothing**. Next time, when I open it, my updates aren't saved. This does not affect other settings.

- @Ninein-Dog

**Comment by rasel2001** [comment]
The issue is occurred due to the Notified Librarians option in the Notifications / Reminders tab. The Notified Librarians field is required. Please fill up the Notified Librarians field then the preferences will be saved.

**Comment by Ninein-Dog** [comment]
Oh, it worked, thanks!
