### ISSUE TITLE
Paid for upgrade to basic pro, cant change preferrences

### ISSUE THREAD

**Issue by tomseeber** [Librarika/Issues#608]
I upgraded my library to the first paid tier.   It is not letting me actually change the preferences marked for the paid libraries. 

The Library is toronto-occult.librarika.com
Please advise.

**Comment by rasel2001** [comment]
**Save preferences is not working**

The issue is occurred due to the Notified Librarians option in the Notifications / Reminders tab. The Notified Librarians field is required. Please fill up the Notified Librarians field then the preferences will be saved.

**Comment by rasel2001** [comment]
We have resolved this issue. Please check now.
