### ISSUE TITLE
Save Preferences - Doesn't work

### ISSUE THREAD

**Issue by Adi-A** [Librarika/Issues#609]
Not able to save any type of preference changes, even the ones not marked as paid. Clicking on the Save Preferences button doesn't result in any action. 

Problem URL -- https://ultrahuman.librarika.com/libraries/preferences

**Comment by timowen2** [comment]
This is correct, somehow this has stopped working and needs to be fixed as a matter of urgency

**Comment by rasel2001** [comment]
The issue is occurred due to the Notified Librarians option in the Notifications / Reminders tab. The Notified Librarians field is required. Please fill up the Notified Librarians field then the preferences will be saved.

**Comment by rasel2001** [comment]
We have resolved this issue. Please check now.
