### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by Elena-UkrLib** [Librarika/Issues#612]
Hello,
In my library, I have books both in English and Ukrainian languages. When I export the catalogue items into CSV file  -  Ukrainian language turns into this:

"Ð¡Ð»Ð¾Ð²Ð¾ Ð·Ð°   Ñ‚Ð¾Ð±Ð¾ÑŽ, Ð¡Ñ‚Ð°Ð»Ñ–Ð½Ðµ!". ÐŸÐ¾Ð»Ñ–Ñ‚Ð¸Ñ‡Ð½Ð° ÐºÐ¾Ð½Ñ†ÐµÐ¿Ñ†Ñ–Ñ Ð²   Ð¾Ð±Ñ€Ð°Ð·Ð°Ñ…
(please see the attached screenshot)

Could you please fix this problem?

![screenshot](https://user-images.githubusercontent.com/60111849/72750473-e4371f00-3bf7-11ea-8182-104991ba50f6.PNG)

**Comment by jinia3636** [comment]
Ukrainian characters should work without any issue. Please make sure that you have correct Ukrainian fonts on your device. Also, you can try on google docs.
