### ISSUE TITLE
"Church Library" option when creating new library

### ISSUE THREAD

**Issue by mitc0185** [Librarika/Issues#613]
When creating a new library, under "Library Type" there is no option referring to a church library or anything to that effect. It could be "faith based institution program activities" or something like that if you prefer a broader term. 

I would like to propose using your software to my church's library committee; Some might be put off that this option is not present or that we have to choose "Other."

**Comment by jinia3636** [comment]
Sorry, currently we do not have any plan to add more option on **Library Type**

Please use the **Other** type option for now.
