### ISSUE TITLE
User Account Permission bugs ???

### ISSUE THREAD

**Issue by T-TeeJay-J** [Librarika/Issues#616]
Hi, i recently started using this application to manage my school library. The overall experience was fine until recently. When i try to add a new with a permission as library staff which only allow to check in and check out books. It works fine on the web version, but when i log in on the mobile device, the account still be able to do stuff like add book and add member which "staff" was not allow to.

**Comment by jinia3636** [comment]
Our mobile apps are only available for library administrators.
