### ISSUE TITLE
Import of CSV fails on Media Type

### ISSUE THREAD

**Issue by RayLibrary1971** [Librarika/Issues#619]
My import of a Librarika .csv file fails.  The error message is  "Type: Please provide a valid media type.".  The csv file clearly contains the field "Type" all occupied by the label "Book".

**Comment by jinia3636** [comment]
The media type should be label as **Books**, not Book.

For more details please check our manual at https://docs.librarika.com/en/latest/cataloging/#bulk-import

**Comment by RayLibrary1971** [comment]
Fabulous, thank you!  All fixed!
