### ISSUE TITLE
[Feature Request] Languages for books

### ISSUE THREAD

**Issue by basklein** [Librarika/Issues#620]
I'm the administrator for an international school and we deal with books in multiple languages. Some books only available in one, others available in multiple languages.
As such it would be very useful to be able to browse through the catalog with language as a parameter. Of course that would also require us to be able to indicate the language of a book. I think the language of a book is already provided by the ISBN API, but I'm not sure. I wouldn't mind having to input the language manually.

A temporary solution for us would be to create library branches for the different languages. However, in the near future we are splitting our campus and will have different physical branches as well, which would make this rather inconvenient.

**Comment by jinia3636** [comment]
Currently, it's not possible to implement this feature. But we will think about it in the future.
