### ISSUE TITLE
Grammar and Punctuation Issues

### ISSUE THREAD

**Issue by RedwoodsLIB** [Librarika/Issues#621]
Proofreading alerts:
DASHBOARD:
Checkouts:  "There is no items checked out recently" should be "There are no items checked out recently."
Overdues:  "Lets keep this clean" should be "Let's keep this clean"

It would also be really helpful to be able to customize outgoing messages for overdue books, etc., for patrons, rather than relying on the stock wording, which can be a bit stilted.

Also, it's frustrating that punctuation can totally screw up the "Tags" function.  If I copy and paste the Library of Congress subject tags, I have to go back and manually change periods to commas, as the system intermittently omits any tags that follow a period.

**Comment by jinia3636** [comment]
Thank you for letting us know, we will fix the grammatical issue.

Sorry, the reminder emails are not customizable.

We use these separators , ; -- // » > for tag. Please make sure you are using any of them while importing multiple tags for your catalog.
