### ISSUE TITLE
Can't connect via Facebook

### ISSUE THREAD

**Issue by adivele** [Librarika/Issues#623]
I can't connect via Facebook. First I can't select facebook login box, and second, if I press connect botton I receive an error message.
![Captură ecran (1)](https://user-images.githubusercontent.com/55286670/80082324-e2fdf100-855c-11ea-8b12-dd633c62b090.png)
![image](https://user-images.githubusercontent.com/55286670/80082379-f5782a80-855c-11ea-93cd-aad8667e3071.png)

**Comment by jinia3636** [comment]
Hello,
Sorry, the Facebook login option is not working because of some issues. We will try to fix the issue soon.
