### ISSUE TITLE
ISBN number bug

### ISSUE THREAD

**Issue by keesholdings** [Librarika/Issues#627]
Item “Knowing Dogs 101” does NOT have an ISBN in my catalog, however, when I try to add the item “Learning to Lead Like Jesus” (isbn 9780736972444), it tells me the isbn is already in use by the previous item.

**Comment by jinia3636** [comment]
We have added the item 'Learning to Lead Like Jesus' to your library catalog ( accession number 48 ) please check and update necessary information. Also, you can delete that item and add it again if you want.
