### ISSUE TITLE
Quick checkin bug when checking in a book that wasn't checked out

### ISSUE THREAD

**Issue by theoneandonlyrick** [Librarika/Issues#628]
When I use quick return, if the book isn't checked out, it shows the alert 'Error in performing action. Please, try again.'.
But after that, if I put in a valid book that is checked out, the error remains and the book is not checked in.
If I close the modal and try again with the valid book then it is ok.

**Comment by jinia3636** [comment]
Are you sure that you are entering accession number in the Accession No field?

Also, are you using the web version or the app?

**Comment by theoneandonlyrick** [comment]
Yes definitely in the correct field. It was using the web version.

**Comment by jinia3636** [comment]
We have checked it from our end and its working fine.

**Comment by theoneandonlyrick** [comment]
Ok I'll do it again and record the screen.
