### ISSUE TITLE
No invitation email to the users with hotmail address

### ISSUE THREAD

**Issue by atsuch** [Librarika/Issues#629]
Hello,

First of all, I'd like to thank the developers for the great app. It's simple and easy to use. 

However, I encountered a strange problem when testing. Whenever I try to add a member with hotmail address (@hotmail.com) it does not seem to send the invitation email. I have tried it with my own hotmail address (I use gmail as an administrator of the test library I created), as well as with another person with hotmail. I tried "Resend invitation" multiple times, and checked the spam folder. With different email providers it seems to work as expected. 

Is there anyway I can check where things are going wrong??

**Comment by jinia3636** [comment]
Please send us the email addresses. We will investigate and let you know.

**Comment by atsuch** [comment]
Upon more testing, we did find the invitation in the spam folder. Sorry about that!
