### ISSUE TITLE
User unable to log-in

### ISSUE THREAD

**Issue by kevinbsoriano** [Librarika/Issues#630]
We have a user that is unable to log-in.
I already cancelled, and re-setup her user account several times, but to no avail.
Had her reset her Librarika password as well, but she still can't get in. Help!

**Comment by jinia3636** [comment]
Please send her email address to us using the contact form at https://librarika.com/spages/contact

**Comment by kevinbsoriano** [comment]
thank you so much! yes, sent the email with her address just now :)
