### ISSUE TITLE
Accession number problem

### ISSUE THREAD

**Issue by adivele** [Librarika/Issues#631]
The problem is that I imported the books, and maybe that the problem why the accession number for 1400 books is 1 and 2. Just for 1100 books from my 2600 books the accesion number is a unique value. 

My question is if is there any chance to modify the accesion numbers in some automatically way?
Or the only way to modify and to assingn a unique value is one by one?

Thank you in advance for answer.

**Comment by jinia3636** [comment]
Sorry, there is no such option to update the accession numbers automatically. You have to edit them manually.
