### ISSUE TITLE
509 Gateway Time-out Error when none should be raised

### ISSUE THREAD

**Issue by shkung** [Librarika/Issues#633]
When I tried to bulk-import library items from CSV files of greater volume, the Error 509 page was often prompted. I later returned to the catalog reports to inspect the latest imports to the library, and all the items seemed to have been imported correctly. 

The error prompt proved to be causing quite a confusion to the user, who would be led to think that the import was unsuccessful. Perheps longer-than-normal processing times for bulk-imports should be taken into account to prevent this error from being raised.

**Comment by jinia3636** [comment]
Hi,

Next time please split your files into multiple CSV files. We recommend max 500 records in each file for the best performance.
