### ISSUE TITLE
Too much information required for bulk import

### ISSUE THREAD

**Issue by dwnorman** [Librarika/Issues#634]
Hello,
Thank you for your hard work and generosity.
I am trying to setup a lending library for church members to church members.  A spreadsheet was created with limited information.  I am trying to work with what I've got, but the list of information required for a .csv file is well beyond what has been collected.  Is there a way to pair down the required fields?

**Comment by jinia3636** [comment]
Sorry, there is no such option. You have to upload your records according to our CSV file format.
