### ISSUE TITLE
Books not found with ISBN

### ISSUE THREAD

**Issue by IrinaKirs** [Librarika/Issues#635]
Hello, I'm adding book into my library and have found out that many books could not be added by using the smart-add option and I have to add items manually. An example for this would be ISBN 978-3-940785-73-2, 978-3-00-024385-1. Why is that so? Thank you!

**Comment by jinia3636** [comment]
The smart add method gets book information from various sources but we can not guarantee that each ISBN can pull information from the internet correctly. Also, Our API tries to find that book if it is available on the internet.

If you can not add any items using our Smart Add method then, please add them by our Manual Add or Bulk Import method.
