### ISSUE TITLE
Android App Won't Do Checkout

### ISSUE THREAD

**Issue by maddieyiwu** [Librarika/Issues#641]
Whenever I try to check out a book using the Android app, it won't let me. It just says, "Please make sure you have entered all the information correctly." I have! The same information works with no problem on a laptop.

**Comment by jinia3636** [comment]
You can reinstall the App and try again. Still, if it doesn't work then please use our web version for now.

**Comment by maddieyiwu** [comment]
I already tried that! What's a better long-term solution?
