### ISSUE TITLE
Creating new categories in Librarika

### ISSUE THREAD

**Issue by IrinaKirs** [Librarika/Issues#644]
It would be great to have an option to add new categories into Librarika in addition to those which already exist. For example, it would be very useful for us to manage our laptops/tablets circulation in Librarika as well. Could you think of adding this option into Librarika? Thank you!

**Comment by jinia3636** [comment]
Yes, we already have this option in our system. You can add a new category or update the existing one. for more details please check our manual at https://docs.librarika.com/en/latest/cataloging/#categories

Also, you can access the circulation using both laptops and tablets.

Please note: both options are only accessible by the library administrators.

**Comment by IrinaKirs** [comment]
Hello,

I think you have misunderstood me because I was not quite accurate in my
request. I'll try once again.

My institution wants to use Librarika not only to circulate books and media
like that but also to lend tablets and laptops to our members and to track
this as well. Could you think of creating a new media type (with specific
fields) for that, because registering tablets under available media types
(fields here are suitable for books only) looks odd.

Thank you!

Kind regards,
Irina Kirsanova


вт, 12 янв. 2021 г., 7:26 jinia3636 <notifications@github.com>:

**Comment by jinia3636** [comment]
Sorry for the late reply.

Media types are fixed. In this case, please, select Media Type = Other when adding other items if your desired type does not match our listed types.
