### ISSUE TITLE
Problem with Llibrarika Branches

### ISSUE THREAD

**Issue by BAMainLib** [Librarika/Issues#645]
When our members selects a branch and try to browse through the listings in it (we have four), Librarika jumps to the first page of another branch when they try to advance the the next page of the branch they selected.  Because of this, it is impossible to scroll through the titles in the branch.  

Is this a bug or are we doing something wrong?

**Comment by jinia3636** [comment]
We will fix this issue in our next release.

**Comment by rasel2001** [comment]
Dear @BAMainLib we have resolved this issue.
