### ISSUE TITLE
beta version and barcode printing

### ISSUE THREAD

**Issue by timowen2** [Librarika/Issues#646]
barcode printing has changed in the beta version. It does not appear to use the same settings as the current production version
![1](https://user-images.githubusercontent.com/39652671/107228691-d9bf1180-6a14-11eb-896b-8256bc4bc634.jpg)
![2](https://user-images.githubusercontent.com/39652671/107228692-da57a800-6a14-11eb-9302-cbd5b6d6a418.jpg)
![3](https://user-images.githubusercontent.com/39652671/107228693-daf03e80-6a14-11eb-8b6f-2935857adafd.jpg)
![4](https://user-images.githubusercontent.com/39652671/107228694-daf03e80-6a14-11eb-97b8-331a47bc77f1.jpg)

**Comment by jinia3636** [comment]
Our barcode label settings are the same as before it's not changed.

**Comment by timowen2** [comment]
Thankyou for looking but I'm afraid you are wrong. i can generate  a barcode and print it in the existing system, if i then use the beta system and generate a barcode it does not print properly (line one wraps and the whole print is shifted to the right)

Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rasel2001** [comment]
@timowen2 Can you please share your browser details and some screenshots? We will look onto this.

**Comment by timowen2** [comment]
Hi, see photos attached, chrome on windows 10. Problem happens after last librarika screen, looks like the chrome print function has a problem with the data it is getting. Sorry for photos, fireshot will not work on these screens

Tim[Image]



Get Outlook for Android<https://aka.ms/ghei36>

[Image]

[Image]

[Image]

________________________________

**Comment by rasel2001** [comment]
Dear @timowen2 
We can't see the photos you have attached. Can you please share them with us again by creating a support ticket at https://librarika.com/spages/contact?

Best regards
Rasel

**Comment by timowen2** [comment]
Hi

I think I have manged to get the photos on to github

Tim

________________________________

**Comment by rasel2001** [comment]
Dear Tim,

We don't see any difference on chrome browser while print the barcode labels. Please see the attached photos that we have taken from your library dashboard.
![Librarika-BarcodeLabels-On-Old-Dashboard](https://user-images.githubusercontent.com/22570306/107231596-b0b97380-6a4a-11eb-8638-77198a8e66ed.png)
![Librarika-BarcodeLabels-On-Beta-Dashboard](https://user-images.githubusercontent.com/22570306/107231805-ee1e0100-6a4a-11eb-93b4-fd24ecdbccee.png)

Also, we have seen that your settings for barcode label printing has been changed. Are you using roll printer? If yes, then please use our default settings for roll printers. You can find the printer settings at **Page Settings** -> **PRESETS** tab.

Please let us know if you need any further assistance.

Kind regards,
Rasel

**Comment by timowen2** [comment]
Please look at the two photos on github of the print file in chrome, everything has shifted

Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timowen2** [comment]
Rasel, thanks, i have tried the presets. I can't make them work, they are all in inches (printer and paper sizes, as well as chrome) operate in millimetres here. They also default to portrait but need to be landscape for a brother printer. I have put everthing back so it works in the current version, if we have to switch to what is now the beta then i will have to change my settings

Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rasel2001** [comment]
Dear @timowen2 
Good day to you. We have update the barcode printing section today for the beta version. Can you please check and let us know if it is okay now?

Regards
Rasel

**Comment by timowen2** [comment]
Thank you, late here now but i will look tomorrow and let you know

Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timowen2** [comment]
OK tried this today - created a list of 3 barcodes using the beta version; amended width and set line 1 to title as usual. Looks OK on screen in Librarika but in the Chrome interface the codes have shifted to the right and there are only 2 barcodes. Going back to the normal interface the same barcodes look OK in Librarika and also in the Chrome interface - and all three are there. So actual creation of the barcodes looks OK but something is going wrong in the transfer to CHrome. Attached photos show the same steps in old and beta interfaces
![13](https://user-images.githubusercontent.com/39652671/107765799-58c08c80-6d2a-11eb-856f-fc81edce42e8.jpg)
![12](https://user-images.githubusercontent.com/39652671/107765802-59592300-6d2a-11eb-8d0a-bb07657edd78.jpg)
![11](https://user-images.githubusercontent.com/39652671/107765803-59f1b980-6d2a-11eb-8591-e3d9649e9ee5.jpg)
![10](https://user-images.githubusercontent.com/39652671/107765804-59f1b980-6d2a-11eb-886c-821975410a3e.jpg)

**Comment by timowen2** [comment]
HI

I have updated github with what I found, it is almost right

Tim

________________________________
