### ISSUE TITLE
Tags don't go away Bug

### ISSUE THREAD

**Issue by 123456789098767** [Librarika/Issues#648]
The software generates tags (and you can see them at OPAC), but on editing, there's nothing on the tags box. And if I try to delete a tag from the tags catalog, it says "Tag don't exist".

**Comment by jinia3636** [comment]
Please share some screenshots of your issue. 

In our system, you can add catalogs with tags in two ways. 
1. Bulk import - While importing records please provide your book tags on column Tags
2. Manual add - You have to manually provide your tags while adding your item.

In the case of Smart Add, you have to add the tags manually by editing the items.

Also, a tag is only removable from the item edit section. You can not delete any tag from the Catalogs -> Tags section.

**Comment by 123456789098767** [comment]
https://user-images.githubusercontent.com/78972041/109292471-537f3980-7822-11eb-8017-3f3b1f9a7884.mp4

Thats not what i am saying. Here is a video (20 sec) of my screen. Those tags just don't exist, they were automatically generated, i can do nothing with them. Thats a bug, right?

**Comment by jinia3636** [comment]
Yes, it was an issue from our side. However, we have already resolved it. When you add any new item this issue will not occur again. But in the case of, the old items you have to fix them manually.

Also, we have fixed this issue manually with the item that you have shared with us.
