### ISSUE TITLE
Barcodes pending in "Queued Status"

### ISSUE THREAD

**Issue by finisfun** [Librarika/Issues#660]
Hello Team - I had scheduled the barcodes to be generated quite some hours back. However, they are still in the queue. I need to generate around 1600 barcodes. Could you please help on how to get this done faster? URL as below for our library.
https://thebooklounge.librarika.com/barcode_labels

**Comment by finisfun** [comment]
The attached list contains all the barcodes which i wish to generate. Due to a problem with the file, the barcodes are in duplicate.
[barcode list.txt](https://github.com/Librarika/Issues/files/6998290/barcode.list.txt)

**Comment by rasel2001** [comment]
@finisfun You need to generate the barcode labels & print them. The free libraries can generate maximum of 100 labels at a time. After finishing first 100 you can queued and generate next 100 and then so on.

To learn more about barcode labels please visit https://docs.librarika.com/en/latest/barcode-labels/
