### ISSUE TITLE
QR codes

### ISSUE THREAD

**Issue by trunghtran2021** [Librarika/Issues#664]
Hello, 
I am new member and user to Librarika.  Has anyone try and successfully generate QR codes for the libraries?

Please comment and provide feedback (or articles) on how have you successfully integrate QR codes to your library.

Thank You So Much.

**Comment by jinia3636** [comment]
Librarika system does not generate QR codes. Only barcode labels are available for the library catalog and library members. For more details please check at https://docs.librarika.com/en/latest/barcode-labels/#barcode-labels
