### ISSUE TITLE
Scrolling refreshes the page when using website on mobile device

### ISSUE THREAD

**Issue by finisfun** [Librarika/Issues#665]
Hello team
When I access thebooklounge.Librarika.com site on my mobile or iPad, and as soon as I scroll down on a page, the page immediately refreshes instead of successfully scrolling down. This happens across pages on the site
This leads to the problem that it is not convenient to browse site and work as an admin on a mobile device. Please help. One of the pages you could check are the pages related to the list of members or books and when you click on the + sign to see details of one particular record and thereafter try to press the (eye) view icon by scrolling down on the page

**Comment by jinia3636** [comment]
Please use our web version if you are facing issues. If you are a library administrator then you can use our mobile apps.

**Comment by finisfun** [comment]
Dear Team
I was talking of problems with the desktop web version when using mobile devices.
I am already also using the app, but the features are limited in the same and hence I have to use the web version at times on my mobile device
Some limitations in the app being

When adding a book I cannot edit the properties (e.g. call number)

When adding a member I cannot select the type of member

Regards,
Sachin Garg
