### ISSUE TITLE
Duplicate Tags and Editing Tags en masse

### ISSUE THREAD

**Issue by dieterjanssen** [Librarika/Issues#667]
Within Librarika, there seem to be a lot of redundant tags which I did not create. Also, there are tags I'm hoping I can edit or delete and reassign to a series of books rather than editing each book individually. Is that possible?
 Several attempts to edit tags - change spelling, delete, etc. - have all lead to an interface that requires me to edit each book individually. At this point, that would take several hours.
 
 For example, there are several tags listed as "Photography". There's no difference in spelling, no hidden spaces, but two separate tags with books assigned to each. The slugs appear to be different, but I didn't generate those. Ideally this would be collapsed under one, otherwise the tag option isn't helpful.

Any ideas or steps I can take? Thanks so much!
 
![Librarika-MediaTags](https://user-images.githubusercontent.com/92032646/136203459-b7e53d1b-d9e5-4a08-b509-7ad4cdacee2f.png)

**Comment by jinia3636** [comment]
You can only delete those tags which do not have any catalog item under them. If any tags have catalog items under them and you want to remove those tags then you have to go to the Edit Media section and remove it from Tags field.

To learn more about tags please check our manual at https://docs.librarika.com/en/latest/cataloging/#tags
