### ISSUE TITLE
Facing issue during payment via paypal for upgrading my account

### ISSUE THREAD

**Issue by finisfun** [Librarika/Issues#669]
Hello Team - I am trying to upgrade my plan using the account thebooklounge.vistas@gmail.com. However, the payment is not proceeding further after entering the credit card details. It shows a blank screen only. I have tried this 3 times in the last 24 hours with the same result everytime. Is there any other alternate way to pay up. Also, I would prefer to pay using my Diners Credit Card which is moreover not an option on Paypal. For the transactions I tried since yesterday, I tried paying using the Visa card

**Comment by jinia3636** [comment]
We have already replied through email. Please kindly check your mailbox
