### ISSUE TITLE
Catalog search is bugged (?)

### ISSUE THREAD

**Issue by magnetar47** [Librarika/Issues#671]
Let's take the following situation:

- I first search the catalog for titles containing "Ocean".
- Then I go to a tag and list all the items containing that tag.
- The tag list is automatically filters only the items, with titles containing "Ocean".

To counter this bug, I'd have to go back to catalog search, empty the search field, trigger the search, and *then* go back to the tag listing and refresh the page.

It looks like the search input persists even when searching from elsewhere, and subsequently interfering with the results.

**Comment by jinia3636** [comment]
it's not a bug. You have to clear the search input in this case.

**Comment by magnetar47** [comment]
Hi @jinia3636, thanks for replying. In my humble opinion, having to manually clear the search input is indeed a bug. Let's take the situation outlined in the first post. What does listing items with a given tag have to do with a catalog search performed sometime earlier? Once I finish searching, I'd expect the search field to be automatically emptied. I'd be glad to filter the list if required, by providing more inputs via the search box, but I don't think it's a good idea to automatically filter the current listing by the **previous** search input. From our side, we've wasted quite a bit of time because of this, where we'd have manually searched for a book earlier, and then when we try to list the items under a category, or associated with a particular tag, we'd end up looking at an empty results page.

I would really like for the previous search input to be cleared, when I want to look at a tag/category list, **OR**, maybe there could be multiple independent searches, where different searches launched from different places don't mix up with each other. Please let me know your thoughts on these points. I'd love to collaborate with you people and look for a solution together, if you're up for it. :)
