### ISSUE TITLE
ISBN autofills with wrong book #, forces backspace

### ISSUE THREAD

**Issue by Kencinal** [Librarika/Issues#672]
I'm finding that when I begin typing an ISBN to "smart add" a book, Librarika autofills with some other ISBN, and any digits past the first are added to the end of this random ISBN.  I have to backspace through all but one digit (deleting all of them merely causes the problem to repeat when I begin typing), and *then* type the rest of the digits.  Quite a hassle!

**Comment by jinia3636** [comment]
You can use a different browser or you need to clear your browser cache. The old searched ISBN numbers are cached in your browser, that's why it's happening.
