### ISSUE TITLE
[Feature Request] Separate attribute for "Language"

### ISSUE THREAD

**Issue by magnetar47** [Librarika/Issues#674]
We're currently using tags for tagging books by language. I feel like it's an essential attribute of any book, and as such it would be nice if we have a separate attribute for language, like we do for ISBN, Publisher, etc.

Please feel free to discuss the pros and cons of this suggestion here. I'll be glad to provide more detail on different implementation-specific aspects of this feature if required.

**Comment by jinia3636** [comment]
Sorry, it's not possible for now but we will think about it in the future.

**Comment by magnetar47** [comment]
> Sorry, it's not possible for now but we will think about it in the future.

I'd really appreciate that, thanks.

May I request that this issue remains open until the feature is implemented? We could also continue to discuss finer implementation details, if you're okay with that.

****

Here's what I was thinking - we could have English as the default language, and if we want to have more languages, we could either have a pre-set list of languages, or we could have the language be "added" to the list of languages as and when needed, like how we handle authors and publishers at the moment. The advantage of the pre-set list is that we don't have to go through the actions of adding a new language and then selecting it. But the disadvantage is that the list has to either be very comprehensive, or it has to allow additions, to accommodate uncommon languages. What are your thoughts on this?
