### ISSUE TITLE
Last Action: You are not authorized to access that location is all I get from Librarika...

### ISSUE THREAD

**Issue by ghost** [Librarika/Issues#68]
Hello,

any time I want to do anything as the administrator of my library, I cannot.
I cannot add books or users or circulate anything or edit... Well, I am stuck doing nothing with the same message appearing at the top of the dashboard screen:
"Last Action: You are not authorized to access that location."

Ah, also, what on earth is an accession number?!

Thank you for help... any help!

Renee

**Comment by rayhan** [comment]
Marking this issue as closed, please re-open it if the problem is not fixed yet. Thanks
