### ISSUE TITLE
[Feature Request] Display cover images in catalogue search

### ISSUE THREAD

**Issue by magnetar47** [Librarika/Issues#681]
This is something that would be extremely helpful in our particular case, but may or may not apply to all libraries. We have different varieties of the same book, like different editions, different versions (paperback vs hardcover, etc.). So when we want to edit such items, I type the name in the search box and 20 different entries are displayed. I'll have to go through each entry to figure out which version/edition I'm looking for in particular. If the cover image is displayed as a thumbnail in the main search page (`<library>.librarika.com/media`), it would make our lives much easier when in this particular situation. But I believe this would be rather helpful even otherwise, so much so that I'd consider this a necessity.

**Comment by jinia3636** [comment]
Sorry, It's not possible to show cover images on catalog listing. Because it will slow down the system's performance.

**Comment by magnetar47** [comment]
Hi @jinia3636, do you have any other solutions in mind? Otherwise, would you be able to suggest some technique by which we can differentiate between different books of the same name in the catalog search, without having to open every single item? Is there a better way of cataloguing books to eliminate such circumstances?

> Sorry, It's not possible to show cover images on catalog listing. Because it will slow down the system's performance.

Your concern with regards to displaying cover image for a large number of books makes total sense and although it didn't occur to me before, I fully agree with you. But is it possible to display cover images if and only if the number of items returned by the search is less than `n`? We can decide on the value of `n` by testing with different values, and see how much is too much.
