### ISSUE TITLE
Auto-focus on first text field in a popup dialog

### ISSUE THREAD

**Issue by magnetar47** [Librarika/Issues#684]
I feel like this would be really useful. Every time I click on the smart-add button, after typing out the entire ISBN, I realise that the text field wasn't in focus. 😆

In my defence, I only expect the text field to be in focus because that's the default behaviour in many apps. So I'd humbly request this to be implemented in Librarika too. Thanks in advance.

**Comment by jinia3636** [comment]
We will think about it.

**Comment by magnetar47** [comment]
Thank you. Hope to see this roll out soon. :)
