### ISSUE TITLE
Import Errors : Title: Title is required.

### ISSUE THREAD

**Issue by pim50** [Librarika/Issues#686]
Hi,
When i try to import a csv file, I get the message Title is required. I used the sample document with a test of three books.
I tried it with Type addes (in the manual but not in the example file), I tried to import an exportfile from Librarika: all with the same result.
Import files are attached.
What can I do to make it work?
Thanks for your reaction

Pim
Library: tasjesbibliotheek

[test inlezen nieuwe boeken 3 uit export.csv](https://github.com/Librarika/Issues/files/8059859/test.inlezen.nieuwe.boeken.3.uit.export.csv)
[test inlezen nieuwe boeken 2.csv](https://github.com/Librarika/Issues/files/8059860/test.inlezen.nieuwe.boeken.2.csv)
[good reads format.csv](https://github.com/Librarika/Issues/files/8059863/good.reads.format.csv)
[test inlezen nieuwe boeken minimaal.csv](https://github.com/Librarika/Issues/files/8059864/test.inlezen.nieuwe.boeken.minimaal.csv)
.

**Comment by jinia3636** [comment]
Please send us any one of your CSV files via our contact us form https://librarika.com/spages/contact so that we can look into this.
