### ISSUE TITLE
Reports > Members > Mostly Engaged Problem

### ISSUE THREAD

**Issue by UCISLibrary** [Librarika/Issues#687]
When I choose the report stated in the title, it only shows me students who have checked out one or two books the entire year, not the students who actually use our library the most. 

Unsure this is a bug, but I'm wondering how the fix it and get the correct information!

**Comment by jinia3636** [comment]
Its not a bug. In our system the mostly engaged members reports shows those members who has maximum number of checkouts. That's mean the members who has checked out the items most.

**Comment by UCISLibrary** [comment]
That's not what it's doing? It's showing students with 1 check out. Why is
that?
