### ISSUE TITLE
bug: Smart Add creates duplicate categories

### ISSUE THREAD

**Issue by basklein** [Librarika/Issues#696]
I had set up my categories before importing any books. Then when I used Smart Add, I selected the correct category using the autocomplete prompt.

When I later tried to add some books with Manual Add, I noticed that there were now two additional categories with the same name, but a different slug as the original. All the books I had added were in the duplicate categories and the original was still at 0.

**Comment by jinia3636** [comment]
You can use the Bulk Actions method to move catalog items from one category to another category. To learn more about Bulk Actions please visit https://docs.librarika.com/en/latest/bulk-actions/#update-medias

Then you can delete the duplicate category from the list.

Our smart add method do not create duplicate category. You can add your category name from Categories section then choose that category on smart add form by overriding Unknown category. For more details please check our documentations Media section at https://docs.librarika.com/en/latest/cataloging/#media

**Comment by basklein** [comment]
But it does create a new category of the same name.

The top one is the original, which I selected in the Smart Add input field. The bottom one is the duplicate that was automatically created.

![Screenshot_2022-06-06-11-37-14-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/18082627/172085777-396f6ebd-58a3-4757-98c5-363d5066dfd3.jpg)
