### ISSUE TITLE
[Feature request] Automatically assigning Dewey Decimal

### ISSUE THREAD

**Issue by basklein** [Librarika/Issues#699]
I would like to request the implementation of a system that automatically provides new records with a Dewey Decimal classification number when applicable. For example by implementing the Classify API.

I'm currently manually adding the DDC to the Call no. field, but having a separate field for the DDC would be ideal.

**Comment by jinia3636** [comment]
Sorry, we don't have any functionality for the Dewey decimal number in our system. But we have plan to implement it in future releases.

Please note: We have two fields Location and Call No for the location of an item. You can use them for shelving your books.
