### ISSUE TITLE
Can't move copy to branch

### ISSUE THREAD

**Issue by gibson38cal** [Librarika/Issues#701]
Hello, 

I'm trying to move some copies of our books from the main library to a branch. However, when editing the item in the catalog, I get the following message: "The media copy could not be saved. Please, try again." This happens when also trying to location or edition information.

**Comment by jinia3636** [comment]
As one item can have multiple branches for it's copies so you can change the branch from the edit copy form. To do that please go to Dashboard -> Catalogs -> Catalog Items section. Locate the item you want to edit from your catalog and click on the View link on the right to that item. Navigate to the copies section at the bottom of the page. Click on the Edit link on right to that specific copy and then update your branch.

For more details, please follow the steps at https://docs.librarika.com/en/latest/cataloging/#edit-copy

**Comment by gibson38cal** [comment]
Yeah - I've been doing those exact steps, and that's where I get the error message.

**Comment by jinia3636** [comment]
Please send us your library URL via our contact us form https://librarika.com/spages/contact so that we can look into this.
