### ISSUE TITLE
The smart add function does not work

### ISSUE THREAD

**Issue by adivele** [Librarika/Issues#705]
Almost all my books are in Romanian. I tried to add them with the smart function, but it didn't work. I think I tried to add some books published in England and the US and it worked. What is the problem?

**Comment by jinia3636** [comment]
The smart add method gets book information from various sources using API but we can not guarantee that each ISBN can pull information from the internet correctly. Our API tries to find that book if it is available on the internet. In this case, you can use our manual add method or bulk import method. For more details please check our manual at https://docs.librarika.com/en/latest/cataloging/
