### ISSUE TITLE
problems displaying books when searching on the phone application

### ISSUE THREAD

**Issue by adivele** [Librarika/Issues#706]
When I do a catalog search on the phone app if there are more results, the last 2 I can't access, being covered by the keyboard.
It is necessary to be able to scroll and have access to the last 2 results.
![IMG_1363](https://user-images.githubusercontent.com/55286670/178967877-c09b4910-3df6-4edd-9860-b78ac1836a6e.PNG)

**Comment by jinia3636** [comment]
We have checked it from our end and the scroll is working properly. After completing the search please click on your keyboard's **Cautare** option then you can see the last 2 results.

**Comment by adivele** [comment]
Still not working.

https://user-images.githubusercontent.com/55286670/179183871-07a8ac0b-c42f-489e-aafb-8926d6e7b6ee.mp4

.

**Comment by jinia3636** [comment]
You can reinstall the app and try again.
