### ISSUE TITLE
Issue recovering my password

### ISSUE THREAD

**Issue by silviaroque** [Librarika/Issues#707]
Hi!

I don't get any email to recover my password.

1. I click: "Forgot Password"
2. I enter the email address I used to sign up.
3. I get the message "An email has been sent with instructions."

But I don't get any email.

Thank you in advance for any help.

Best regards.

Sílvia Martins

**Comment by jinia3636** [comment]
Please check thoroughly your mailboxes including spam/bin folders for the password reset emails.
