### ISSUE TITLE
No results found for any search, in catalogue admin or OPAC

### ISSUE THREAD

**Issue by SueJ60** [Librarika/Issues#708]
Hi,
Since yesterday afternoon, if you search for anything in either the catalogue admin or OPAC, no results are found. You can view the whole catalogue and view or edit items, but if the one you want to view is at the end of the catalogue this is very time-consuming and frustrating. For OPAC users this will be even more frustrating. Please can you investigate as a matter of urgency?
Our catalogue: https://banburyhistoricalsociety.librarika.com/search/newCollections
Thanks,
Sue

**Comment by jinia3636** [comment]
If the search is not working for Default option then please select other options like ID, Title, ISBN, Call No etc.

Please note: it may take a couple of hours for the newly added catalog to reflect the search results for default search. Also, for OPAC only the records enabled for OPAC will be displayed on OPAC.
