### ISSUE TITLE
RE: Librarika Glitch with 

### ISSUE THREAD

**Issue by yosefmelamed** [Librarika/Issues#713]
Trying to Set preferences in "Fees and Fines Settings" to turn off charging fees to library patrons but it doesn't work.
Push buttons to turn off and submit but when we go back in to settings its back on. 
Also is there a way to delete members fees in bulk rather than delete 1 by 1 ?

<img width="404" alt="image" src="https://user-images.githubusercontent.com/96746360/188786007-913d9cdc-b039-4a4f-8958-50f14bcefc4d.png">

**Comment by rasel2001** [comment]
@yosefmelamed We have resolved this issue.
