### ISSUE TITLE
Unable to search the Call No and Accession No from default in OPAC and admin default

### ISSUE THREAD

**Issue by synphanie** [Librarika/Issues#714]
I discover that I am not able to search the Call No and Accession No from default in OPAC on 21/7-6/9(yesterday). in addition, I am not able to search Call No and Accession No from Default of admin web as well.

Hope to hear any response as soon as possible.

Best regards,
Synphanie

**Comment by rasel2001** [comment]
@synphanie
We have resolved the issue. Can you please check once again?

**Comment by synphanie** [comment]
Hi, thank you for your response, the issue has been resolved, thank you
very much for your help.

Synphanie

**Comment by synphanie** [comment]
I couldn't search the books from yesterday what I key in again in OPAC
