### ISSUE TITLE
Smart Add results in error message

### ISSUE THREAD

**Issue by tjdickinson** [Librarika/Issues#722]
For the past day or so, when I try to use Smart Add, 95% of the time I get an error message. Occasionally it works, but usually not. The ISBN number is correct, so it's not that. I'm using Google Chrome, fully updated, and I already tried clearing cookies/cache/history/etc.

![image](https://user-images.githubusercontent.com/28570758/199286433-5277e5db-c521-4117-a334-4abce5f9a2e3.png)

**Comment by rasel2001** [comment]
@tjdickinson 

This issue **Error in processing data, please try again.** occurs when the API provides wrong data. You need to add that item manual.

There are three options for cataloging into your library -

    a. Smart Add - Where you can add books by their ISBN number from the internet but we do not guarantee that each ISBN can pull information from the internet correctly.
 
    b. Manual Add - You have to input all the details of your records manually.

    c. Bulk Import - You can add multiple records at a time from a CSV file.

Please contact us using our [contact us](https://librarika.com/spages/contact) from to quick response.
