### ISSUE TITLE
Catalog missing items and Search shows incorrect results

### ISSUE THREAD

**Issue by Bulungula** [Librarika/Issues#726]
1. Catalogue missing items.
Ive added 4 books - 1 automatically and 3 manually.
When I go to list the Catalog Items, I am shown 10 that are blank - only the unique id shows. All other fields are empty.
2 that I  added are shown - one is the automatically added book and the other a manual one.

2. Search of catalog items doesn't show correct results:
One of the successfully added catalog items doesn't show when I search by Author. 
When searching for anything, author, title, publisher etc ... the drop down for the selection is incorrect. 
3 titles come up (irrespective of  the search criteria) - 3 of which do not show on the catalog list. 2 Are titles I entered but have vanished. One an incorrectly spelled title.

Bulungula College

**Comment by rasel2001** [comment]
@Bulungula 
We have tried to regenerate the issue from the development server & our test libraries, but it is working fine. Can you please share with us the steps you have followed to add the items manually so that we can reproduce the issue & solve it as soon as possible?

You can use our contact us form to send the steps with data.

**Comment by Bulungula** [comment]
Hi there
I have recently had the library created and I tried a few times to add a
catalog item. Often going into Add a Publisher and Add an Author. Only
afterwards did I notice that records were either blank or missing. One
missing item was an auto create one. I had 10 "blank" catalog items which
is a bit worrying. I assume I can delete these and clean up.

What Ill do now is try a few more adds - making a note of the steps and ill
check the catalog items after each add.

Thanks for your speedy response.
Morag

**Comment by Bulungula** [comment]
---------- Forwarded message ---------
From: Morag Swanepoel ***@***.***>
Date: Mon, Mar 20, 2023 at 11:24 AM
Subject: Librerica Manual add Problems
To: ***@***.***>


In order to get around the problem wherd Category Items are addede with no
information, I've started to add Manual items without Adding Authors and
Publishers during the process. These i do via the edit function.

Errors ...
1) IBSN already exists but i am not adding the Title displayed.
Im adding The African Dustbin and its displaying a Maths book title (one of
the first ones added). See attachment.
2) Invald IBSN and it is valid and not for the Title being displayed... see
2 examples attached.
Thanks Morag Bell Swanepoel.
