### ISSUE TITLE
Issue with accents and bulk import

### ISSUE THREAD

**Issue by maroga** [Librarika/Issues#73]
When I try to import a .csv that contain accents or "ñ" character, these characters are changed to html (& aacute;, & ntilde;...) format and loaded this way in the catalog. In addition, when this happens in the author field, the ";" is considered as the character to separate authors and the name of the author is splitted in 2.

I have tried scaping the character in the file (& #241; for ñ for example) and, though in the confirmation page it is shown correctly, the full escape sequence is loaded in the catalog.  

I am using UTF-8 without BOM encoding in the file, since it is the only one that the import tool seems to recognize

Using manual load, I can correctly use accents and other characters. 

Is there any way to avoid this conversion and load a file with accents? 

Thank you in advance

Marga

**Comment by rayhan** [comment]
Hopefully this is solved by now.

**Comment by maroga** [comment]
Indeed. I have tested and is working.
Thank you

Marga
