### ISSUE TITLE
misspeled word 2

### ISSUE THREAD

**Issue by nb-tg** [Librarika/Issues#74]
![thesis](https://cloud.githubusercontent.com/assets/8760934/5034705/a495e0b8-6b71-11e4-80aa-990ad6a23eba.JPG)

thesis is not shown properly in Media

**Comment by ghostrigger** [comment]
also when viewing authors "Referances" instead of "References"

**Comment by rayhan** [comment]
Thanks for the suggestions. Should be fixed by now.
