### ISSUE TITLE
Missing books in the database that should be there 

### ISSUE THREAD

**Issue by paulUDIS** [Librarika/Issues#745]
In librarika I get the feeling that sometimes books just go missing out of the system. Occasionally I will check out a book and there is no trace of it in the system even though there is a barcode and the book looks like its been in the library for a while. Yesterday I had about 5 of these which was very frustrating. These are old books that look like they should be in the system but are not to be found. Does the system drop books that are not read or taken out of the library for a while? 
Paul

**Comment by rasel2001** [comment]
Please note that Librarika never deletes or alters customer records. Currently, your library contains 7157 catalog titles and 8982 catalog copies. You have the option to delete catalogs manually or using bulk actions from your end.

Please use the [contact us](https://librarika.com/spages/contact) form to send more details on your issue.
