### ISSUE TITLE
Adding a picture to the member file

### ISSUE THREAD

**Issue by paulUDIS** [Librarika/Issues#746]
Dear Support 
I would like to add a picture to the member file but every time I do nothing happens. Is there a size requirement? or a type (.jpg, png). I looked in the faq and other user docs and I could find nothing. 
Thank you 
Paul

**Comment by rasel2001** [comment]
Please note that only for manual additions, member photos can be uploaded, and the allowed file extensions are gif, jpg, jpeg, and png. Additionally, the photo should be at least 200x200 in size.
