### ISSUE TITLE
Some characters can not be searched 

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#75]
Words with letters Š, Č, Ž, Ň, Ď can not be searched in the catalog, they are not recognised by the system. This is quite a big issue in case of searching book titles beginning with these letters.

**Comment by rayhan** [comment]
Our next update will include solution for searching with these special characters, our apology for this temporary inconvenience .

**Comment by rayhan** [comment]
Hopefully this is fixed, please let us know if you still face the problem.
