### ISSUE TITLE
How do Memebers Request Books?

### ISSUE THREAD

**Issue by elrking** [Librarika/Issues#76]
Hi,

Recently I've moved my library over to Librarika, and enjoy the site, but have members complaining that they can't reserve books, so put them on hold. Is this possible for Librarika, and if so, how? Thanks!

**Comment by rayhan** [comment]
This feature is in progress and will be up shortly.

**Comment by rayhan** [comment]
From Manage -> Preferences you can enable members online book requests / self checkouts. 
After that, you members can request item form Catalog detail page using request or checkout button.
