### ISSUE TITLE
Back to Catalog Items - Suggestion

### ISSUE THREAD

**Issue by Murrel** [Librarika/Issues#78]
After editing a book (actually booking and inserting the Branch location), when I press the "Back to Catalog Items" to find the next book, I am returned to the top of the book list. If the book is on the next page or beyond I then have to page down through the rest of the books to get to the next book for processing. It would be more convenient if it would return to the list at the point it was left.

**Comment by 2manybooks** [comment]
I agree; this is very frustrating. I hope this is fixed.

**Comment by rayhan** [comment]
Unfortunately its a technical problem with many internet related sites, please try opening that edit page in a new browser tab, keeping your listing tab open. So once the edit is done, you can close that edit tab.

**Comment by 2manybooks** [comment]
This is the approach I've been using to get around this problem and it seems to be a good solution. Thanks.
