### ISSUE TITLE
automatic book addition is ineffective

### ISSUE THREAD

**Issue by badhrij** [Librarika/Issues#79]
While trying to import books using librarika csv format, the Author’s names are not automatically filled in. This makes automatic importing of books useless since we have to manually add author one by one.

Please ensure to automatically add author while importing the csv and/or enhance importing author list as csv instead of manual addition

**Comment by rayhan** [comment]
Hi, if you have author and coauthors filed properly set in CSV it automatically creates them for you. No need to manually add authors. http://ray.librarika.com/spages/import-items
