### ISSUE TITLE
add tags and description as part of librarika csv format

### ISSUE THREAD

**Issue by badhrij** [Librarika/Issues#80]
I would like to be able to add tags and description fields in the csv and import it seamlessly using librarika csv format.

**Comment by winamp-fan** [comment]
Agree, that would be helpful, in both import and export!

**Comment by sagarjoshi3183** [comment]
Any updates on the possibility of this feature?

**Comment by rayhan** [comment]
Yes, it will be added.

**Comment by rayhan** [comment]
Added. Thanks for reporting.

**Comment by badhrij** [comment]
Thanks.
But when I tried to add the below CSV. Now it shows "internal error". Is
this a mess up on my part or a bug in the tool?

:)
Badhri

thinkchangeindia.org
<http://social.yourstory.com/category/think-change-india/> ||
blacknike.blogspot.com ||
comedydaze.blogspot.com || ngopost.org ||

**Comment by rayhan** [comment]
Can you please email me the CSV file so that I can see what's wrong?

On Fri, Oct 30, 2015 at 8:02 PM, badhrij <notifications@github.com> wrote:

> Thanks.
> But when I tried to add the below CSV. Now it shows "internal error". Is
> this a mess up on my part or a bug in the tool?
>
> :)
> Badhri
>
> thinkchangeindia.org
> <http://social.yourstory.com/category/think-change-india/> ||
> blacknike.blogspot.com ||
> comedydaze.blogspot.com || ngopost.org ||
>
> On Mon, Oct 19, 2015 at 11:05 PM, Md. Rayhan Chowdhury <
> notifications@github.com> wrote:
>
> > Added. Thanks for reporting.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Librarika/Issues/issues/80#issuecomment-149291310>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/80#issuecomment-152534109>.
>



-- 
Rayhan
