### ISSUE TITLE
Can't link users to members

### ISSUE THREAD

**Issue by VinceyKapincey** [Librarika/Issues#84]
I'm trying to link a library member to a library user account. it seems to work with all other accounts except for this particular account. Is there a way to fix this or reset/delete all (or one) user accounts except for the administrator?

Thanks.

**Comment by rayhan** [comment]
Can you be more specific of which library are you trying with and which member and user do you want to connect with?

**Comment by rayhan** [comment]
Closing this point since there is no followup, please open the issue again if not already solved.
