### ISSUE TITLE
User Defined Fields

### ISSUE THREAD

**Issue by Murrel** [Librarika/Issues#85]
Are user defined fields available or should I convert a non-used field to record information that we need that doesn't apply to non-technical general library books? 

Possibly related, I don't understand the Tag fields. It might be possible to use tags instead, but I notice that some books added using the smart add function come with existing tags. Is there a place to look up what these existing tags mean? 

I can be quite flexible in the solution, but as our library is composed of materials from one discipline there are some designations we must be able to make.

Thanks
- Murrel

**Comment by rayhan** [comment]
User defined fields are not available at this moment. You can use a non-used field for that.

Tags are a group of topics that you can assign to each item. Smart Add gets tags from the source by default. You can also tag anything you like and search based on the tags.

Thanks
