### ISSUE TITLE
Search by ISBN 13

### ISSUE THREAD

**Issue by nikue** [Librarika/Issues#87]
Barcode scanners read ISBN 13 instead of ISBN, so it would be really helpful for this to be included in search, as for the moment we have to perform all searches manually. Love the site though! Excellent work so far. If a paid tier would help drive development, we'd be happy to contribute!

**Comment by rayhan** [comment]
This is fixed. Thanks for reporting.

**Comment by nikue** [comment]
Thanks a million!

Nikue Gardner
