### ISSUE TITLE
Auto-focus search fields

### ISSUE THREAD

**Issue by nikue** [Librarika/Issues#91]
Could the search field on the catalogue search pages get auto-focus when the page loads? This would make it much easier for those of us who use barcode readers. Thanks!

**Comment by rayhan** [comment]
Yes, I agree. Will be there.

**Comment by rayhan** [comment]
Done

**Comment by nikue** [comment]
Thanks! This is working for the "/search" and "/media" pages, but why not
the OPAC root page as well?

Nikue Gardner

**Comment by rayhan** [comment]
Yes, so it is now. :D

**Comment by nikue** [comment]
Thanks!

Nikue Gardner
