### ISSUE TITLE
Circulate by ISBN 10/13 rather than Accession #

### ISSUE THREAD

**Issue by nikue** [Librarika/Issues#93]
Would it be possible to circulation without using accession numbers? With just under 2000 books, it would be quite a task to print off numbers or bar codes for all of them. Perhaps circulation could be done by ISBN, with the system automaticaly choosing one of the un-checked out copies? Thanks!

**Comment by rayhan** [comment]
When doing circulation, you can try ISBN also, its multi-functional and will match ISBNs and suggest available copies to choose from. So, it should not be a problem now.
