### ISSUE TITLE
Sorry, member has reached their total booking quota.

### ISSUE THREAD

**Issue by davidhaines** [Librarika/Issues#94]
When trying to circulate an item I get the following message and I am unable to circulate the item.

**Comment by rayhan** [comment]
Please navigate to Dashboard -> Manage -> Preferences and update booking quotas and other settings, it will be ok. Thanks!

**Comment by davidhaines** [comment]
Thanks. I'm now seeing 'Sorry, member has already requested or checked out
this item' even though the item is not at present loaned out but when I
change the member it will let me loan the item.

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Did you check Overdue, Issued, Reserved & Pending tabs in circulation for this member?

**Comment by davidhaines** [comment]
I have just had a look and the member has no items Overdue, Reserved or
Pending. The do have four items Issued at present.

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Ok, please give me the information about the member and the item so that I can inspect more.

**Comment by davidhaines** [comment]
The member is number 18.

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Sorry, I also need the item you are going to loan them.

**Comment by davidhaines** [comment]
The items I am trying to loan out are Accession No's 3808 and 3809.

Thanks

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Please check here at https://newburyhall.librarika.com/members/view/1141, I see the member has already loaned this item. That's why its not letting you loan same item twice.

**Comment by davidhaines** [comment]
Hi

I can see that items 3806 and 3807 have been loaned out for this member but
not 3808 and 3809.

Thanks

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Yea, the idea is that the check is not based on copy, its based on title. If you have a book of same title, then why do you need to loan another copy of that same book. I might be wrong, if there is a valid reason, we can update the logic.

**Comment by davidhaines** [comment]
I am loaning text books out to a teacher and they have two copies of the
same title they wish to borrow.

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com

**Comment by rayhan** [comment]
Okey, that makes sense. You can try now, we will add a control for that policy later.

**Comment by davidhaines** [comment]
Brilliant. Thanks a lot!

Regards

David Haines
Literacy Coordinator/Teaching Assistant

Newbury Hall
Enborne Road
Newbury
Berkshire
RG14 6AD

Tel: +44 (0) 1635 36879 Fax: +44 (0) 1635 48400
Email: david.haines@newburyhall.com
