### ISSUE TITLE
Problem with checking out items

### ISSUE THREAD

**Issue by camcclure2483** [Librarika/Issues#96]
When I check out an item to a member, in the beginning a pop up box would appear where I could put in the member number and book accession number and there was no problem. Now, that pop up box has stopped appearing. Instead a new page is opened where I can put in the same information EXCEPT when I put the numbers in for the member number and book number, there is no more drop down box showing me the corresponding member name and book title for me to choose from. It's just the number in the text box and nothing else and it if I try to click Enter, a new page appears that says there was an error. It always works whenever the pop up box appears, but it never works when a full new page appears.

**Comment by rayhan** [comment]
Please let me know which browser and version are you using. Did you try using a latest version of chrome or firefox? Did you try clearing your browser cache?

Regards,
Rayhan

**Comment by camcclure2483** [comment]
I'm using chrome. I'll try clearing the browser cache. Thank you

Courtney

**Comment by camcclure2483** [comment]
clearing the browser cache worked. Thank you!!
Courtney 

     On Saturday, January 31, 2015 10:33 AM, Courtney Mcclure <camcclure2483@yahoo.com> wrote:
   

 I'm using chrome. I'll try clearing the browser cache. Thank you
Courtney

Sent from my iPad
On Jan 30, 2015, at 11:41 PM, "Md. Rayhan Chowdhury" <notifications@github.com> wrote:


Please let me know which browser and version are you using. Did you try using a latest version of chrome or firefox? Did you try clearing your browser cache?Regards,
Rayhan—
