### ISSUE TITLE
Special characters can not be recognized by the application

### ISSUE THREAD

**Issue by MonikaIness** [Librarika/Issues#97]
While searching for books or publications starting with the letter "Š", the application is not able to find these. While searching for catalog items starting with "A", the application is also recognizing item names starting with "Š".  It would be helpful to add these items with "Š", to the search results under "S". I would like to send you screenshots of the issue, so you can get a better view of the whole thing.It would be great, if you can send me an email, where I can attach the document. 

Thanks.

**Comment by rayhan** [comment]
Yes, it has to be solved. Thanks for reporting.

**Comment by MonikaIness** [comment]
Another issue:

![bug](https://cloud.githubusercontent.com/assets/10180177/6881100/15e63346-d551-11e4-88ce-c4fa0074e63b.jpg)

**Comment by rayhan** [comment]
The second bug about 11 hours ago has been fixed.
