### ISSUE TITLE
Member login

### ISSUE THREAD

**Issue by cadkins4** [Librarika/Issues#98]
Every time I try to login as a member, not an admin, it takes me to the dashboard and says I do not have access to anything there. That makes sense, but it won't allow me to go to the library. Why would that be? Is it because requests dont work yet? A setting issue?

Thank you for your help,
cadkins4

**Comment by rayhan** [comment]
Actually, we need to investigate this. keeping this point open until we reach a solution.

**Comment by am156** [comment]
So how can a member login? when i enter the member email account, it says the email isn't recognized. also what is the password for the member? they aren't prompted to enter anything

**Comment by rayhan** [comment]
Hi,

When you enable login option for member, member receives an email
invitation with instructions. You don't need to do anything for them, just
make sure that their email address are correct and email is not being block
by corporate firewall.

Thanks

Regards,
Rayhan

On Fri, Feb 27, 2015 at 9:16 AM, am156 <notifications@github.com> wrote:

> So how can a member login? when i enter the member email account, it says
> the email isn't recognized. also what is the password for the member? they
> aren't prompted to enter anything
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Librarika/Issues/issues/98#issuecomment-76324045>.
>



-- 
Rayhan
